// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTailRepository creates a new instance of MockTailRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTailRepository[ID comparable](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTailRepository[ID] {
	mock := &MockTailRepository[ID]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTailRepository is an autogenerated mock type for the TailRepository type
type MockTailRepository[ID comparable] struct {
	mock.Mock
}

type MockTailRepository_Expecter[ID comparable] struct {
	mock *mock.Mock
}

func (_m *MockTailRepository[ID]) EXPECT() *MockTailRepository_Expecter[ID] {
	return &MockTailRepository_Expecter[ID]{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockTailRepository
func (_mock *MockTailRepository[ID]) Delete(ctx context.Context, id ID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTailRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTailRepository_Delete_Call[ID comparable] struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id ID
func (_e *MockTailRepository_Expecter[ID]) Delete(ctx interface{}, id interface{}) *MockTailRepository_Delete_Call[ID] {
	return &MockTailRepository_Delete_Call[ID]{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockTailRepository_Delete_Call[ID]) Run(run func(ctx context.Context, id ID)) *MockTailRepository_Delete_Call[ID] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ID
		if args[1] != nil {
			arg1 = args[1].(ID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTailRepository_Delete_Call[ID]) Return(err error) *MockTailRepository_Delete_Call[ID] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTailRepository_Delete_Call[ID]) RunAndReturn(run func(ctx context.Context, id ID) error) *MockTailRepository_Delete_Call[ID] {
	_c.Call.Return(run)
	return _c
}

// GetTail provides a mock function for the type MockTailRepository
func (_mock *MockTailRepository[ID]) GetTail(ctx context.Context, tailDate time.Time) ([]ID, error) {
	ret := _mock.Called(ctx, tailDate)

	if len(ret) == 0 {
		panic("no return value specified for GetTail")
	}

	var r0 []ID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) ([]ID, error)); ok {
		return returnFunc(ctx, tailDate)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) []ID); ok {
		r0 = returnFunc(ctx, tailDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = returnFunc(ctx, tailDate)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTailRepository_GetTail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTail'
type MockTailRepository_GetTail_Call[ID comparable] struct {
	*mock.Call
}

// GetTail is a helper method to define mock.On call
//   - ctx context.Context
//   - tailDate time.Time
func (_e *MockTailRepository_Expecter[ID]) GetTail(ctx interface{}, tailDate interface{}) *MockTailRepository_GetTail_Call[ID] {
	return &MockTailRepository_GetTail_Call[ID]{Call: _e.mock.On("GetTail", ctx, tailDate)}
}

func (_c *MockTailRepository_GetTail_Call[ID]) Run(run func(ctx context.Context, tailDate time.Time)) *MockTailRepository_GetTail_Call[ID] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTailRepository_GetTail_Call[ID]) Return(vs []ID, err error) *MockTailRepository_GetTail_Call[ID] {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockTailRepository_GetTail_Call[ID]) RunAndReturn(run func(ctx context.Context, tailDate time.Time) ([]ID, error)) *MockTailRepository_GetTail_Call[ID] {
	_c.Call.Return(run)
	return _c
}
