// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/ElfAstAhe/tiny-audit-service/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDataAuditRepository creates a new instance of MockDataAuditRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDataAuditRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDataAuditRepository {
	mock := &MockDataAuditRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDataAuditRepository is an autogenerated mock type for the DataAuditRepository type
type MockDataAuditRepository struct {
	mock.Mock
}

type MockDataAuditRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDataAuditRepository) EXPECT() *MockDataAuditRepository_Expecter {
	return &MockDataAuditRepository_Expecter{mock: &_m.Mock}
}

// Change provides a mock function for the type MockDataAuditRepository
func (_mock *MockDataAuditRepository) Change(ctx context.Context, entity *domain.DataAudit) (*domain.DataAudit, error) {
	ret := _mock.Called(ctx, entity)

	if len(ret) == 0 {
		panic("no return value specified for Change")
	}

	var r0 *domain.DataAudit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.DataAudit) (*domain.DataAudit, error)); ok {
		return returnFunc(ctx, entity)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.DataAudit) *domain.DataAudit); ok {
		r0 = returnFunc(ctx, entity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.DataAudit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.DataAudit) error); ok {
		r1 = returnFunc(ctx, entity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDataAuditRepository_Change_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Change'
type MockDataAuditRepository_Change_Call struct {
	*mock.Call
}

// Change is a helper method to define mock.On call
//   - ctx context.Context
//   - entity *domain.DataAudit
func (_e *MockDataAuditRepository_Expecter) Change(ctx interface{}, entity interface{}) *MockDataAuditRepository_Change_Call {
	return &MockDataAuditRepository_Change_Call{Call: _e.mock.On("Change", ctx, entity)}
}

func (_c *MockDataAuditRepository_Change_Call) Run(run func(ctx context.Context, entity *domain.DataAudit)) *MockDataAuditRepository_Change_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.DataAudit
		if args[1] != nil {
			arg1 = args[1].(*domain.DataAudit)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDataAuditRepository_Change_Call) Return(dataAudit *domain.DataAudit, err error) *MockDataAuditRepository_Change_Call {
	_c.Call.Return(dataAudit, err)
	return _c
}

func (_c *MockDataAuditRepository_Change_Call) RunAndReturn(run func(ctx context.Context, entity *domain.DataAudit) (*domain.DataAudit, error)) *MockDataAuditRepository_Change_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockDataAuditRepository
func (_mock *MockDataAuditRepository) Create(ctx context.Context, entity *domain.DataAudit) (*domain.DataAudit, error) {
	ret := _mock.Called(ctx, entity)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.DataAudit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.DataAudit) (*domain.DataAudit, error)); ok {
		return returnFunc(ctx, entity)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.DataAudit) *domain.DataAudit); ok {
		r0 = returnFunc(ctx, entity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.DataAudit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.DataAudit) error); ok {
		r1 = returnFunc(ctx, entity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDataAuditRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockDataAuditRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - entity *domain.DataAudit
func (_e *MockDataAuditRepository_Expecter) Create(ctx interface{}, entity interface{}) *MockDataAuditRepository_Create_Call {
	return &MockDataAuditRepository_Create_Call{Call: _e.mock.On("Create", ctx, entity)}
}

func (_c *MockDataAuditRepository_Create_Call) Run(run func(ctx context.Context, entity *domain.DataAudit)) *MockDataAuditRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.DataAudit
		if args[1] != nil {
			arg1 = args[1].(*domain.DataAudit)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDataAuditRepository_Create_Call) Return(dataAudit *domain.DataAudit, err error) *MockDataAuditRepository_Create_Call {
	_c.Call.Return(dataAudit, err)
	return _c
}

func (_c *MockDataAuditRepository_Create_Call) RunAndReturn(run func(ctx context.Context, entity *domain.DataAudit) (*domain.DataAudit, error)) *MockDataAuditRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockDataAuditRepository
func (_mock *MockDataAuditRepository) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDataAuditRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockDataAuditRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockDataAuditRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockDataAuditRepository_Delete_Call {
	return &MockDataAuditRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockDataAuditRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockDataAuditRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDataAuditRepository_Delete_Call) Return(err error) *MockDataAuditRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDataAuditRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockDataAuditRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function for the type MockDataAuditRepository
func (_mock *MockDataAuditRepository) Find(ctx context.Context, id string) (*domain.DataAudit, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *domain.DataAudit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.DataAudit, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.DataAudit); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.DataAudit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDataAuditRepository_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockDataAuditRepository_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockDataAuditRepository_Expecter) Find(ctx interface{}, id interface{}) *MockDataAuditRepository_Find_Call {
	return &MockDataAuditRepository_Find_Call{Call: _e.mock.On("Find", ctx, id)}
}

func (_c *MockDataAuditRepository_Find_Call) Run(run func(ctx context.Context, id string)) *MockDataAuditRepository_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDataAuditRepository_Find_Call) Return(dataAudit *domain.DataAudit, err error) *MockDataAuditRepository_Find_Call {
	_c.Call.Return(dataAudit, err)
	return _c
}

func (_c *MockDataAuditRepository_Find_Call) RunAndReturn(run func(ctx context.Context, id string) (*domain.DataAudit, error)) *MockDataAuditRepository_Find_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockDataAuditRepository
func (_mock *MockDataAuditRepository) List(ctx context.Context, limit int, offset int) ([]*domain.DataAudit, error) {
	ret := _mock.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.DataAudit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]*domain.DataAudit, error)); ok {
		return returnFunc(ctx, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []*domain.DataAudit); ok {
		r0 = returnFunc(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.DataAudit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDataAuditRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockDataAuditRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockDataAuditRepository_Expecter) List(ctx interface{}, limit interface{}, offset interface{}) *MockDataAuditRepository_List_Call {
	return &MockDataAuditRepository_List_Call{Call: _e.mock.On("List", ctx, limit, offset)}
}

func (_c *MockDataAuditRepository_List_Call) Run(run func(ctx context.Context, limit int, offset int)) *MockDataAuditRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDataAuditRepository_List_Call) Return(dataAudits []*domain.DataAudit, err error) *MockDataAuditRepository_List_Call {
	_c.Call.Return(dataAudits, err)
	return _c
}

func (_c *MockDataAuditRepository_List_Call) RunAndReturn(run func(ctx context.Context, limit int, offset int) ([]*domain.DataAudit, error)) *MockDataAuditRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListByInstance provides a mock function for the type MockDataAuditRepository
func (_mock *MockDataAuditRepository) ListByInstance(ctx context.Context, typeName string, instanceID string, limit int, offset int) ([]*domain.DataAudit, error) {
	ret := _mock.Called(ctx, typeName, instanceID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListByInstance")
	}

	var r0 []*domain.DataAudit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int, int) ([]*domain.DataAudit, error)); ok {
		return returnFunc(ctx, typeName, instanceID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int, int) []*domain.DataAudit); ok {
		r0 = returnFunc(ctx, typeName, instanceID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.DataAudit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, int, int) error); ok {
		r1 = returnFunc(ctx, typeName, instanceID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDataAuditRepository_ListByInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByInstance'
type MockDataAuditRepository_ListByInstance_Call struct {
	*mock.Call
}

// ListByInstance is a helper method to define mock.On call
//   - ctx context.Context
//   - typeName string
//   - instanceID string
//   - limit int
//   - offset int
func (_e *MockDataAuditRepository_Expecter) ListByInstance(ctx interface{}, typeName interface{}, instanceID interface{}, limit interface{}, offset interface{}) *MockDataAuditRepository_ListByInstance_Call {
	return &MockDataAuditRepository_ListByInstance_Call{Call: _e.mock.On("ListByInstance", ctx, typeName, instanceID, limit, offset)}
}

func (_c *MockDataAuditRepository_ListByInstance_Call) Run(run func(ctx context.Context, typeName string, instanceID string, limit int, offset int)) *MockDataAuditRepository_ListByInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockDataAuditRepository_ListByInstance_Call) Return(dataAudits []*domain.DataAudit, err error) *MockDataAuditRepository_ListByInstance_Call {
	_c.Call.Return(dataAudits, err)
	return _c
}

func (_c *MockDataAuditRepository_ListByInstance_Call) RunAndReturn(run func(ctx context.Context, typeName string, instanceID string, limit int, offset int) ([]*domain.DataAudit, error)) *MockDataAuditRepository_ListByInstance_Call {
	_c.Call.Return(run)
	return _c
}

// ListByPeriod provides a mock function for the type MockDataAuditRepository
func (_mock *MockDataAuditRepository) ListByPeriod(ctx context.Context, from time.Time, till time.Time, limit int, offset int) ([]*domain.DataAudit, error) {
	ret := _mock.Called(ctx, from, till, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListByPeriod")
	}

	var r0 []*domain.DataAudit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, time.Time, int, int) ([]*domain.DataAudit, error)); ok {
		return returnFunc(ctx, from, till, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, time.Time, int, int) []*domain.DataAudit); ok {
		r0 = returnFunc(ctx, from, till, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.DataAudit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time, time.Time, int, int) error); ok {
		r1 = returnFunc(ctx, from, till, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDataAuditRepository_ListByPeriod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByPeriod'
type MockDataAuditRepository_ListByPeriod_Call struct {
	*mock.Call
}

// ListByPeriod is a helper method to define mock.On call
//   - ctx context.Context
//   - from time.Time
//   - till time.Time
//   - limit int
//   - offset int
func (_e *MockDataAuditRepository_Expecter) ListByPeriod(ctx interface{}, from interface{}, till interface{}, limit interface{}, offset interface{}) *MockDataAuditRepository_ListByPeriod_Call {
	return &MockDataAuditRepository_ListByPeriod_Call{Call: _e.mock.On("ListByPeriod", ctx, from, till, limit, offset)}
}

func (_c *MockDataAuditRepository_ListByPeriod_Call) Run(run func(ctx context.Context, from time.Time, till time.Time, limit int, offset int)) *MockDataAuditRepository_ListByPeriod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockDataAuditRepository_ListByPeriod_Call) Return(dataAudits []*domain.DataAudit, err error) *MockDataAuditRepository_ListByPeriod_Call {
	_c.Call.Return(dataAudits, err)
	return _c
}

func (_c *MockDataAuditRepository_ListByPeriod_Call) RunAndReturn(run func(ctx context.Context, from time.Time, till time.Time, limit int, offset int) ([]*domain.DataAudit, error)) *MockDataAuditRepository_ListByPeriod_Call {
	_c.Call.Return(run)
	return _c
}
