// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// newMockcommonAudit creates a new instance of mockcommonAudit. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockcommonAudit(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockcommonAudit {
	mock := &mockcommonAudit{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockcommonAudit is an autogenerated mock type for the commonAudit type
type mockcommonAudit struct {
	mock.Mock
}

type mockcommonAudit_Expecter struct {
	mock *mock.Mock
}

func (_m *mockcommonAudit) EXPECT() *mockcommonAudit_Expecter {
	return &mockcommonAudit_Expecter{mock: &_m.Mock}
}

// GetEvent provides a mock function for the type mockcommonAudit
func (_mock *mockcommonAudit) GetEvent() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEvent")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// mockcommonAudit_GetEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEvent'
type mockcommonAudit_GetEvent_Call struct {
	*mock.Call
}

// GetEvent is a helper method to define mock.On call
func (_e *mockcommonAudit_Expecter) GetEvent() *mockcommonAudit_GetEvent_Call {
	return &mockcommonAudit_GetEvent_Call{Call: _e.mock.On("GetEvent")}
}

func (_c *mockcommonAudit_GetEvent_Call) Run(run func()) *mockcommonAudit_GetEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockcommonAudit_GetEvent_Call) Return(s string) *mockcommonAudit_GetEvent_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *mockcommonAudit_GetEvent_Call) RunAndReturn(run func() string) *mockcommonAudit_GetEvent_Call {
	_c.Call.Return(run)
	return _c
}

// GetEventDate provides a mock function for the type mockcommonAudit
func (_mock *mockcommonAudit) GetEventDate() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEventDate")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// mockcommonAudit_GetEventDate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEventDate'
type mockcommonAudit_GetEventDate_Call struct {
	*mock.Call
}

// GetEventDate is a helper method to define mock.On call
func (_e *mockcommonAudit_Expecter) GetEventDate() *mockcommonAudit_GetEventDate_Call {
	return &mockcommonAudit_GetEventDate_Call{Call: _e.mock.On("GetEventDate")}
}

func (_c *mockcommonAudit_GetEventDate_Call) Run(run func()) *mockcommonAudit_GetEventDate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockcommonAudit_GetEventDate_Call) Return(time1 time.Time) *mockcommonAudit_GetEventDate_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *mockcommonAudit_GetEventDate_Call) RunAndReturn(run func() time.Time) *mockcommonAudit_GetEventDate_Call {
	_c.Call.Return(run)
	return _c
}

// GetRequestID provides a mock function for the type mockcommonAudit
func (_mock *mockcommonAudit) GetRequestID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRequestID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// mockcommonAudit_GetRequestID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRequestID'
type mockcommonAudit_GetRequestID_Call struct {
	*mock.Call
}

// GetRequestID is a helper method to define mock.On call
func (_e *mockcommonAudit_Expecter) GetRequestID() *mockcommonAudit_GetRequestID_Call {
	return &mockcommonAudit_GetRequestID_Call{Call: _e.mock.On("GetRequestID")}
}

func (_c *mockcommonAudit_GetRequestID_Call) Run(run func()) *mockcommonAudit_GetRequestID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockcommonAudit_GetRequestID_Call) Return(s string) *mockcommonAudit_GetRequestID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *mockcommonAudit_GetRequestID_Call) RunAndReturn(run func() string) *mockcommonAudit_GetRequestID_Call {
	_c.Call.Return(run)
	return _c
}

// GetSource provides a mock function for the type mockcommonAudit
func (_mock *mockcommonAudit) GetSource() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSource")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// mockcommonAudit_GetSource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSource'
type mockcommonAudit_GetSource_Call struct {
	*mock.Call
}

// GetSource is a helper method to define mock.On call
func (_e *mockcommonAudit_Expecter) GetSource() *mockcommonAudit_GetSource_Call {
	return &mockcommonAudit_GetSource_Call{Call: _e.mock.On("GetSource")}
}

func (_c *mockcommonAudit_GetSource_Call) Run(run func()) *mockcommonAudit_GetSource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockcommonAudit_GetSource_Call) Return(s string) *mockcommonAudit_GetSource_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *mockcommonAudit_GetSource_Call) RunAndReturn(run func() string) *mockcommonAudit_GetSource_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatus provides a mock function for the type mockcommonAudit
func (_mock *mockcommonAudit) GetStatus() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetStatus")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// mockcommonAudit_GetStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatus'
type mockcommonAudit_GetStatus_Call struct {
	*mock.Call
}

// GetStatus is a helper method to define mock.On call
func (_e *mockcommonAudit_Expecter) GetStatus() *mockcommonAudit_GetStatus_Call {
	return &mockcommonAudit_GetStatus_Call{Call: _e.mock.On("GetStatus")}
}

func (_c *mockcommonAudit_GetStatus_Call) Run(run func()) *mockcommonAudit_GetStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockcommonAudit_GetStatus_Call) Return(s string) *mockcommonAudit_GetStatus_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *mockcommonAudit_GetStatus_Call) RunAndReturn(run func() string) *mockcommonAudit_GetStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsername provides a mock function for the type mockcommonAudit
func (_mock *mockcommonAudit) GetUsername() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUsername")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// mockcommonAudit_GetUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsername'
type mockcommonAudit_GetUsername_Call struct {
	*mock.Call
}

// GetUsername is a helper method to define mock.On call
func (_e *mockcommonAudit_Expecter) GetUsername() *mockcommonAudit_GetUsername_Call {
	return &mockcommonAudit_GetUsername_Call{Call: _e.mock.On("GetUsername")}
}

func (_c *mockcommonAudit_GetUsername_Call) Run(run func()) *mockcommonAudit_GetUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockcommonAudit_GetUsername_Call) Return(s string) *mockcommonAudit_GetUsername_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *mockcommonAudit_GetUsername_Call) RunAndReturn(run func() string) *mockcommonAudit_GetUsername_Call {
	_c.Call.Return(run)
	return _c
}
