// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/ElfAstAhe/tiny-audit-service/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthAuditRepository creates a new instance of MockAuthAuditRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthAuditRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthAuditRepository {
	mock := &MockAuthAuditRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthAuditRepository is an autogenerated mock type for the AuthAuditRepository type
type MockAuthAuditRepository struct {
	mock.Mock
}

type MockAuthAuditRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthAuditRepository) EXPECT() *MockAuthAuditRepository_Expecter {
	return &MockAuthAuditRepository_Expecter{mock: &_m.Mock}
}

// Change provides a mock function for the type MockAuthAuditRepository
func (_mock *MockAuthAuditRepository) Change(ctx context.Context, entity *domain.AuthAudit) (*domain.AuthAudit, error) {
	ret := _mock.Called(ctx, entity)

	if len(ret) == 0 {
		panic("no return value specified for Change")
	}

	var r0 *domain.AuthAudit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuthAudit) (*domain.AuthAudit, error)); ok {
		return returnFunc(ctx, entity)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuthAudit) *domain.AuthAudit); ok {
		r0 = returnFunc(ctx, entity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AuthAudit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.AuthAudit) error); ok {
		r1 = returnFunc(ctx, entity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthAuditRepository_Change_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Change'
type MockAuthAuditRepository_Change_Call struct {
	*mock.Call
}

// Change is a helper method to define mock.On call
//   - ctx context.Context
//   - entity *domain.AuthAudit
func (_e *MockAuthAuditRepository_Expecter) Change(ctx interface{}, entity interface{}) *MockAuthAuditRepository_Change_Call {
	return &MockAuthAuditRepository_Change_Call{Call: _e.mock.On("Change", ctx, entity)}
}

func (_c *MockAuthAuditRepository_Change_Call) Run(run func(ctx context.Context, entity *domain.AuthAudit)) *MockAuthAuditRepository_Change_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.AuthAudit
		if args[1] != nil {
			arg1 = args[1].(*domain.AuthAudit)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthAuditRepository_Change_Call) Return(authAudit *domain.AuthAudit, err error) *MockAuthAuditRepository_Change_Call {
	_c.Call.Return(authAudit, err)
	return _c
}

func (_c *MockAuthAuditRepository_Change_Call) RunAndReturn(run func(ctx context.Context, entity *domain.AuthAudit) (*domain.AuthAudit, error)) *MockAuthAuditRepository_Change_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockAuthAuditRepository
func (_mock *MockAuthAuditRepository) Create(ctx context.Context, entity *domain.AuthAudit) (*domain.AuthAudit, error) {
	ret := _mock.Called(ctx, entity)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.AuthAudit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuthAudit) (*domain.AuthAudit, error)); ok {
		return returnFunc(ctx, entity)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuthAudit) *domain.AuthAudit); ok {
		r0 = returnFunc(ctx, entity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AuthAudit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.AuthAudit) error); ok {
		r1 = returnFunc(ctx, entity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthAuditRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAuthAuditRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - entity *domain.AuthAudit
func (_e *MockAuthAuditRepository_Expecter) Create(ctx interface{}, entity interface{}) *MockAuthAuditRepository_Create_Call {
	return &MockAuthAuditRepository_Create_Call{Call: _e.mock.On("Create", ctx, entity)}
}

func (_c *MockAuthAuditRepository_Create_Call) Run(run func(ctx context.Context, entity *domain.AuthAudit)) *MockAuthAuditRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.AuthAudit
		if args[1] != nil {
			arg1 = args[1].(*domain.AuthAudit)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthAuditRepository_Create_Call) Return(authAudit *domain.AuthAudit, err error) *MockAuthAuditRepository_Create_Call {
	_c.Call.Return(authAudit, err)
	return _c
}

func (_c *MockAuthAuditRepository_Create_Call) RunAndReturn(run func(ctx context.Context, entity *domain.AuthAudit) (*domain.AuthAudit, error)) *MockAuthAuditRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockAuthAuditRepository
func (_mock *MockAuthAuditRepository) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthAuditRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockAuthAuditRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockAuthAuditRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockAuthAuditRepository_Delete_Call {
	return &MockAuthAuditRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockAuthAuditRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockAuthAuditRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthAuditRepository_Delete_Call) Return(err error) *MockAuthAuditRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthAuditRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockAuthAuditRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function for the type MockAuthAuditRepository
func (_mock *MockAuthAuditRepository) Find(ctx context.Context, id string) (*domain.AuthAudit, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *domain.AuthAudit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.AuthAudit, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.AuthAudit); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AuthAudit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthAuditRepository_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockAuthAuditRepository_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockAuthAuditRepository_Expecter) Find(ctx interface{}, id interface{}) *MockAuthAuditRepository_Find_Call {
	return &MockAuthAuditRepository_Find_Call{Call: _e.mock.On("Find", ctx, id)}
}

func (_c *MockAuthAuditRepository_Find_Call) Run(run func(ctx context.Context, id string)) *MockAuthAuditRepository_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthAuditRepository_Find_Call) Return(authAudit *domain.AuthAudit, err error) *MockAuthAuditRepository_Find_Call {
	_c.Call.Return(authAudit, err)
	return _c
}

func (_c *MockAuthAuditRepository_Find_Call) RunAndReturn(run func(ctx context.Context, id string) (*domain.AuthAudit, error)) *MockAuthAuditRepository_Find_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockAuthAuditRepository
func (_mock *MockAuthAuditRepository) List(ctx context.Context, limit int, offset int) ([]*domain.AuthAudit, error) {
	ret := _mock.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.AuthAudit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]*domain.AuthAudit, error)); ok {
		return returnFunc(ctx, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []*domain.AuthAudit); ok {
		r0 = returnFunc(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.AuthAudit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthAuditRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockAuthAuditRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockAuthAuditRepository_Expecter) List(ctx interface{}, limit interface{}, offset interface{}) *MockAuthAuditRepository_List_Call {
	return &MockAuthAuditRepository_List_Call{Call: _e.mock.On("List", ctx, limit, offset)}
}

func (_c *MockAuthAuditRepository_List_Call) Run(run func(ctx context.Context, limit int, offset int)) *MockAuthAuditRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuthAuditRepository_List_Call) Return(authAudits []*domain.AuthAudit, err error) *MockAuthAuditRepository_List_Call {
	_c.Call.Return(authAudits, err)
	return _c
}

func (_c *MockAuthAuditRepository_List_Call) RunAndReturn(run func(ctx context.Context, limit int, offset int) ([]*domain.AuthAudit, error)) *MockAuthAuditRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListByPeriod provides a mock function for the type MockAuthAuditRepository
func (_mock *MockAuthAuditRepository) ListByPeriod(ctx context.Context, from time.Time, till time.Time, limit int, offset int) ([]*domain.AuthAudit, error) {
	ret := _mock.Called(ctx, from, till, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListByPeriod")
	}

	var r0 []*domain.AuthAudit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, time.Time, int, int) ([]*domain.AuthAudit, error)); ok {
		return returnFunc(ctx, from, till, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, time.Time, int, int) []*domain.AuthAudit); ok {
		r0 = returnFunc(ctx, from, till, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.AuthAudit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time, time.Time, int, int) error); ok {
		r1 = returnFunc(ctx, from, till, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthAuditRepository_ListByPeriod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByPeriod'
type MockAuthAuditRepository_ListByPeriod_Call struct {
	*mock.Call
}

// ListByPeriod is a helper method to define mock.On call
//   - ctx context.Context
//   - from time.Time
//   - till time.Time
//   - limit int
//   - offset int
func (_e *MockAuthAuditRepository_Expecter) ListByPeriod(ctx interface{}, from interface{}, till interface{}, limit interface{}, offset interface{}) *MockAuthAuditRepository_ListByPeriod_Call {
	return &MockAuthAuditRepository_ListByPeriod_Call{Call: _e.mock.On("ListByPeriod", ctx, from, till, limit, offset)}
}

func (_c *MockAuthAuditRepository_ListByPeriod_Call) Run(run func(ctx context.Context, from time.Time, till time.Time, limit int, offset int)) *MockAuthAuditRepository_ListByPeriod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockAuthAuditRepository_ListByPeriod_Call) Return(authAudits []*domain.AuthAudit, err error) *MockAuthAuditRepository_ListByPeriod_Call {
	_c.Call.Return(authAudits, err)
	return _c
}

func (_c *MockAuthAuditRepository_ListByPeriod_Call) RunAndReturn(run func(ctx context.Context, from time.Time, till time.Time, limit int, offset int) ([]*domain.AuthAudit, error)) *MockAuthAuditRepository_ListByPeriod_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUsername provides a mock function for the type MockAuthAuditRepository
func (_mock *MockAuthAuditRepository) ListByUsername(ctx context.Context, username string, offset int, limit int) ([]*domain.AuthAudit, error) {
	ret := _mock.Called(ctx, username, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListByUsername")
	}

	var r0 []*domain.AuthAudit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) ([]*domain.AuthAudit, error)); ok {
		return returnFunc(ctx, username, offset, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) []*domain.AuthAudit); ok {
		r0 = returnFunc(ctx, username, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.AuthAudit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = returnFunc(ctx, username, offset, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthAuditRepository_ListByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUsername'
type MockAuthAuditRepository_ListByUsername_Call struct {
	*mock.Call
}

// ListByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - offset int
//   - limit int
func (_e *MockAuthAuditRepository_Expecter) ListByUsername(ctx interface{}, username interface{}, offset interface{}, limit interface{}) *MockAuthAuditRepository_ListByUsername_Call {
	return &MockAuthAuditRepository_ListByUsername_Call{Call: _e.mock.On("ListByUsername", ctx, username, offset, limit)}
}

func (_c *MockAuthAuditRepository_ListByUsername_Call) Run(run func(ctx context.Context, username string, offset int, limit int)) *MockAuthAuditRepository_ListByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAuthAuditRepository_ListByUsername_Call) Return(authAudits []*domain.AuthAudit, err error) *MockAuthAuditRepository_ListByUsername_Call {
	_c.Call.Return(authAudits, err)
	return _c
}

func (_c *MockAuthAuditRepository_ListByUsername_Call) RunAndReturn(run func(ctx context.Context, username string, offset int, limit int) ([]*domain.AuthAudit, error)) *MockAuthAuditRepository_ListByUsername_Call {
	_c.Call.Return(run)
	return _c
}
