// Code generated by go-swagger; DO NOT EDIT.

package audit

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new audit API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new audit API client with basic auth credentials.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new audit API client with a bearer token for authentication.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for audit API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	PostAPIV1AuditAuth(params *PostAPIV1AuditAuthParams, opts ...ClientOption) (*PostAPIV1AuditAuthCreated, error)

	PostAPIV1AuditAuthPeriod(params *PostAPIV1AuditAuthPeriodParams, opts ...ClientOption) (*PostAPIV1AuditAuthPeriodOK, error)

	PostAPIV1AuditData(params *PostAPIV1AuditDataParams, opts ...ClientOption) (*PostAPIV1AuditDataCreated, error)

	PostAPIV1AuditDataInstance(params *PostAPIV1AuditDataInstanceParams, opts ...ClientOption) (*PostAPIV1AuditDataInstanceOK, error)

	PostAPIV1AuditDataPeriod(params *PostAPIV1AuditDataPeriodParams, opts ...ClientOption) (*PostAPIV1AuditDataPeriodOK, error)

	PostAPIV1AuditDataUsername(params *PostAPIV1AuditDataUsernameParams, opts ...ClientOption) (*PostAPIV1AuditDataUsernameOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
PostAPIV1AuditAuth аудитs аутентификации и авторизации

Создание новой записи аудита
*/
func (a *Client) PostAPIV1AuditAuth(params *PostAPIV1AuditAuthParams, opts ...ClientOption) (*PostAPIV1AuditAuthCreated, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostAPIV1AuditAuthParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostAPIV1AuditAuth",
		Method:             "POST",
		PathPattern:        "/api/v1/audit/auth",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostAPIV1AuditAuthReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostAPIV1AuditAuthCreated)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostAPIV1AuditAuth: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PostAPIV1AuditAuthPeriod списокs аудита аутентификации в разрезе периода

Получить список аудита аутентификации в разрезе периода
*/
func (a *Client) PostAPIV1AuditAuthPeriod(params *PostAPIV1AuditAuthPeriodParams, opts ...ClientOption) (*PostAPIV1AuditAuthPeriodOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostAPIV1AuditAuthPeriodParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostAPIV1AuditAuthPeriod",
		Method:             "POST",
		PathPattern:        "/api/v1/audit/auth/period",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostAPIV1AuditAuthPeriodReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostAPIV1AuditAuthPeriodOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostAPIV1AuditAuthPeriod: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PostAPIV1AuditData аудитs данных

Создание новой записи аудита
*/
func (a *Client) PostAPIV1AuditData(params *PostAPIV1AuditDataParams, opts ...ClientOption) (*PostAPIV1AuditDataCreated, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostAPIV1AuditDataParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostAPIV1AuditData",
		Method:             "POST",
		PathPattern:        "/api/v1/audit/data",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostAPIV1AuditDataReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostAPIV1AuditDataCreated)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostAPIV1AuditData: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PostAPIV1AuditDataInstance списокs аудита данных в разрезе инстанса данных

Получить список аудита данных в разрезе инстанса данных
*/
func (a *Client) PostAPIV1AuditDataInstance(params *PostAPIV1AuditDataInstanceParams, opts ...ClientOption) (*PostAPIV1AuditDataInstanceOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostAPIV1AuditDataInstanceParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostAPIV1AuditDataInstance",
		Method:             "POST",
		PathPattern:        "/api/v1/audit/data/instance",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostAPIV1AuditDataInstanceReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostAPIV1AuditDataInstanceOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostAPIV1AuditDataInstance: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PostAPIV1AuditDataPeriod списокs аудита данных в разрезе периода

Получить список аудита данных в разрезе периода
*/
func (a *Client) PostAPIV1AuditDataPeriod(params *PostAPIV1AuditDataPeriodParams, opts ...ClientOption) (*PostAPIV1AuditDataPeriodOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostAPIV1AuditDataPeriodParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostAPIV1AuditDataPeriod",
		Method:             "POST",
		PathPattern:        "/api/v1/audit/data/period",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostAPIV1AuditDataPeriodReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostAPIV1AuditDataPeriodOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostAPIV1AuditDataPeriod: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PostAPIV1AuditDataUsername списокs аудита данных в разрезе пользователя

Получить список аудита данных в разрезе пользователя
*/
func (a *Client) PostAPIV1AuditDataUsername(params *PostAPIV1AuditDataUsernameParams, opts ...ClientOption) (*PostAPIV1AuditDataUsernameOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostAPIV1AuditDataUsernameParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostAPIV1AuditDataUsername",
		Method:             "POST",
		PathPattern:        "/api/v1/audit/data/username",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostAPIV1AuditDataUsernameReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostAPIV1AuditDataUsernameOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostAPIV1AuditDataUsername: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
