// Code generated by go-swagger; DO NOT EDIT.

package audit

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/ElfAstAhe/tiny-audit-service/pkg/api/http/audit/v1/models"
)

// NewPostAPIV1AuditAuthPeriodParams creates a new PostAPIV1AuditAuthPeriodParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPIV1AuditAuthPeriodParams() *PostAPIV1AuditAuthPeriodParams {
	return &PostAPIV1AuditAuthPeriodParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIV1AuditAuthPeriodParamsWithTimeout creates a new PostAPIV1AuditAuthPeriodParams object
// with the ability to set a timeout on a request.
func NewPostAPIV1AuditAuthPeriodParamsWithTimeout(timeout time.Duration) *PostAPIV1AuditAuthPeriodParams {
	return &PostAPIV1AuditAuthPeriodParams{
		timeout: timeout,
	}
}

// NewPostAPIV1AuditAuthPeriodParamsWithContext creates a new PostAPIV1AuditAuthPeriodParams object
// with the ability to set a context for a request.
func NewPostAPIV1AuditAuthPeriodParamsWithContext(ctx context.Context) *PostAPIV1AuditAuthPeriodParams {
	return &PostAPIV1AuditAuthPeriodParams{
		Context: ctx,
	}
}

// NewPostAPIV1AuditAuthPeriodParamsWithHTTPClient creates a new PostAPIV1AuditAuthPeriodParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPIV1AuditAuthPeriodParamsWithHTTPClient(client *http.Client) *PostAPIV1AuditAuthPeriodParams {
	return &PostAPIV1AuditAuthPeriodParams{
		HTTPClient: client,
	}
}

/*
PostAPIV1AuditAuthPeriodParams contains all the parameters to send to the API endpoint

	for the post API v1 audit auth period operation.

	Typically these are written to a http.Request.
*/
type PostAPIV1AuditAuthPeriodParams struct {

	/* Input.

	   Период аудита
	*/
	Input *models.AuditPeriodDTO

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post API v1 audit auth period params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIV1AuditAuthPeriodParams) WithDefaults() *PostAPIV1AuditAuthPeriodParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post API v1 audit auth period params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIV1AuditAuthPeriodParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post API v1 audit auth period params
func (o *PostAPIV1AuditAuthPeriodParams) WithTimeout(timeout time.Duration) *PostAPIV1AuditAuthPeriodParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API v1 audit auth period params
func (o *PostAPIV1AuditAuthPeriodParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API v1 audit auth period params
func (o *PostAPIV1AuditAuthPeriodParams) WithContext(ctx context.Context) *PostAPIV1AuditAuthPeriodParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API v1 audit auth period params
func (o *PostAPIV1AuditAuthPeriodParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API v1 audit auth period params
func (o *PostAPIV1AuditAuthPeriodParams) WithHTTPClient(client *http.Client) *PostAPIV1AuditAuthPeriodParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API v1 audit auth period params
func (o *PostAPIV1AuditAuthPeriodParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInput adds the input to the post API v1 audit auth period params
func (o *PostAPIV1AuditAuthPeriodParams) WithInput(input *models.AuditPeriodDTO) *PostAPIV1AuditAuthPeriodParams {
	o.SetInput(input)
	return o
}

// SetInput adds the input to the post API v1 audit auth period params
func (o *PostAPIV1AuditAuthPeriodParams) SetInput(input *models.AuditPeriodDTO) {
	o.Input = input
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIV1AuditAuthPeriodParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Input != nil {
		if err := r.SetBodyParam(o.Input); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
