// Code generated by go-swagger; DO NOT EDIT.

package audit

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ElfAstAhe/tiny-audit-service/pkg/api/http/audit/v1/models"
)

// PostAPIV1AuditAuthPeriodReader is a Reader for the PostAPIV1AuditAuthPeriod structure.
type PostAPIV1AuditAuthPeriodReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIV1AuditAuthPeriodReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPostAPIV1AuditAuthPeriodOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostAPIV1AuditAuthPeriodBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPostAPIV1AuditAuthPeriodUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPostAPIV1AuditAuthPeriodForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewPostAPIV1AuditAuthPeriodConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostAPIV1AuditAuthPeriodInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /api/v1/audit/auth/period] PostAPIV1AuditAuthPeriod", response, response.Code())
	}
}

// NewPostAPIV1AuditAuthPeriodOK creates a PostAPIV1AuditAuthPeriodOK with default headers values
func NewPostAPIV1AuditAuthPeriodOK() *PostAPIV1AuditAuthPeriodOK {
	return &PostAPIV1AuditAuthPeriodOK{}
}

/*
PostAPIV1AuditAuthPeriodOK describes a response with status code 200, with default header values.

список данных аудита
*/
type PostAPIV1AuditAuthPeriodOK struct {
	Payload []*models.AuthAuditDTO
}

// IsSuccess returns true when this post Api v1 audit auth period o k response has a 2xx status code
func (o *PostAPIV1AuditAuthPeriodOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post Api v1 audit auth period o k response has a 3xx status code
func (o *PostAPIV1AuditAuthPeriodOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 audit auth period o k response has a 4xx status code
func (o *PostAPIV1AuditAuthPeriodOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api v1 audit auth period o k response has a 5xx status code
func (o *PostAPIV1AuditAuthPeriodOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 audit auth period o k response a status code equal to that given
func (o *PostAPIV1AuditAuthPeriodOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post Api v1 audit auth period o k response
func (o *PostAPIV1AuditAuthPeriodOK) Code() int {
	return 200
}

func (o *PostAPIV1AuditAuthPeriodOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/audit/auth/period][%d] postApiV1AuditAuthPeriodOK %s", 200, payload)
}

func (o *PostAPIV1AuditAuthPeriodOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/audit/auth/period][%d] postApiV1AuditAuthPeriodOK %s", 200, payload)
}

func (o *PostAPIV1AuditAuthPeriodOK) GetPayload() []*models.AuthAuditDTO {
	return o.Payload
}

func (o *PostAPIV1AuditAuthPeriodOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1AuditAuthPeriodBadRequest creates a PostAPIV1AuditAuthPeriodBadRequest with default headers values
func NewPostAPIV1AuditAuthPeriodBadRequest() *PostAPIV1AuditAuthPeriodBadRequest {
	return &PostAPIV1AuditAuthPeriodBadRequest{}
}

/*
PostAPIV1AuditAuthPeriodBadRequest describes a response with status code 400, with default header values.

Кривые данные
*/
type PostAPIV1AuditAuthPeriodBadRequest struct {
	Payload *models.ErrorDTO
}

// IsSuccess returns true when this post Api v1 audit auth period bad request response has a 2xx status code
func (o *PostAPIV1AuditAuthPeriodBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 audit auth period bad request response has a 3xx status code
func (o *PostAPIV1AuditAuthPeriodBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 audit auth period bad request response has a 4xx status code
func (o *PostAPIV1AuditAuthPeriodBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 audit auth period bad request response has a 5xx status code
func (o *PostAPIV1AuditAuthPeriodBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 audit auth period bad request response a status code equal to that given
func (o *PostAPIV1AuditAuthPeriodBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post Api v1 audit auth period bad request response
func (o *PostAPIV1AuditAuthPeriodBadRequest) Code() int {
	return 400
}

func (o *PostAPIV1AuditAuthPeriodBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/audit/auth/period][%d] postApiV1AuditAuthPeriodBadRequest %s", 400, payload)
}

func (o *PostAPIV1AuditAuthPeriodBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/audit/auth/period][%d] postApiV1AuditAuthPeriodBadRequest %s", 400, payload)
}

func (o *PostAPIV1AuditAuthPeriodBadRequest) GetPayload() *models.ErrorDTO {
	return o.Payload
}

func (o *PostAPIV1AuditAuthPeriodBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1AuditAuthPeriodUnauthorized creates a PostAPIV1AuditAuthPeriodUnauthorized with default headers values
func NewPostAPIV1AuditAuthPeriodUnauthorized() *PostAPIV1AuditAuthPeriodUnauthorized {
	return &PostAPIV1AuditAuthPeriodUnauthorized{}
}

/*
PostAPIV1AuditAuthPeriodUnauthorized describes a response with status code 401, with default header values.

Не авторизован
*/
type PostAPIV1AuditAuthPeriodUnauthorized struct {
	Payload *models.ErrorDTO
}

// IsSuccess returns true when this post Api v1 audit auth period unauthorized response has a 2xx status code
func (o *PostAPIV1AuditAuthPeriodUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 audit auth period unauthorized response has a 3xx status code
func (o *PostAPIV1AuditAuthPeriodUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 audit auth period unauthorized response has a 4xx status code
func (o *PostAPIV1AuditAuthPeriodUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 audit auth period unauthorized response has a 5xx status code
func (o *PostAPIV1AuditAuthPeriodUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 audit auth period unauthorized response a status code equal to that given
func (o *PostAPIV1AuditAuthPeriodUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the post Api v1 audit auth period unauthorized response
func (o *PostAPIV1AuditAuthPeriodUnauthorized) Code() int {
	return 401
}

func (o *PostAPIV1AuditAuthPeriodUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/audit/auth/period][%d] postApiV1AuditAuthPeriodUnauthorized %s", 401, payload)
}

func (o *PostAPIV1AuditAuthPeriodUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/audit/auth/period][%d] postApiV1AuditAuthPeriodUnauthorized %s", 401, payload)
}

func (o *PostAPIV1AuditAuthPeriodUnauthorized) GetPayload() *models.ErrorDTO {
	return o.Payload
}

func (o *PostAPIV1AuditAuthPeriodUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1AuditAuthPeriodForbidden creates a PostAPIV1AuditAuthPeriodForbidden with default headers values
func NewPostAPIV1AuditAuthPeriodForbidden() *PostAPIV1AuditAuthPeriodForbidden {
	return &PostAPIV1AuditAuthPeriodForbidden{}
}

/*
PostAPIV1AuditAuthPeriodForbidden describes a response with status code 403, with default header values.

В доступе отказано
*/
type PostAPIV1AuditAuthPeriodForbidden struct {
	Payload *models.ErrorDTO
}

// IsSuccess returns true when this post Api v1 audit auth period forbidden response has a 2xx status code
func (o *PostAPIV1AuditAuthPeriodForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 audit auth period forbidden response has a 3xx status code
func (o *PostAPIV1AuditAuthPeriodForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 audit auth period forbidden response has a 4xx status code
func (o *PostAPIV1AuditAuthPeriodForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 audit auth period forbidden response has a 5xx status code
func (o *PostAPIV1AuditAuthPeriodForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 audit auth period forbidden response a status code equal to that given
func (o *PostAPIV1AuditAuthPeriodForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the post Api v1 audit auth period forbidden response
func (o *PostAPIV1AuditAuthPeriodForbidden) Code() int {
	return 403
}

func (o *PostAPIV1AuditAuthPeriodForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/audit/auth/period][%d] postApiV1AuditAuthPeriodForbidden %s", 403, payload)
}

func (o *PostAPIV1AuditAuthPeriodForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/audit/auth/period][%d] postApiV1AuditAuthPeriodForbidden %s", 403, payload)
}

func (o *PostAPIV1AuditAuthPeriodForbidden) GetPayload() *models.ErrorDTO {
	return o.Payload
}

func (o *PostAPIV1AuditAuthPeriodForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1AuditAuthPeriodConflict creates a PostAPIV1AuditAuthPeriodConflict with default headers values
func NewPostAPIV1AuditAuthPeriodConflict() *PostAPIV1AuditAuthPeriodConflict {
	return &PostAPIV1AuditAuthPeriodConflict{}
}

/*
PostAPIV1AuditAuthPeriodConflict describes a response with status code 409, with default header values.

Уже существует
*/
type PostAPIV1AuditAuthPeriodConflict struct {
	Payload *models.ErrorDTO
}

// IsSuccess returns true when this post Api v1 audit auth period conflict response has a 2xx status code
func (o *PostAPIV1AuditAuthPeriodConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 audit auth period conflict response has a 3xx status code
func (o *PostAPIV1AuditAuthPeriodConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 audit auth period conflict response has a 4xx status code
func (o *PostAPIV1AuditAuthPeriodConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 audit auth period conflict response has a 5xx status code
func (o *PostAPIV1AuditAuthPeriodConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 audit auth period conflict response a status code equal to that given
func (o *PostAPIV1AuditAuthPeriodConflict) IsCode(code int) bool {
	return code == 409
}

// Code gets the status code for the post Api v1 audit auth period conflict response
func (o *PostAPIV1AuditAuthPeriodConflict) Code() int {
	return 409
}

func (o *PostAPIV1AuditAuthPeriodConflict) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/audit/auth/period][%d] postApiV1AuditAuthPeriodConflict %s", 409, payload)
}

func (o *PostAPIV1AuditAuthPeriodConflict) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/audit/auth/period][%d] postApiV1AuditAuthPeriodConflict %s", 409, payload)
}

func (o *PostAPIV1AuditAuthPeriodConflict) GetPayload() *models.ErrorDTO {
	return o.Payload
}

func (o *PostAPIV1AuditAuthPeriodConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1AuditAuthPeriodInternalServerError creates a PostAPIV1AuditAuthPeriodInternalServerError with default headers values
func NewPostAPIV1AuditAuthPeriodInternalServerError() *PostAPIV1AuditAuthPeriodInternalServerError {
	return &PostAPIV1AuditAuthPeriodInternalServerError{}
}

/*
PostAPIV1AuditAuthPeriodInternalServerError describes a response with status code 500, with default header values.

Внутренняя ошибка сервера (пустое тело)
*/
type PostAPIV1AuditAuthPeriodInternalServerError struct {
}

// IsSuccess returns true when this post Api v1 audit auth period internal server error response has a 2xx status code
func (o *PostAPIV1AuditAuthPeriodInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 audit auth period internal server error response has a 3xx status code
func (o *PostAPIV1AuditAuthPeriodInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 audit auth period internal server error response has a 4xx status code
func (o *PostAPIV1AuditAuthPeriodInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api v1 audit auth period internal server error response has a 5xx status code
func (o *PostAPIV1AuditAuthPeriodInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post Api v1 audit auth period internal server error response a status code equal to that given
func (o *PostAPIV1AuditAuthPeriodInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post Api v1 audit auth period internal server error response
func (o *PostAPIV1AuditAuthPeriodInternalServerError) Code() int {
	return 500
}

func (o *PostAPIV1AuditAuthPeriodInternalServerError) Error() string {
	return fmt.Sprintf("[POST /api/v1/audit/auth/period][%d] postApiV1AuditAuthPeriodInternalServerError", 500)
}

func (o *PostAPIV1AuditAuthPeriodInternalServerError) String() string {
	return fmt.Sprintf("[POST /api/v1/audit/auth/period][%d] postApiV1AuditAuthPeriodInternalServerError", 500)
}

func (o *PostAPIV1AuditAuthPeriodInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
