// Code generated by go-swagger; DO NOT EDIT.

package audit

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/ElfAstAhe/tiny-audit-service/pkg/api/http/audit/v1/models"
)

// NewPostAPIV1AuditAuthParams creates a new PostAPIV1AuditAuthParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPIV1AuditAuthParams() *PostAPIV1AuditAuthParams {
	return &PostAPIV1AuditAuthParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIV1AuditAuthParamsWithTimeout creates a new PostAPIV1AuditAuthParams object
// with the ability to set a timeout on a request.
func NewPostAPIV1AuditAuthParamsWithTimeout(timeout time.Duration) *PostAPIV1AuditAuthParams {
	return &PostAPIV1AuditAuthParams{
		timeout: timeout,
	}
}

// NewPostAPIV1AuditAuthParamsWithContext creates a new PostAPIV1AuditAuthParams object
// with the ability to set a context for a request.
func NewPostAPIV1AuditAuthParamsWithContext(ctx context.Context) *PostAPIV1AuditAuthParams {
	return &PostAPIV1AuditAuthParams{
		Context: ctx,
	}
}

// NewPostAPIV1AuditAuthParamsWithHTTPClient creates a new PostAPIV1AuditAuthParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPIV1AuditAuthParamsWithHTTPClient(client *http.Client) *PostAPIV1AuditAuthParams {
	return &PostAPIV1AuditAuthParams{
		HTTPClient: client,
	}
}

/*
PostAPIV1AuditAuthParams contains all the parameters to send to the API endpoint

	for the post API v1 audit auth operation.

	Typically these are written to a http.Request.
*/
type PostAPIV1AuditAuthParams struct {

	/* Input.

	   Аудит аутентификации
	*/
	Input *models.AuthAuditDTO

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post API v1 audit auth params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIV1AuditAuthParams) WithDefaults() *PostAPIV1AuditAuthParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post API v1 audit auth params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIV1AuditAuthParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post API v1 audit auth params
func (o *PostAPIV1AuditAuthParams) WithTimeout(timeout time.Duration) *PostAPIV1AuditAuthParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API v1 audit auth params
func (o *PostAPIV1AuditAuthParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API v1 audit auth params
func (o *PostAPIV1AuditAuthParams) WithContext(ctx context.Context) *PostAPIV1AuditAuthParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API v1 audit auth params
func (o *PostAPIV1AuditAuthParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API v1 audit auth params
func (o *PostAPIV1AuditAuthParams) WithHTTPClient(client *http.Client) *PostAPIV1AuditAuthParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API v1 audit auth params
func (o *PostAPIV1AuditAuthParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInput adds the input to the post API v1 audit auth params
func (o *PostAPIV1AuditAuthParams) WithInput(input *models.AuthAuditDTO) *PostAPIV1AuditAuthParams {
	o.SetInput(input)
	return o
}

// SetInput adds the input to the post API v1 audit auth params
func (o *PostAPIV1AuditAuthParams) SetInput(input *models.AuthAuditDTO) {
	o.Input = input
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIV1AuditAuthParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Input != nil {
		if err := r.SetBodyParam(o.Input); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
