// Code generated by go-swagger; DO NOT EDIT.

package audit

import (
	"context"
	"net/http"
	"time"

	"github.com/ElfAstAhe/tiny-audit-service/pkg/api/http/audit/v1/models"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostAPIV1AuditDataPeriodParams creates a new PostAPIV1AuditDataPeriodParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPIV1AuditDataPeriodParams() *PostAPIV1AuditDataPeriodParams {
	return NewPostAPIV1AuditDataPeriodParamsWithTimeout(cr.DefaultTimeout)
}

// NewPostAPIV1AuditDataPeriodParamsWithTimeout creates a new PostAPIV1AuditDataPeriodParams object
// with the ability to set a timeout on a request.
func NewPostAPIV1AuditDataPeriodParamsWithTimeout(timeout time.Duration) *PostAPIV1AuditDataPeriodParams {
	return &PostAPIV1AuditDataPeriodParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewPostAPIV1AuditDataPeriodParamsWithContext creates a new PostAPIV1AuditDataPeriodParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [PostAPIV1AuditDataPeriodParams].
func NewPostAPIV1AuditDataPeriodParamsWithContext(ctx context.Context) *PostAPIV1AuditDataPeriodParams {
	return &PostAPIV1AuditDataPeriodParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewPostAPIV1AuditDataPeriodParamsWithHTTPClient creates a new PostAPIV1AuditDataPeriodParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPIV1AuditDataPeriodParamsWithHTTPClient(client *http.Client) *PostAPIV1AuditDataPeriodParams {
	return &PostAPIV1AuditDataPeriodParams{
		HTTPClient: client,
	}
}

/*
PostAPIV1AuditDataPeriodParams contains all the parameters to send to the API endpoint

	for the post API v1 audit data period operation.

	Typically these are written to a http.Request.
*/
type PostAPIV1AuditDataPeriodParams struct {

	// Input.
	//
	// Период аудита
	Input *models.AuditPeriodDTO

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the post API v1 audit data period params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIV1AuditDataPeriodParams) WithDefaults() *PostAPIV1AuditDataPeriodParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post API v1 audit data period params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIV1AuditDataPeriodParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post API v1 audit data period params.
func (o *PostAPIV1AuditDataPeriodParams) WithTimeout(timeout time.Duration) *PostAPIV1AuditDataPeriodParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API v1 audit data period params.
func (o *PostAPIV1AuditDataPeriodParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the post API v1 audit data period params.
//
// Deprecated: use the operation call with context to pass the context instead of [PostAPIV1AuditDataPeriodParams].
func (o *PostAPIV1AuditDataPeriodParams) WithContext(ctx context.Context) *PostAPIV1AuditDataPeriodParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API v1 audit data period params.
//
// Deprecated: use the operation call with context to pass the context instead of [PostAPIV1AuditDataPeriodParams].
func (o *PostAPIV1AuditDataPeriodParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the post API v1 audit data period params.
func (o *PostAPIV1AuditDataPeriodParams) WithHTTPClient(client *http.Client) *PostAPIV1AuditDataPeriodParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API v1 audit data period params.
func (o *PostAPIV1AuditDataPeriodParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInput adds the input to the post API v1 audit data period params.
func (o *PostAPIV1AuditDataPeriodParams) WithInput(input *models.AuditPeriodDTO) *PostAPIV1AuditDataPeriodParams {
	o.SetInput(input)
	return o
}

// SetInput adds the input to the post API v1 audit data period params.
func (o *PostAPIV1AuditDataPeriodParams) SetInput(input *models.AuditPeriodDTO) {
	o.Input = input
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *PostAPIV1AuditDataPeriodParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error
	if o.Input != nil {
		if err := r.SetBodyParam(o.Input); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
