// Code generated by go-swagger; DO NOT EDIT.

package audit

import (
	"context"
	"net/http"
	"time"

	"github.com/ElfAstAhe/tiny-audit-service/pkg/api/http/audit/v1/models"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostAPIV1AuditDataInstanceParams creates a new PostAPIV1AuditDataInstanceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPIV1AuditDataInstanceParams() *PostAPIV1AuditDataInstanceParams {
	return NewPostAPIV1AuditDataInstanceParamsWithTimeout(cr.DefaultTimeout)
}

// NewPostAPIV1AuditDataInstanceParamsWithTimeout creates a new PostAPIV1AuditDataInstanceParams object
// with the ability to set a timeout on a request.
func NewPostAPIV1AuditDataInstanceParamsWithTimeout(timeout time.Duration) *PostAPIV1AuditDataInstanceParams {
	return &PostAPIV1AuditDataInstanceParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewPostAPIV1AuditDataInstanceParamsWithContext creates a new PostAPIV1AuditDataInstanceParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [PostAPIV1AuditDataInstanceParams].
func NewPostAPIV1AuditDataInstanceParamsWithContext(ctx context.Context) *PostAPIV1AuditDataInstanceParams {
	return &PostAPIV1AuditDataInstanceParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewPostAPIV1AuditDataInstanceParamsWithHTTPClient creates a new PostAPIV1AuditDataInstanceParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPIV1AuditDataInstanceParamsWithHTTPClient(client *http.Client) *PostAPIV1AuditDataInstanceParams {
	return &PostAPIV1AuditDataInstanceParams{
		HTTPClient: client,
	}
}

/*
PostAPIV1AuditDataInstanceParams contains all the parameters to send to the API endpoint

	for the post API v1 audit data instance operation.

	Typically these are written to a http.Request.
*/
type PostAPIV1AuditDataInstanceParams struct {

	// Input.
	//
	// инстанс данных
	Input *models.AuditInstanceDTO

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the post API v1 audit data instance params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIV1AuditDataInstanceParams) WithDefaults() *PostAPIV1AuditDataInstanceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post API v1 audit data instance params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIV1AuditDataInstanceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post API v1 audit data instance params.
func (o *PostAPIV1AuditDataInstanceParams) WithTimeout(timeout time.Duration) *PostAPIV1AuditDataInstanceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API v1 audit data instance params.
func (o *PostAPIV1AuditDataInstanceParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the post API v1 audit data instance params.
//
// Deprecated: use the operation call with context to pass the context instead of [PostAPIV1AuditDataInstanceParams].
func (o *PostAPIV1AuditDataInstanceParams) WithContext(ctx context.Context) *PostAPIV1AuditDataInstanceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API v1 audit data instance params.
//
// Deprecated: use the operation call with context to pass the context instead of [PostAPIV1AuditDataInstanceParams].
func (o *PostAPIV1AuditDataInstanceParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the post API v1 audit data instance params.
func (o *PostAPIV1AuditDataInstanceParams) WithHTTPClient(client *http.Client) *PostAPIV1AuditDataInstanceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API v1 audit data instance params.
func (o *PostAPIV1AuditDataInstanceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInput adds the input to the post API v1 audit data instance params.
func (o *PostAPIV1AuditDataInstanceParams) WithInput(input *models.AuditInstanceDTO) *PostAPIV1AuditDataInstanceParams {
	o.SetInput(input)
	return o
}

// SetInput adds the input to the post API v1 audit data instance params.
func (o *PostAPIV1AuditDataInstanceParams) SetInput(input *models.AuditInstanceDTO) {
	o.Input = input
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *PostAPIV1AuditDataInstanceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error
	if o.Input != nil {
		if err := r.SetBodyParam(o.Input); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
