// Code generated by go-swagger; DO NOT EDIT.

package audit

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/ElfAstAhe/tiny-audit-service/pkg/api/http/audit/v1/models"
)

// NewPostAPIV1AuditDataParams creates a new PostAPIV1AuditDataParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPIV1AuditDataParams() *PostAPIV1AuditDataParams {
	return &PostAPIV1AuditDataParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIV1AuditDataParamsWithTimeout creates a new PostAPIV1AuditDataParams object
// with the ability to set a timeout on a request.
func NewPostAPIV1AuditDataParamsWithTimeout(timeout time.Duration) *PostAPIV1AuditDataParams {
	return &PostAPIV1AuditDataParams{
		timeout: timeout,
	}
}

// NewPostAPIV1AuditDataParamsWithContext creates a new PostAPIV1AuditDataParams object
// with the ability to set a context for a request.
func NewPostAPIV1AuditDataParamsWithContext(ctx context.Context) *PostAPIV1AuditDataParams {
	return &PostAPIV1AuditDataParams{
		Context: ctx,
	}
}

// NewPostAPIV1AuditDataParamsWithHTTPClient creates a new PostAPIV1AuditDataParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPIV1AuditDataParamsWithHTTPClient(client *http.Client) *PostAPIV1AuditDataParams {
	return &PostAPIV1AuditDataParams{
		HTTPClient: client,
	}
}

/*
PostAPIV1AuditDataParams contains all the parameters to send to the API endpoint

	for the post API v1 audit data operation.

	Typically these are written to a http.Request.
*/
type PostAPIV1AuditDataParams struct {

	/* Input.

	   Аудит данных
	*/
	Input *models.DataAuditDTO

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post API v1 audit data params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIV1AuditDataParams) WithDefaults() *PostAPIV1AuditDataParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post API v1 audit data params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIV1AuditDataParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post API v1 audit data params
func (o *PostAPIV1AuditDataParams) WithTimeout(timeout time.Duration) *PostAPIV1AuditDataParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API v1 audit data params
func (o *PostAPIV1AuditDataParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API v1 audit data params
func (o *PostAPIV1AuditDataParams) WithContext(ctx context.Context) *PostAPIV1AuditDataParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API v1 audit data params
func (o *PostAPIV1AuditDataParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API v1 audit data params
func (o *PostAPIV1AuditDataParams) WithHTTPClient(client *http.Client) *PostAPIV1AuditDataParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API v1 audit data params
func (o *PostAPIV1AuditDataParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInput adds the input to the post API v1 audit data params
func (o *PostAPIV1AuditDataParams) WithInput(input *models.DataAuditDTO) *PostAPIV1AuditDataParams {
	o.SetInput(input)
	return o
}

// SetInput adds the input to the post API v1 audit data params
func (o *PostAPIV1AuditDataParams) SetInput(input *models.DataAuditDTO) {
	o.Input = input
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIV1AuditDataParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Input != nil {
		if err := r.SetBodyParam(o.Input); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
