// Code generated by go-swagger; DO NOT EDIT.

package audit

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ElfAstAhe/tiny-audit-service/pkg/api/http/audit/v1/models"
)

// PostAPIV1AuditDataPeriodReader is a Reader for the PostAPIV1AuditDataPeriod structure.
type PostAPIV1AuditDataPeriodReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIV1AuditDataPeriodReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPostAPIV1AuditDataPeriodOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostAPIV1AuditDataPeriodBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPostAPIV1AuditDataPeriodUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPostAPIV1AuditDataPeriodForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewPostAPIV1AuditDataPeriodConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostAPIV1AuditDataPeriodInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /api/v1/audit/data/period] PostAPIV1AuditDataPeriod", response, response.Code())
	}
}

// NewPostAPIV1AuditDataPeriodOK creates a PostAPIV1AuditDataPeriodOK with default headers values
func NewPostAPIV1AuditDataPeriodOK() *PostAPIV1AuditDataPeriodOK {
	return &PostAPIV1AuditDataPeriodOK{}
}

/*
PostAPIV1AuditDataPeriodOK describes a response with status code 200, with default header values.

список данных аудита
*/
type PostAPIV1AuditDataPeriodOK struct {
	Payload []*models.DataAuditDTO
}

// IsSuccess returns true when this post Api v1 audit data period o k response has a 2xx status code
func (o *PostAPIV1AuditDataPeriodOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post Api v1 audit data period o k response has a 3xx status code
func (o *PostAPIV1AuditDataPeriodOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 audit data period o k response has a 4xx status code
func (o *PostAPIV1AuditDataPeriodOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api v1 audit data period o k response has a 5xx status code
func (o *PostAPIV1AuditDataPeriodOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 audit data period o k response a status code equal to that given
func (o *PostAPIV1AuditDataPeriodOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post Api v1 audit data period o k response
func (o *PostAPIV1AuditDataPeriodOK) Code() int {
	return 200
}

func (o *PostAPIV1AuditDataPeriodOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/audit/data/period][%d] postApiV1AuditDataPeriodOK %s", 200, payload)
}

func (o *PostAPIV1AuditDataPeriodOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/audit/data/period][%d] postApiV1AuditDataPeriodOK %s", 200, payload)
}

func (o *PostAPIV1AuditDataPeriodOK) GetPayload() []*models.DataAuditDTO {
	return o.Payload
}

func (o *PostAPIV1AuditDataPeriodOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1AuditDataPeriodBadRequest creates a PostAPIV1AuditDataPeriodBadRequest with default headers values
func NewPostAPIV1AuditDataPeriodBadRequest() *PostAPIV1AuditDataPeriodBadRequest {
	return &PostAPIV1AuditDataPeriodBadRequest{}
}

/*
PostAPIV1AuditDataPeriodBadRequest describes a response with status code 400, with default header values.

Кривые данные
*/
type PostAPIV1AuditDataPeriodBadRequest struct {
	Payload *models.ErrorDTO
}

// IsSuccess returns true when this post Api v1 audit data period bad request response has a 2xx status code
func (o *PostAPIV1AuditDataPeriodBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 audit data period bad request response has a 3xx status code
func (o *PostAPIV1AuditDataPeriodBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 audit data period bad request response has a 4xx status code
func (o *PostAPIV1AuditDataPeriodBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 audit data period bad request response has a 5xx status code
func (o *PostAPIV1AuditDataPeriodBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 audit data period bad request response a status code equal to that given
func (o *PostAPIV1AuditDataPeriodBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post Api v1 audit data period bad request response
func (o *PostAPIV1AuditDataPeriodBadRequest) Code() int {
	return 400
}

func (o *PostAPIV1AuditDataPeriodBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/audit/data/period][%d] postApiV1AuditDataPeriodBadRequest %s", 400, payload)
}

func (o *PostAPIV1AuditDataPeriodBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/audit/data/period][%d] postApiV1AuditDataPeriodBadRequest %s", 400, payload)
}

func (o *PostAPIV1AuditDataPeriodBadRequest) GetPayload() *models.ErrorDTO {
	return o.Payload
}

func (o *PostAPIV1AuditDataPeriodBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1AuditDataPeriodUnauthorized creates a PostAPIV1AuditDataPeriodUnauthorized with default headers values
func NewPostAPIV1AuditDataPeriodUnauthorized() *PostAPIV1AuditDataPeriodUnauthorized {
	return &PostAPIV1AuditDataPeriodUnauthorized{}
}

/*
PostAPIV1AuditDataPeriodUnauthorized describes a response with status code 401, with default header values.

Не авторизован
*/
type PostAPIV1AuditDataPeriodUnauthorized struct {
	Payload *models.ErrorDTO
}

// IsSuccess returns true when this post Api v1 audit data period unauthorized response has a 2xx status code
func (o *PostAPIV1AuditDataPeriodUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 audit data period unauthorized response has a 3xx status code
func (o *PostAPIV1AuditDataPeriodUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 audit data period unauthorized response has a 4xx status code
func (o *PostAPIV1AuditDataPeriodUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 audit data period unauthorized response has a 5xx status code
func (o *PostAPIV1AuditDataPeriodUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 audit data period unauthorized response a status code equal to that given
func (o *PostAPIV1AuditDataPeriodUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the post Api v1 audit data period unauthorized response
func (o *PostAPIV1AuditDataPeriodUnauthorized) Code() int {
	return 401
}

func (o *PostAPIV1AuditDataPeriodUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/audit/data/period][%d] postApiV1AuditDataPeriodUnauthorized %s", 401, payload)
}

func (o *PostAPIV1AuditDataPeriodUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/audit/data/period][%d] postApiV1AuditDataPeriodUnauthorized %s", 401, payload)
}

func (o *PostAPIV1AuditDataPeriodUnauthorized) GetPayload() *models.ErrorDTO {
	return o.Payload
}

func (o *PostAPIV1AuditDataPeriodUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1AuditDataPeriodForbidden creates a PostAPIV1AuditDataPeriodForbidden with default headers values
func NewPostAPIV1AuditDataPeriodForbidden() *PostAPIV1AuditDataPeriodForbidden {
	return &PostAPIV1AuditDataPeriodForbidden{}
}

/*
PostAPIV1AuditDataPeriodForbidden describes a response with status code 403, with default header values.

В доступе отказано
*/
type PostAPIV1AuditDataPeriodForbidden struct {
	Payload *models.ErrorDTO
}

// IsSuccess returns true when this post Api v1 audit data period forbidden response has a 2xx status code
func (o *PostAPIV1AuditDataPeriodForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 audit data period forbidden response has a 3xx status code
func (o *PostAPIV1AuditDataPeriodForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 audit data period forbidden response has a 4xx status code
func (o *PostAPIV1AuditDataPeriodForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 audit data period forbidden response has a 5xx status code
func (o *PostAPIV1AuditDataPeriodForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 audit data period forbidden response a status code equal to that given
func (o *PostAPIV1AuditDataPeriodForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the post Api v1 audit data period forbidden response
func (o *PostAPIV1AuditDataPeriodForbidden) Code() int {
	return 403
}

func (o *PostAPIV1AuditDataPeriodForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/audit/data/period][%d] postApiV1AuditDataPeriodForbidden %s", 403, payload)
}

func (o *PostAPIV1AuditDataPeriodForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/audit/data/period][%d] postApiV1AuditDataPeriodForbidden %s", 403, payload)
}

func (o *PostAPIV1AuditDataPeriodForbidden) GetPayload() *models.ErrorDTO {
	return o.Payload
}

func (o *PostAPIV1AuditDataPeriodForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1AuditDataPeriodConflict creates a PostAPIV1AuditDataPeriodConflict with default headers values
func NewPostAPIV1AuditDataPeriodConflict() *PostAPIV1AuditDataPeriodConflict {
	return &PostAPIV1AuditDataPeriodConflict{}
}

/*
PostAPIV1AuditDataPeriodConflict describes a response with status code 409, with default header values.

Уже существует
*/
type PostAPIV1AuditDataPeriodConflict struct {
	Payload *models.ErrorDTO
}

// IsSuccess returns true when this post Api v1 audit data period conflict response has a 2xx status code
func (o *PostAPIV1AuditDataPeriodConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 audit data period conflict response has a 3xx status code
func (o *PostAPIV1AuditDataPeriodConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 audit data period conflict response has a 4xx status code
func (o *PostAPIV1AuditDataPeriodConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 audit data period conflict response has a 5xx status code
func (o *PostAPIV1AuditDataPeriodConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 audit data period conflict response a status code equal to that given
func (o *PostAPIV1AuditDataPeriodConflict) IsCode(code int) bool {
	return code == 409
}

// Code gets the status code for the post Api v1 audit data period conflict response
func (o *PostAPIV1AuditDataPeriodConflict) Code() int {
	return 409
}

func (o *PostAPIV1AuditDataPeriodConflict) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/audit/data/period][%d] postApiV1AuditDataPeriodConflict %s", 409, payload)
}

func (o *PostAPIV1AuditDataPeriodConflict) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/audit/data/period][%d] postApiV1AuditDataPeriodConflict %s", 409, payload)
}

func (o *PostAPIV1AuditDataPeriodConflict) GetPayload() *models.ErrorDTO {
	return o.Payload
}

func (o *PostAPIV1AuditDataPeriodConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1AuditDataPeriodInternalServerError creates a PostAPIV1AuditDataPeriodInternalServerError with default headers values
func NewPostAPIV1AuditDataPeriodInternalServerError() *PostAPIV1AuditDataPeriodInternalServerError {
	return &PostAPIV1AuditDataPeriodInternalServerError{}
}

/*
PostAPIV1AuditDataPeriodInternalServerError describes a response with status code 500, with default header values.

Внутренняя ошибка сервера (пустое тело)
*/
type PostAPIV1AuditDataPeriodInternalServerError struct {
}

// IsSuccess returns true when this post Api v1 audit data period internal server error response has a 2xx status code
func (o *PostAPIV1AuditDataPeriodInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 audit data period internal server error response has a 3xx status code
func (o *PostAPIV1AuditDataPeriodInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 audit data period internal server error response has a 4xx status code
func (o *PostAPIV1AuditDataPeriodInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api v1 audit data period internal server error response has a 5xx status code
func (o *PostAPIV1AuditDataPeriodInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post Api v1 audit data period internal server error response a status code equal to that given
func (o *PostAPIV1AuditDataPeriodInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post Api v1 audit data period internal server error response
func (o *PostAPIV1AuditDataPeriodInternalServerError) Code() int {
	return 500
}

func (o *PostAPIV1AuditDataPeriodInternalServerError) Error() string {
	return fmt.Sprintf("[POST /api/v1/audit/data/period][%d] postApiV1AuditDataPeriodInternalServerError", 500)
}

func (o *PostAPIV1AuditDataPeriodInternalServerError) String() string {
	return fmt.Sprintf("[POST /api/v1/audit/data/period][%d] postApiV1AuditDataPeriodInternalServerError", 500)
}

func (o *PostAPIV1AuditDataPeriodInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
