// Code generated by go-swagger; DO NOT EDIT.

package audit

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ElfAstAhe/tiny-audit-service/pkg/api/http/audit/v1/models"
)

// PostAPIV1AuditAuthReader is a Reader for the PostAPIV1AuditAuth structure.
type PostAPIV1AuditAuthReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIV1AuditAuthReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 201:
		result := NewPostAPIV1AuditAuthCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostAPIV1AuditAuthBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPostAPIV1AuditAuthUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPostAPIV1AuditAuthForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostAPIV1AuditAuthInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /api/v1/audit/auth] PostAPIV1AuditAuth", response, response.Code())
	}
}

// NewPostAPIV1AuditAuthCreated creates a PostAPIV1AuditAuthCreated with default headers values
func NewPostAPIV1AuditAuthCreated() *PostAPIV1AuditAuthCreated {
	return &PostAPIV1AuditAuthCreated{}
}

/*
PostAPIV1AuditAuthCreated describes a response with status code 201, with default header values.

Всё хорошо (пустое тело)
*/
type PostAPIV1AuditAuthCreated struct {
}

// IsSuccess returns true when this post Api v1 audit auth created response has a 2xx status code
func (o *PostAPIV1AuditAuthCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post Api v1 audit auth created response has a 3xx status code
func (o *PostAPIV1AuditAuthCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 audit auth created response has a 4xx status code
func (o *PostAPIV1AuditAuthCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api v1 audit auth created response has a 5xx status code
func (o *PostAPIV1AuditAuthCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 audit auth created response a status code equal to that given
func (o *PostAPIV1AuditAuthCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the post Api v1 audit auth created response
func (o *PostAPIV1AuditAuthCreated) Code() int {
	return 201
}

func (o *PostAPIV1AuditAuthCreated) Error() string {
	return fmt.Sprintf("[POST /api/v1/audit/auth][%d] postApiV1AuditAuthCreated", 201)
}

func (o *PostAPIV1AuditAuthCreated) String() string {
	return fmt.Sprintf("[POST /api/v1/audit/auth][%d] postApiV1AuditAuthCreated", 201)
}

func (o *PostAPIV1AuditAuthCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostAPIV1AuditAuthBadRequest creates a PostAPIV1AuditAuthBadRequest with default headers values
func NewPostAPIV1AuditAuthBadRequest() *PostAPIV1AuditAuthBadRequest {
	return &PostAPIV1AuditAuthBadRequest{}
}

/*
PostAPIV1AuditAuthBadRequest describes a response with status code 400, with default header values.

Кривые данные
*/
type PostAPIV1AuditAuthBadRequest struct {
	Payload *models.ErrorDTO
}

// IsSuccess returns true when this post Api v1 audit auth bad request response has a 2xx status code
func (o *PostAPIV1AuditAuthBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 audit auth bad request response has a 3xx status code
func (o *PostAPIV1AuditAuthBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 audit auth bad request response has a 4xx status code
func (o *PostAPIV1AuditAuthBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 audit auth bad request response has a 5xx status code
func (o *PostAPIV1AuditAuthBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 audit auth bad request response a status code equal to that given
func (o *PostAPIV1AuditAuthBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post Api v1 audit auth bad request response
func (o *PostAPIV1AuditAuthBadRequest) Code() int {
	return 400
}

func (o *PostAPIV1AuditAuthBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/audit/auth][%d] postApiV1AuditAuthBadRequest %s", 400, payload)
}

func (o *PostAPIV1AuditAuthBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/audit/auth][%d] postApiV1AuditAuthBadRequest %s", 400, payload)
}

func (o *PostAPIV1AuditAuthBadRequest) GetPayload() *models.ErrorDTO {
	return o.Payload
}

func (o *PostAPIV1AuditAuthBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1AuditAuthUnauthorized creates a PostAPIV1AuditAuthUnauthorized with default headers values
func NewPostAPIV1AuditAuthUnauthorized() *PostAPIV1AuditAuthUnauthorized {
	return &PostAPIV1AuditAuthUnauthorized{}
}

/*
PostAPIV1AuditAuthUnauthorized describes a response with status code 401, with default header values.

Не авторизован
*/
type PostAPIV1AuditAuthUnauthorized struct {
	Payload *models.ErrorDTO
}

// IsSuccess returns true when this post Api v1 audit auth unauthorized response has a 2xx status code
func (o *PostAPIV1AuditAuthUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 audit auth unauthorized response has a 3xx status code
func (o *PostAPIV1AuditAuthUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 audit auth unauthorized response has a 4xx status code
func (o *PostAPIV1AuditAuthUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 audit auth unauthorized response has a 5xx status code
func (o *PostAPIV1AuditAuthUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 audit auth unauthorized response a status code equal to that given
func (o *PostAPIV1AuditAuthUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the post Api v1 audit auth unauthorized response
func (o *PostAPIV1AuditAuthUnauthorized) Code() int {
	return 401
}

func (o *PostAPIV1AuditAuthUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/audit/auth][%d] postApiV1AuditAuthUnauthorized %s", 401, payload)
}

func (o *PostAPIV1AuditAuthUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/audit/auth][%d] postApiV1AuditAuthUnauthorized %s", 401, payload)
}

func (o *PostAPIV1AuditAuthUnauthorized) GetPayload() *models.ErrorDTO {
	return o.Payload
}

func (o *PostAPIV1AuditAuthUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1AuditAuthForbidden creates a PostAPIV1AuditAuthForbidden with default headers values
func NewPostAPIV1AuditAuthForbidden() *PostAPIV1AuditAuthForbidden {
	return &PostAPIV1AuditAuthForbidden{}
}

/*
PostAPIV1AuditAuthForbidden describes a response with status code 403, with default header values.

В доступе отказано
*/
type PostAPIV1AuditAuthForbidden struct {
	Payload *models.ErrorDTO
}

// IsSuccess returns true when this post Api v1 audit auth forbidden response has a 2xx status code
func (o *PostAPIV1AuditAuthForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 audit auth forbidden response has a 3xx status code
func (o *PostAPIV1AuditAuthForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 audit auth forbidden response has a 4xx status code
func (o *PostAPIV1AuditAuthForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 audit auth forbidden response has a 5xx status code
func (o *PostAPIV1AuditAuthForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 audit auth forbidden response a status code equal to that given
func (o *PostAPIV1AuditAuthForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the post Api v1 audit auth forbidden response
func (o *PostAPIV1AuditAuthForbidden) Code() int {
	return 403
}

func (o *PostAPIV1AuditAuthForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/audit/auth][%d] postApiV1AuditAuthForbidden %s", 403, payload)
}

func (o *PostAPIV1AuditAuthForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/audit/auth][%d] postApiV1AuditAuthForbidden %s", 403, payload)
}

func (o *PostAPIV1AuditAuthForbidden) GetPayload() *models.ErrorDTO {
	return o.Payload
}

func (o *PostAPIV1AuditAuthForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1AuditAuthInternalServerError creates a PostAPIV1AuditAuthInternalServerError with default headers values
func NewPostAPIV1AuditAuthInternalServerError() *PostAPIV1AuditAuthInternalServerError {
	return &PostAPIV1AuditAuthInternalServerError{}
}

/*
PostAPIV1AuditAuthInternalServerError describes a response with status code 500, with default header values.

Внутренняя ошибка сервера (пустое тело)
*/
type PostAPIV1AuditAuthInternalServerError struct {
}

// IsSuccess returns true when this post Api v1 audit auth internal server error response has a 2xx status code
func (o *PostAPIV1AuditAuthInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 audit auth internal server error response has a 3xx status code
func (o *PostAPIV1AuditAuthInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 audit auth internal server error response has a 4xx status code
func (o *PostAPIV1AuditAuthInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api v1 audit auth internal server error response has a 5xx status code
func (o *PostAPIV1AuditAuthInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post Api v1 audit auth internal server error response a status code equal to that given
func (o *PostAPIV1AuditAuthInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post Api v1 audit auth internal server error response
func (o *PostAPIV1AuditAuthInternalServerError) Code() int {
	return 500
}

func (o *PostAPIV1AuditAuthInternalServerError) Error() string {
	return fmt.Sprintf("[POST /api/v1/audit/auth][%d] postApiV1AuditAuthInternalServerError", 500)
}

func (o *PostAPIV1AuditAuthInternalServerError) String() string {
	return fmt.Sprintf("[POST /api/v1/audit/auth][%d] postApiV1AuditAuthInternalServerError", 500)
}

func (o *PostAPIV1AuditAuthInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
