// Code generated by go-swagger; DO NOT EDIT.

package audit

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ElfAstAhe/tiny-audit-service/pkg/api/http/audit/v1/models"
)

// PostAPIV1AuditDataUsernameReader is a Reader for the PostAPIV1AuditDataUsername structure.
type PostAPIV1AuditDataUsernameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIV1AuditDataUsernameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPostAPIV1AuditDataUsernameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostAPIV1AuditDataUsernameBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPostAPIV1AuditDataUsernameUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPostAPIV1AuditDataUsernameForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewPostAPIV1AuditDataUsernameConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostAPIV1AuditDataUsernameInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /api/v1/audit/data/username] PostAPIV1AuditDataUsername", response, response.Code())
	}
}

// NewPostAPIV1AuditDataUsernameOK creates a PostAPIV1AuditDataUsernameOK with default headers values
func NewPostAPIV1AuditDataUsernameOK() *PostAPIV1AuditDataUsernameOK {
	return &PostAPIV1AuditDataUsernameOK{}
}

/*
PostAPIV1AuditDataUsernameOK describes a response with status code 200, with default header values.

список данных аудита
*/
type PostAPIV1AuditDataUsernameOK struct {
	Payload []*models.AuthAuditDTO
}

// IsSuccess returns true when this post Api v1 audit data username o k response has a 2xx status code
func (o *PostAPIV1AuditDataUsernameOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post Api v1 audit data username o k response has a 3xx status code
func (o *PostAPIV1AuditDataUsernameOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 audit data username o k response has a 4xx status code
func (o *PostAPIV1AuditDataUsernameOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api v1 audit data username o k response has a 5xx status code
func (o *PostAPIV1AuditDataUsernameOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 audit data username o k response a status code equal to that given
func (o *PostAPIV1AuditDataUsernameOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post Api v1 audit data username o k response
func (o *PostAPIV1AuditDataUsernameOK) Code() int {
	return 200
}

func (o *PostAPIV1AuditDataUsernameOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/audit/data/username][%d] postApiV1AuditDataUsernameOK %s", 200, payload)
}

func (o *PostAPIV1AuditDataUsernameOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/audit/data/username][%d] postApiV1AuditDataUsernameOK %s", 200, payload)
}

func (o *PostAPIV1AuditDataUsernameOK) GetPayload() []*models.AuthAuditDTO {
	return o.Payload
}

func (o *PostAPIV1AuditDataUsernameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1AuditDataUsernameBadRequest creates a PostAPIV1AuditDataUsernameBadRequest with default headers values
func NewPostAPIV1AuditDataUsernameBadRequest() *PostAPIV1AuditDataUsernameBadRequest {
	return &PostAPIV1AuditDataUsernameBadRequest{}
}

/*
PostAPIV1AuditDataUsernameBadRequest describes a response with status code 400, with default header values.

Кривые данные
*/
type PostAPIV1AuditDataUsernameBadRequest struct {
	Payload *models.ErrorDTO
}

// IsSuccess returns true when this post Api v1 audit data username bad request response has a 2xx status code
func (o *PostAPIV1AuditDataUsernameBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 audit data username bad request response has a 3xx status code
func (o *PostAPIV1AuditDataUsernameBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 audit data username bad request response has a 4xx status code
func (o *PostAPIV1AuditDataUsernameBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 audit data username bad request response has a 5xx status code
func (o *PostAPIV1AuditDataUsernameBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 audit data username bad request response a status code equal to that given
func (o *PostAPIV1AuditDataUsernameBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post Api v1 audit data username bad request response
func (o *PostAPIV1AuditDataUsernameBadRequest) Code() int {
	return 400
}

func (o *PostAPIV1AuditDataUsernameBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/audit/data/username][%d] postApiV1AuditDataUsernameBadRequest %s", 400, payload)
}

func (o *PostAPIV1AuditDataUsernameBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/audit/data/username][%d] postApiV1AuditDataUsernameBadRequest %s", 400, payload)
}

func (o *PostAPIV1AuditDataUsernameBadRequest) GetPayload() *models.ErrorDTO {
	return o.Payload
}

func (o *PostAPIV1AuditDataUsernameBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1AuditDataUsernameUnauthorized creates a PostAPIV1AuditDataUsernameUnauthorized with default headers values
func NewPostAPIV1AuditDataUsernameUnauthorized() *PostAPIV1AuditDataUsernameUnauthorized {
	return &PostAPIV1AuditDataUsernameUnauthorized{}
}

/*
PostAPIV1AuditDataUsernameUnauthorized describes a response with status code 401, with default header values.

Не авторизован
*/
type PostAPIV1AuditDataUsernameUnauthorized struct {
	Payload *models.ErrorDTO
}

// IsSuccess returns true when this post Api v1 audit data username unauthorized response has a 2xx status code
func (o *PostAPIV1AuditDataUsernameUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 audit data username unauthorized response has a 3xx status code
func (o *PostAPIV1AuditDataUsernameUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 audit data username unauthorized response has a 4xx status code
func (o *PostAPIV1AuditDataUsernameUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 audit data username unauthorized response has a 5xx status code
func (o *PostAPIV1AuditDataUsernameUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 audit data username unauthorized response a status code equal to that given
func (o *PostAPIV1AuditDataUsernameUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the post Api v1 audit data username unauthorized response
func (o *PostAPIV1AuditDataUsernameUnauthorized) Code() int {
	return 401
}

func (o *PostAPIV1AuditDataUsernameUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/audit/data/username][%d] postApiV1AuditDataUsernameUnauthorized %s", 401, payload)
}

func (o *PostAPIV1AuditDataUsernameUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/audit/data/username][%d] postApiV1AuditDataUsernameUnauthorized %s", 401, payload)
}

func (o *PostAPIV1AuditDataUsernameUnauthorized) GetPayload() *models.ErrorDTO {
	return o.Payload
}

func (o *PostAPIV1AuditDataUsernameUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1AuditDataUsernameForbidden creates a PostAPIV1AuditDataUsernameForbidden with default headers values
func NewPostAPIV1AuditDataUsernameForbidden() *PostAPIV1AuditDataUsernameForbidden {
	return &PostAPIV1AuditDataUsernameForbidden{}
}

/*
PostAPIV1AuditDataUsernameForbidden describes a response with status code 403, with default header values.

В доступе отказано
*/
type PostAPIV1AuditDataUsernameForbidden struct {
	Payload *models.ErrorDTO
}

// IsSuccess returns true when this post Api v1 audit data username forbidden response has a 2xx status code
func (o *PostAPIV1AuditDataUsernameForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 audit data username forbidden response has a 3xx status code
func (o *PostAPIV1AuditDataUsernameForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 audit data username forbidden response has a 4xx status code
func (o *PostAPIV1AuditDataUsernameForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 audit data username forbidden response has a 5xx status code
func (o *PostAPIV1AuditDataUsernameForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 audit data username forbidden response a status code equal to that given
func (o *PostAPIV1AuditDataUsernameForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the post Api v1 audit data username forbidden response
func (o *PostAPIV1AuditDataUsernameForbidden) Code() int {
	return 403
}

func (o *PostAPIV1AuditDataUsernameForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/audit/data/username][%d] postApiV1AuditDataUsernameForbidden %s", 403, payload)
}

func (o *PostAPIV1AuditDataUsernameForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/audit/data/username][%d] postApiV1AuditDataUsernameForbidden %s", 403, payload)
}

func (o *PostAPIV1AuditDataUsernameForbidden) GetPayload() *models.ErrorDTO {
	return o.Payload
}

func (o *PostAPIV1AuditDataUsernameForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1AuditDataUsernameConflict creates a PostAPIV1AuditDataUsernameConflict with default headers values
func NewPostAPIV1AuditDataUsernameConflict() *PostAPIV1AuditDataUsernameConflict {
	return &PostAPIV1AuditDataUsernameConflict{}
}

/*
PostAPIV1AuditDataUsernameConflict describes a response with status code 409, with default header values.

Уже существует
*/
type PostAPIV1AuditDataUsernameConflict struct {
	Payload *models.ErrorDTO
}

// IsSuccess returns true when this post Api v1 audit data username conflict response has a 2xx status code
func (o *PostAPIV1AuditDataUsernameConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 audit data username conflict response has a 3xx status code
func (o *PostAPIV1AuditDataUsernameConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 audit data username conflict response has a 4xx status code
func (o *PostAPIV1AuditDataUsernameConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 audit data username conflict response has a 5xx status code
func (o *PostAPIV1AuditDataUsernameConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 audit data username conflict response a status code equal to that given
func (o *PostAPIV1AuditDataUsernameConflict) IsCode(code int) bool {
	return code == 409
}

// Code gets the status code for the post Api v1 audit data username conflict response
func (o *PostAPIV1AuditDataUsernameConflict) Code() int {
	return 409
}

func (o *PostAPIV1AuditDataUsernameConflict) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/audit/data/username][%d] postApiV1AuditDataUsernameConflict %s", 409, payload)
}

func (o *PostAPIV1AuditDataUsernameConflict) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/audit/data/username][%d] postApiV1AuditDataUsernameConflict %s", 409, payload)
}

func (o *PostAPIV1AuditDataUsernameConflict) GetPayload() *models.ErrorDTO {
	return o.Payload
}

func (o *PostAPIV1AuditDataUsernameConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1AuditDataUsernameInternalServerError creates a PostAPIV1AuditDataUsernameInternalServerError with default headers values
func NewPostAPIV1AuditDataUsernameInternalServerError() *PostAPIV1AuditDataUsernameInternalServerError {
	return &PostAPIV1AuditDataUsernameInternalServerError{}
}

/*
PostAPIV1AuditDataUsernameInternalServerError describes a response with status code 500, with default header values.

Внутренняя ошибка сервера (пустое тело)
*/
type PostAPIV1AuditDataUsernameInternalServerError struct {
}

// IsSuccess returns true when this post Api v1 audit data username internal server error response has a 2xx status code
func (o *PostAPIV1AuditDataUsernameInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 audit data username internal server error response has a 3xx status code
func (o *PostAPIV1AuditDataUsernameInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 audit data username internal server error response has a 4xx status code
func (o *PostAPIV1AuditDataUsernameInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api v1 audit data username internal server error response has a 5xx status code
func (o *PostAPIV1AuditDataUsernameInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post Api v1 audit data username internal server error response a status code equal to that given
func (o *PostAPIV1AuditDataUsernameInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post Api v1 audit data username internal server error response
func (o *PostAPIV1AuditDataUsernameInternalServerError) Code() int {
	return 500
}

func (o *PostAPIV1AuditDataUsernameInternalServerError) Error() string {
	return fmt.Sprintf("[POST /api/v1/audit/data/username][%d] postApiV1AuditDataUsernameInternalServerError", 500)
}

func (o *PostAPIV1AuditDataUsernameInternalServerError) String() string {
	return fmt.Sprintf("[POST /api/v1/audit/data/username][%d] postApiV1AuditDataUsernameInternalServerError", 500)
}

func (o *PostAPIV1AuditDataUsernameInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
