// Code generated by go-swagger; DO NOT EDIT.

package audit

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ElfAstAhe/tiny-audit-service/pkg/api/http/audit/v1/models"
)

// PostAPIV1AuditDataReader is a Reader for the PostAPIV1AuditData structure.
type PostAPIV1AuditDataReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIV1AuditDataReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 201:
		result := NewPostAPIV1AuditDataCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostAPIV1AuditDataBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPostAPIV1AuditDataUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPostAPIV1AuditDataForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostAPIV1AuditDataInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /api/v1/audit/data] PostAPIV1AuditData", response, response.Code())
	}
}

// NewPostAPIV1AuditDataCreated creates a PostAPIV1AuditDataCreated with default headers values
func NewPostAPIV1AuditDataCreated() *PostAPIV1AuditDataCreated {
	return &PostAPIV1AuditDataCreated{}
}

/*
PostAPIV1AuditDataCreated describes a response with status code 201, with default header values.

Всё хорошо (пустое тело)
*/
type PostAPIV1AuditDataCreated struct {
}

// IsSuccess returns true when this post Api v1 audit data created response has a 2xx status code
func (o *PostAPIV1AuditDataCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post Api v1 audit data created response has a 3xx status code
func (o *PostAPIV1AuditDataCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 audit data created response has a 4xx status code
func (o *PostAPIV1AuditDataCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api v1 audit data created response has a 5xx status code
func (o *PostAPIV1AuditDataCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 audit data created response a status code equal to that given
func (o *PostAPIV1AuditDataCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the post Api v1 audit data created response
func (o *PostAPIV1AuditDataCreated) Code() int {
	return 201
}

func (o *PostAPIV1AuditDataCreated) Error() string {
	return fmt.Sprintf("[POST /api/v1/audit/data][%d] postApiV1AuditDataCreated", 201)
}

func (o *PostAPIV1AuditDataCreated) String() string {
	return fmt.Sprintf("[POST /api/v1/audit/data][%d] postApiV1AuditDataCreated", 201)
}

func (o *PostAPIV1AuditDataCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostAPIV1AuditDataBadRequest creates a PostAPIV1AuditDataBadRequest with default headers values
func NewPostAPIV1AuditDataBadRequest() *PostAPIV1AuditDataBadRequest {
	return &PostAPIV1AuditDataBadRequest{}
}

/*
PostAPIV1AuditDataBadRequest describes a response with status code 400, with default header values.

Кривые данные
*/
type PostAPIV1AuditDataBadRequest struct {
	Payload *models.ErrorDTO
}

// IsSuccess returns true when this post Api v1 audit data bad request response has a 2xx status code
func (o *PostAPIV1AuditDataBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 audit data bad request response has a 3xx status code
func (o *PostAPIV1AuditDataBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 audit data bad request response has a 4xx status code
func (o *PostAPIV1AuditDataBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 audit data bad request response has a 5xx status code
func (o *PostAPIV1AuditDataBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 audit data bad request response a status code equal to that given
func (o *PostAPIV1AuditDataBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post Api v1 audit data bad request response
func (o *PostAPIV1AuditDataBadRequest) Code() int {
	return 400
}

func (o *PostAPIV1AuditDataBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/audit/data][%d] postApiV1AuditDataBadRequest %s", 400, payload)
}

func (o *PostAPIV1AuditDataBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/audit/data][%d] postApiV1AuditDataBadRequest %s", 400, payload)
}

func (o *PostAPIV1AuditDataBadRequest) GetPayload() *models.ErrorDTO {
	return o.Payload
}

func (o *PostAPIV1AuditDataBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1AuditDataUnauthorized creates a PostAPIV1AuditDataUnauthorized with default headers values
func NewPostAPIV1AuditDataUnauthorized() *PostAPIV1AuditDataUnauthorized {
	return &PostAPIV1AuditDataUnauthorized{}
}

/*
PostAPIV1AuditDataUnauthorized describes a response with status code 401, with default header values.

Не авторизован
*/
type PostAPIV1AuditDataUnauthorized struct {
	Payload *models.ErrorDTO
}

// IsSuccess returns true when this post Api v1 audit data unauthorized response has a 2xx status code
func (o *PostAPIV1AuditDataUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 audit data unauthorized response has a 3xx status code
func (o *PostAPIV1AuditDataUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 audit data unauthorized response has a 4xx status code
func (o *PostAPIV1AuditDataUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 audit data unauthorized response has a 5xx status code
func (o *PostAPIV1AuditDataUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 audit data unauthorized response a status code equal to that given
func (o *PostAPIV1AuditDataUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the post Api v1 audit data unauthorized response
func (o *PostAPIV1AuditDataUnauthorized) Code() int {
	return 401
}

func (o *PostAPIV1AuditDataUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/audit/data][%d] postApiV1AuditDataUnauthorized %s", 401, payload)
}

func (o *PostAPIV1AuditDataUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/audit/data][%d] postApiV1AuditDataUnauthorized %s", 401, payload)
}

func (o *PostAPIV1AuditDataUnauthorized) GetPayload() *models.ErrorDTO {
	return o.Payload
}

func (o *PostAPIV1AuditDataUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1AuditDataForbidden creates a PostAPIV1AuditDataForbidden with default headers values
func NewPostAPIV1AuditDataForbidden() *PostAPIV1AuditDataForbidden {
	return &PostAPIV1AuditDataForbidden{}
}

/*
PostAPIV1AuditDataForbidden describes a response with status code 403, with default header values.

В доступе отказано
*/
type PostAPIV1AuditDataForbidden struct {
	Payload *models.ErrorDTO
}

// IsSuccess returns true when this post Api v1 audit data forbidden response has a 2xx status code
func (o *PostAPIV1AuditDataForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 audit data forbidden response has a 3xx status code
func (o *PostAPIV1AuditDataForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 audit data forbidden response has a 4xx status code
func (o *PostAPIV1AuditDataForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 audit data forbidden response has a 5xx status code
func (o *PostAPIV1AuditDataForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 audit data forbidden response a status code equal to that given
func (o *PostAPIV1AuditDataForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the post Api v1 audit data forbidden response
func (o *PostAPIV1AuditDataForbidden) Code() int {
	return 403
}

func (o *PostAPIV1AuditDataForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/audit/data][%d] postApiV1AuditDataForbidden %s", 403, payload)
}

func (o *PostAPIV1AuditDataForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/audit/data][%d] postApiV1AuditDataForbidden %s", 403, payload)
}

func (o *PostAPIV1AuditDataForbidden) GetPayload() *models.ErrorDTO {
	return o.Payload
}

func (o *PostAPIV1AuditDataForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1AuditDataInternalServerError creates a PostAPIV1AuditDataInternalServerError with default headers values
func NewPostAPIV1AuditDataInternalServerError() *PostAPIV1AuditDataInternalServerError {
	return &PostAPIV1AuditDataInternalServerError{}
}

/*
PostAPIV1AuditDataInternalServerError describes a response with status code 500, with default header values.

Внутренняя ошибка сервера (пустое тело)
*/
type PostAPIV1AuditDataInternalServerError struct {
}

// IsSuccess returns true when this post Api v1 audit data internal server error response has a 2xx status code
func (o *PostAPIV1AuditDataInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 audit data internal server error response has a 3xx status code
func (o *PostAPIV1AuditDataInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 audit data internal server error response has a 4xx status code
func (o *PostAPIV1AuditDataInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api v1 audit data internal server error response has a 5xx status code
func (o *PostAPIV1AuditDataInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post Api v1 audit data internal server error response a status code equal to that given
func (o *PostAPIV1AuditDataInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post Api v1 audit data internal server error response
func (o *PostAPIV1AuditDataInternalServerError) Code() int {
	return 500
}

func (o *PostAPIV1AuditDataInternalServerError) Error() string {
	return fmt.Sprintf("[POST /api/v1/audit/data][%d] postApiV1AuditDataInternalServerError", 500)
}

func (o *PostAPIV1AuditDataInternalServerError) String() string {
	return fmt.Sprintf("[POST /api/v1/audit/data][%d] postApiV1AuditDataInternalServerError", 500)
}

func (o *PostAPIV1AuditDataInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
