// Code generated by go-swagger; DO NOT EDIT.

package audit

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ElfAstAhe/tiny-audit-service/pkg/api/http/audit/v1/models"
)

// PostAPIV1AuditDataInstanceReader is a Reader for the PostAPIV1AuditDataInstance structure.
type PostAPIV1AuditDataInstanceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIV1AuditDataInstanceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPostAPIV1AuditDataInstanceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostAPIV1AuditDataInstanceBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPostAPIV1AuditDataInstanceUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPostAPIV1AuditDataInstanceForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewPostAPIV1AuditDataInstanceConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostAPIV1AuditDataInstanceInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /api/v1/audit/data/instance] PostAPIV1AuditDataInstance", response, response.Code())
	}
}

// NewPostAPIV1AuditDataInstanceOK creates a PostAPIV1AuditDataInstanceOK with default headers values
func NewPostAPIV1AuditDataInstanceOK() *PostAPIV1AuditDataInstanceOK {
	return &PostAPIV1AuditDataInstanceOK{}
}

/*
PostAPIV1AuditDataInstanceOK describes a response with status code 200, with default header values.

список данных аудита
*/
type PostAPIV1AuditDataInstanceOK struct {
	Payload []*models.DataAuditDTO
}

// IsSuccess returns true when this post Api v1 audit data instance o k response has a 2xx status code
func (o *PostAPIV1AuditDataInstanceOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post Api v1 audit data instance o k response has a 3xx status code
func (o *PostAPIV1AuditDataInstanceOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 audit data instance o k response has a 4xx status code
func (o *PostAPIV1AuditDataInstanceOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api v1 audit data instance o k response has a 5xx status code
func (o *PostAPIV1AuditDataInstanceOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 audit data instance o k response a status code equal to that given
func (o *PostAPIV1AuditDataInstanceOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post Api v1 audit data instance o k response
func (o *PostAPIV1AuditDataInstanceOK) Code() int {
	return 200
}

func (o *PostAPIV1AuditDataInstanceOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/audit/data/instance][%d] postApiV1AuditDataInstanceOK %s", 200, payload)
}

func (o *PostAPIV1AuditDataInstanceOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/audit/data/instance][%d] postApiV1AuditDataInstanceOK %s", 200, payload)
}

func (o *PostAPIV1AuditDataInstanceOK) GetPayload() []*models.DataAuditDTO {
	return o.Payload
}

func (o *PostAPIV1AuditDataInstanceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1AuditDataInstanceBadRequest creates a PostAPIV1AuditDataInstanceBadRequest with default headers values
func NewPostAPIV1AuditDataInstanceBadRequest() *PostAPIV1AuditDataInstanceBadRequest {
	return &PostAPIV1AuditDataInstanceBadRequest{}
}

/*
PostAPIV1AuditDataInstanceBadRequest describes a response with status code 400, with default header values.

Кривые данные
*/
type PostAPIV1AuditDataInstanceBadRequest struct {
	Payload *models.ErrorDTO
}

// IsSuccess returns true when this post Api v1 audit data instance bad request response has a 2xx status code
func (o *PostAPIV1AuditDataInstanceBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 audit data instance bad request response has a 3xx status code
func (o *PostAPIV1AuditDataInstanceBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 audit data instance bad request response has a 4xx status code
func (o *PostAPIV1AuditDataInstanceBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 audit data instance bad request response has a 5xx status code
func (o *PostAPIV1AuditDataInstanceBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 audit data instance bad request response a status code equal to that given
func (o *PostAPIV1AuditDataInstanceBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post Api v1 audit data instance bad request response
func (o *PostAPIV1AuditDataInstanceBadRequest) Code() int {
	return 400
}

func (o *PostAPIV1AuditDataInstanceBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/audit/data/instance][%d] postApiV1AuditDataInstanceBadRequest %s", 400, payload)
}

func (o *PostAPIV1AuditDataInstanceBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/audit/data/instance][%d] postApiV1AuditDataInstanceBadRequest %s", 400, payload)
}

func (o *PostAPIV1AuditDataInstanceBadRequest) GetPayload() *models.ErrorDTO {
	return o.Payload
}

func (o *PostAPIV1AuditDataInstanceBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1AuditDataInstanceUnauthorized creates a PostAPIV1AuditDataInstanceUnauthorized with default headers values
func NewPostAPIV1AuditDataInstanceUnauthorized() *PostAPIV1AuditDataInstanceUnauthorized {
	return &PostAPIV1AuditDataInstanceUnauthorized{}
}

/*
PostAPIV1AuditDataInstanceUnauthorized describes a response with status code 401, with default header values.

Не авторизован
*/
type PostAPIV1AuditDataInstanceUnauthorized struct {
	Payload *models.ErrorDTO
}

// IsSuccess returns true when this post Api v1 audit data instance unauthorized response has a 2xx status code
func (o *PostAPIV1AuditDataInstanceUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 audit data instance unauthorized response has a 3xx status code
func (o *PostAPIV1AuditDataInstanceUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 audit data instance unauthorized response has a 4xx status code
func (o *PostAPIV1AuditDataInstanceUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 audit data instance unauthorized response has a 5xx status code
func (o *PostAPIV1AuditDataInstanceUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 audit data instance unauthorized response a status code equal to that given
func (o *PostAPIV1AuditDataInstanceUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the post Api v1 audit data instance unauthorized response
func (o *PostAPIV1AuditDataInstanceUnauthorized) Code() int {
	return 401
}

func (o *PostAPIV1AuditDataInstanceUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/audit/data/instance][%d] postApiV1AuditDataInstanceUnauthorized %s", 401, payload)
}

func (o *PostAPIV1AuditDataInstanceUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/audit/data/instance][%d] postApiV1AuditDataInstanceUnauthorized %s", 401, payload)
}

func (o *PostAPIV1AuditDataInstanceUnauthorized) GetPayload() *models.ErrorDTO {
	return o.Payload
}

func (o *PostAPIV1AuditDataInstanceUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1AuditDataInstanceForbidden creates a PostAPIV1AuditDataInstanceForbidden with default headers values
func NewPostAPIV1AuditDataInstanceForbidden() *PostAPIV1AuditDataInstanceForbidden {
	return &PostAPIV1AuditDataInstanceForbidden{}
}

/*
PostAPIV1AuditDataInstanceForbidden describes a response with status code 403, with default header values.

В доступе отказано
*/
type PostAPIV1AuditDataInstanceForbidden struct {
	Payload *models.ErrorDTO
}

// IsSuccess returns true when this post Api v1 audit data instance forbidden response has a 2xx status code
func (o *PostAPIV1AuditDataInstanceForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 audit data instance forbidden response has a 3xx status code
func (o *PostAPIV1AuditDataInstanceForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 audit data instance forbidden response has a 4xx status code
func (o *PostAPIV1AuditDataInstanceForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 audit data instance forbidden response has a 5xx status code
func (o *PostAPIV1AuditDataInstanceForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 audit data instance forbidden response a status code equal to that given
func (o *PostAPIV1AuditDataInstanceForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the post Api v1 audit data instance forbidden response
func (o *PostAPIV1AuditDataInstanceForbidden) Code() int {
	return 403
}

func (o *PostAPIV1AuditDataInstanceForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/audit/data/instance][%d] postApiV1AuditDataInstanceForbidden %s", 403, payload)
}

func (o *PostAPIV1AuditDataInstanceForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/audit/data/instance][%d] postApiV1AuditDataInstanceForbidden %s", 403, payload)
}

func (o *PostAPIV1AuditDataInstanceForbidden) GetPayload() *models.ErrorDTO {
	return o.Payload
}

func (o *PostAPIV1AuditDataInstanceForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1AuditDataInstanceConflict creates a PostAPIV1AuditDataInstanceConflict with default headers values
func NewPostAPIV1AuditDataInstanceConflict() *PostAPIV1AuditDataInstanceConflict {
	return &PostAPIV1AuditDataInstanceConflict{}
}

/*
PostAPIV1AuditDataInstanceConflict describes a response with status code 409, with default header values.

Уже существует
*/
type PostAPIV1AuditDataInstanceConflict struct {
	Payload *models.ErrorDTO
}

// IsSuccess returns true when this post Api v1 audit data instance conflict response has a 2xx status code
func (o *PostAPIV1AuditDataInstanceConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 audit data instance conflict response has a 3xx status code
func (o *PostAPIV1AuditDataInstanceConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 audit data instance conflict response has a 4xx status code
func (o *PostAPIV1AuditDataInstanceConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 audit data instance conflict response has a 5xx status code
func (o *PostAPIV1AuditDataInstanceConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 audit data instance conflict response a status code equal to that given
func (o *PostAPIV1AuditDataInstanceConflict) IsCode(code int) bool {
	return code == 409
}

// Code gets the status code for the post Api v1 audit data instance conflict response
func (o *PostAPIV1AuditDataInstanceConflict) Code() int {
	return 409
}

func (o *PostAPIV1AuditDataInstanceConflict) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/audit/data/instance][%d] postApiV1AuditDataInstanceConflict %s", 409, payload)
}

func (o *PostAPIV1AuditDataInstanceConflict) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/audit/data/instance][%d] postApiV1AuditDataInstanceConflict %s", 409, payload)
}

func (o *PostAPIV1AuditDataInstanceConflict) GetPayload() *models.ErrorDTO {
	return o.Payload
}

func (o *PostAPIV1AuditDataInstanceConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1AuditDataInstanceInternalServerError creates a PostAPIV1AuditDataInstanceInternalServerError with default headers values
func NewPostAPIV1AuditDataInstanceInternalServerError() *PostAPIV1AuditDataInstanceInternalServerError {
	return &PostAPIV1AuditDataInstanceInternalServerError{}
}

/*
PostAPIV1AuditDataInstanceInternalServerError describes a response with status code 500, with default header values.

Внутренняя ошибка сервера (пустое тело)
*/
type PostAPIV1AuditDataInstanceInternalServerError struct {
}

// IsSuccess returns true when this post Api v1 audit data instance internal server error response has a 2xx status code
func (o *PostAPIV1AuditDataInstanceInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 audit data instance internal server error response has a 3xx status code
func (o *PostAPIV1AuditDataInstanceInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 audit data instance internal server error response has a 4xx status code
func (o *PostAPIV1AuditDataInstanceInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api v1 audit data instance internal server error response has a 5xx status code
func (o *PostAPIV1AuditDataInstanceInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post Api v1 audit data instance internal server error response a status code equal to that given
func (o *PostAPIV1AuditDataInstanceInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post Api v1 audit data instance internal server error response
func (o *PostAPIV1AuditDataInstanceInternalServerError) Code() int {
	return 500
}

func (o *PostAPIV1AuditDataInstanceInternalServerError) Error() string {
	return fmt.Sprintf("[POST /api/v1/audit/data/instance][%d] postApiV1AuditDataInstanceInternalServerError", 500)
}

func (o *PostAPIV1AuditDataInstanceInternalServerError) String() string {
	return fmt.Sprintf("[POST /api/v1/audit/data/instance][%d] postApiV1AuditDataInstanceInternalServerError", 500)
}

func (o *PostAPIV1AuditDataInstanceInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
