// Code generated by go-swagger; DO NOT EDIT.

package audit

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/ElfAstAhe/tiny-audit-service/pkg/api/http/audit/v1/models"
)

// NewPostAPIV1AuditDataUsernameParams creates a new PostAPIV1AuditDataUsernameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPIV1AuditDataUsernameParams() *PostAPIV1AuditDataUsernameParams {
	return &PostAPIV1AuditDataUsernameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIV1AuditDataUsernameParamsWithTimeout creates a new PostAPIV1AuditDataUsernameParams object
// with the ability to set a timeout on a request.
func NewPostAPIV1AuditDataUsernameParamsWithTimeout(timeout time.Duration) *PostAPIV1AuditDataUsernameParams {
	return &PostAPIV1AuditDataUsernameParams{
		timeout: timeout,
	}
}

// NewPostAPIV1AuditDataUsernameParamsWithContext creates a new PostAPIV1AuditDataUsernameParams object
// with the ability to set a context for a request.
func NewPostAPIV1AuditDataUsernameParamsWithContext(ctx context.Context) *PostAPIV1AuditDataUsernameParams {
	return &PostAPIV1AuditDataUsernameParams{
		Context: ctx,
	}
}

// NewPostAPIV1AuditDataUsernameParamsWithHTTPClient creates a new PostAPIV1AuditDataUsernameParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPIV1AuditDataUsernameParamsWithHTTPClient(client *http.Client) *PostAPIV1AuditDataUsernameParams {
	return &PostAPIV1AuditDataUsernameParams{
		HTTPClient: client,
	}
}

/*
PostAPIV1AuditDataUsernameParams contains all the parameters to send to the API endpoint

	for the post API v1 audit data username operation.

	Typically these are written to a http.Request.
*/
type PostAPIV1AuditDataUsernameParams struct {

	/* Input.

	   Пользователь
	*/
	Input *models.AuditUserDTO

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post API v1 audit data username params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIV1AuditDataUsernameParams) WithDefaults() *PostAPIV1AuditDataUsernameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post API v1 audit data username params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIV1AuditDataUsernameParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post API v1 audit data username params
func (o *PostAPIV1AuditDataUsernameParams) WithTimeout(timeout time.Duration) *PostAPIV1AuditDataUsernameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API v1 audit data username params
func (o *PostAPIV1AuditDataUsernameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API v1 audit data username params
func (o *PostAPIV1AuditDataUsernameParams) WithContext(ctx context.Context) *PostAPIV1AuditDataUsernameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API v1 audit data username params
func (o *PostAPIV1AuditDataUsernameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API v1 audit data username params
func (o *PostAPIV1AuditDataUsernameParams) WithHTTPClient(client *http.Client) *PostAPIV1AuditDataUsernameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API v1 audit data username params
func (o *PostAPIV1AuditDataUsernameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInput adds the input to the post API v1 audit data username params
func (o *PostAPIV1AuditDataUsernameParams) WithInput(input *models.AuditUserDTO) *PostAPIV1AuditDataUsernameParams {
	o.SetInput(input)
	return o
}

// SetInput adds the input to the post API v1 audit data username params
func (o *PostAPIV1AuditDataUsernameParams) SetInput(input *models.AuditUserDTO) {
	o.Input = input
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIV1AuditDataUsernameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Input != nil {
		if err := r.SetBodyParam(o.Input); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
