// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: tiny-audit-service/v1/auth-audit-service.proto

package tiny_audit_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthAuditRequest struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Data *AuthAudit             `protobuf:"bytes,1,opt,name=data"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AuthAuditRequest) Reset() {
	*x = AuthAuditRequest{}
	mi := &file_tiny_audit_service_v1_auth_audit_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthAuditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthAuditRequest) ProtoMessage() {}

func (x *AuthAuditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tiny_audit_service_v1_auth_audit_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AuthAuditRequest) GetData() *AuthAudit {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *AuthAuditRequest) SetData(v *AuthAudit) {
	x.xxx_hidden_Data = v
}

func (x *AuthAuditRequest) HasData() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Data != nil
}

func (x *AuthAuditRequest) ClearData() {
	x.xxx_hidden_Data = nil
}

type AuthAuditRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Data *AuthAudit
}

func (b0 AuthAuditRequest_builder) Build() *AuthAuditRequest {
	m0 := &AuthAuditRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Data = b.Data
	return m0
}

type AuthAuditInstances struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Instances *[]*AuthAudit          `protobuf:"bytes,1,rep,name=instances"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AuthAuditInstances) Reset() {
	*x = AuthAuditInstances{}
	mi := &file_tiny_audit_service_v1_auth_audit_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthAuditInstances) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthAuditInstances) ProtoMessage() {}

func (x *AuthAuditInstances) ProtoReflect() protoreflect.Message {
	mi := &file_tiny_audit_service_v1_auth_audit_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AuthAuditInstances) GetInstances() []*AuthAudit {
	if x != nil {
		if x.xxx_hidden_Instances != nil {
			return *x.xxx_hidden_Instances
		}
	}
	return nil
}

func (x *AuthAuditInstances) SetInstances(v []*AuthAudit) {
	x.xxx_hidden_Instances = &v
}

type AuthAuditInstances_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Instances []*AuthAudit
}

func (b0 AuthAuditInstances_builder) Build() *AuthAuditInstances {
	m0 := &AuthAuditInstances{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Instances = &b.Instances
	return m0
}

type AuthListByUsernameRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Username    *string                `protobuf:"bytes,1,opt,name=username"`
	xxx_hidden_Limit       uint32                 `protobuf:"varint,2,opt,name=limit"`
	xxx_hidden_Offset      uint32                 `protobuf:"varint,3,opt,name=offset"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AuthListByUsernameRequest) Reset() {
	*x = AuthListByUsernameRequest{}
	mi := &file_tiny_audit_service_v1_auth_audit_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthListByUsernameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthListByUsernameRequest) ProtoMessage() {}

func (x *AuthListByUsernameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tiny_audit_service_v1_auth_audit_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AuthListByUsernameRequest) GetUsername() string {
	if x != nil {
		if x.xxx_hidden_Username != nil {
			return *x.xxx_hidden_Username
		}
		return ""
	}
	return ""
}

func (x *AuthListByUsernameRequest) GetLimit() uint32 {
	if x != nil {
		return x.xxx_hidden_Limit
	}
	return 0
}

func (x *AuthListByUsernameRequest) GetOffset() uint32 {
	if x != nil {
		return x.xxx_hidden_Offset
	}
	return 0
}

func (x *AuthListByUsernameRequest) SetUsername(v string) {
	x.xxx_hidden_Username = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *AuthListByUsernameRequest) SetLimit(v uint32) {
	x.xxx_hidden_Limit = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *AuthListByUsernameRequest) SetOffset(v uint32) {
	x.xxx_hidden_Offset = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *AuthListByUsernameRequest) HasUsername() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AuthListByUsernameRequest) HasLimit() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *AuthListByUsernameRequest) HasOffset() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *AuthListByUsernameRequest) ClearUsername() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Username = nil
}

func (x *AuthListByUsernameRequest) ClearLimit() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Limit = 0
}

func (x *AuthListByUsernameRequest) ClearOffset() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Offset = 0
}

type AuthListByUsernameRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Username *string
	Limit    *uint32
	Offset   *uint32
}

func (b0 AuthListByUsernameRequest_builder) Build() *AuthListByUsernameRequest {
	m0 := &AuthListByUsernameRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Username != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Username = b.Username
	}
	if b.Limit != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Limit = *b.Limit
	}
	if b.Offset != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Offset = *b.Offset
	}
	return m0
}

var File_tiny_audit_service_v1_auth_audit_service_proto protoreflect.FileDescriptor

const file_tiny_audit_service_v1_auth_audit_service_proto_rawDesc = "" +
	"\n" +
	".tiny-audit-service/v1/auth-audit-service.proto\x12\raudit.service\x1a\x1bgoogle/protobuf/empty.proto\x1a$tiny-audit-service/v1/messages.proto\"@\n" +
	"\x10AuthAuditRequest\x12,\n" +
	"\x04data\x18\x01 \x01(\v2\x18.audit.service.AuthAuditR\x04data\"L\n" +
	"\x12AuthAuditInstances\x126\n" +
	"\tinstances\x18\x01 \x03(\v2\x18.audit.service.AuthAuditR\tinstances\"e\n" +
	"\x19AuthListByUsernameRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\rR\x06offset2\x8a\x02\n" +
	"\x10AuthAuditService\x12@\n" +
	"\x05Audit\x12\x1f.audit.service.AuthAuditRequest\x1a\x16.google.protobuf.Empty\x12U\n" +
	"\fListByPeriod\x12\".audit.service.ListByPeriodRequest\x1a!.audit.service.AuthAuditInstances\x12]\n" +
	"\x0eListByUsername\x12(.audit.service.AuthListByUsernameRequest\x1a!.audit.service.AuthAuditInstancesB,Z*tiny-audit-service/grpc/tiny-audit-serviceb\beditionsp\xe8\a"

var file_tiny_audit_service_v1_auth_audit_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_tiny_audit_service_v1_auth_audit_service_proto_goTypes = []any{
	(*AuthAuditRequest)(nil),          // 0: audit.service.AuthAuditRequest
	(*AuthAuditInstances)(nil),        // 1: audit.service.AuthAuditInstances
	(*AuthListByUsernameRequest)(nil), // 2: audit.service.AuthListByUsernameRequest
	(*AuthAudit)(nil),                 // 3: audit.service.AuthAudit
	(*ListByPeriodRequest)(nil),       // 4: audit.service.ListByPeriodRequest
	(*emptypb.Empty)(nil),             // 5: google.protobuf.Empty
}
var file_tiny_audit_service_v1_auth_audit_service_proto_depIdxs = []int32{
	3, // 0: audit.service.AuthAuditRequest.data:type_name -> audit.service.AuthAudit
	3, // 1: audit.service.AuthAuditInstances.instances:type_name -> audit.service.AuthAudit
	0, // 2: audit.service.AuthAuditService.Audit:input_type -> audit.service.AuthAuditRequest
	4, // 3: audit.service.AuthAuditService.ListByPeriod:input_type -> audit.service.ListByPeriodRequest
	2, // 4: audit.service.AuthAuditService.ListByUsername:input_type -> audit.service.AuthListByUsernameRequest
	5, // 5: audit.service.AuthAuditService.Audit:output_type -> google.protobuf.Empty
	1, // 6: audit.service.AuthAuditService.ListByPeriod:output_type -> audit.service.AuthAuditInstances
	1, // 7: audit.service.AuthAuditService.ListByUsername:output_type -> audit.service.AuthAuditInstances
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_tiny_audit_service_v1_auth_audit_service_proto_init() }
func file_tiny_audit_service_v1_auth_audit_service_proto_init() {
	if File_tiny_audit_service_v1_auth_audit_service_proto != nil {
		return
	}
	file_tiny_audit_service_v1_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tiny_audit_service_v1_auth_audit_service_proto_rawDesc), len(file_tiny_audit_service_v1_auth_audit_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tiny_audit_service_v1_auth_audit_service_proto_goTypes,
		DependencyIndexes: file_tiny_audit_service_v1_auth_audit_service_proto_depIdxs,
		MessageInfos:      file_tiny_audit_service_v1_auth_audit_service_proto_msgTypes,
	}.Build()
	File_tiny_audit_service_v1_auth_audit_service_proto = out.File
	file_tiny_audit_service_v1_auth_audit_service_proto_goTypes = nil
	file_tiny_audit_service_v1_auth_audit_service_proto_depIdxs = nil
}
