// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: tiny-audit-service/v1/auth-audit-service.proto

package tiny_audit_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthAuditService_Audit_FullMethodName          = "/audit.service.AuthAuditService/Audit"
	AuthAuditService_ListByPeriod_FullMethodName   = "/audit.service.AuthAuditService/ListByPeriod"
	AuthAuditService_ListByUsername_FullMethodName = "/audit.service.AuthAuditService/ListByUsername"
)

// AuthAuditServiceClient is the client API for AuthAuditService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthAuditServiceClient interface {
	Audit(ctx context.Context, in *AuthAuditRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListByPeriod(ctx context.Context, in *AuthListByPeriodRequest, opts ...grpc.CallOption) (*AuthAuditInstances, error)
	ListByUsername(ctx context.Context, in *AuthListByUsernameRequest, opts ...grpc.CallOption) (*AuthAuditInstances, error)
}

type authAuditServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthAuditServiceClient(cc grpc.ClientConnInterface) AuthAuditServiceClient {
	return &authAuditServiceClient{cc}
}

func (c *authAuditServiceClient) Audit(ctx context.Context, in *AuthAuditRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AuthAuditService_Audit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authAuditServiceClient) ListByPeriod(ctx context.Context, in *AuthListByPeriodRequest, opts ...grpc.CallOption) (*AuthAuditInstances, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthAuditInstances)
	err := c.cc.Invoke(ctx, AuthAuditService_ListByPeriod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authAuditServiceClient) ListByUsername(ctx context.Context, in *AuthListByUsernameRequest, opts ...grpc.CallOption) (*AuthAuditInstances, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthAuditInstances)
	err := c.cc.Invoke(ctx, AuthAuditService_ListByUsername_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthAuditServiceServer is the server API for AuthAuditService service.
// All implementations must embed UnimplementedAuthAuditServiceServer
// for forward compatibility.
type AuthAuditServiceServer interface {
	Audit(context.Context, *AuthAuditRequest) (*emptypb.Empty, error)
	ListByPeriod(context.Context, *AuthListByPeriodRequest) (*AuthAuditInstances, error)
	ListByUsername(context.Context, *AuthListByUsernameRequest) (*AuthAuditInstances, error)
	mustEmbedUnimplementedAuthAuditServiceServer()
}

// UnimplementedAuthAuditServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthAuditServiceServer struct{}

func (UnimplementedAuthAuditServiceServer) Audit(context.Context, *AuthAuditRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Audit not implemented")
}
func (UnimplementedAuthAuditServiceServer) ListByPeriod(context.Context, *AuthListByPeriodRequest) (*AuthAuditInstances, error) {
	return nil, status.Error(codes.Unimplemented, "method ListByPeriod not implemented")
}
func (UnimplementedAuthAuditServiceServer) ListByUsername(context.Context, *AuthListByUsernameRequest) (*AuthAuditInstances, error) {
	return nil, status.Error(codes.Unimplemented, "method ListByUsername not implemented")
}
func (UnimplementedAuthAuditServiceServer) mustEmbedUnimplementedAuthAuditServiceServer() {}
func (UnimplementedAuthAuditServiceServer) testEmbeddedByValue()                          {}

// UnsafeAuthAuditServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthAuditServiceServer will
// result in compilation errors.
type UnsafeAuthAuditServiceServer interface {
	mustEmbedUnimplementedAuthAuditServiceServer()
}

func RegisterAuthAuditServiceServer(s grpc.ServiceRegistrar, srv AuthAuditServiceServer) {
	// If the following call panics, it indicates UnimplementedAuthAuditServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthAuditService_ServiceDesc, srv)
}

func _AuthAuditService_Audit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthAuditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthAuditServiceServer).Audit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthAuditService_Audit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthAuditServiceServer).Audit(ctx, req.(*AuthAuditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthAuditService_ListByPeriod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthListByPeriodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthAuditServiceServer).ListByPeriod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthAuditService_ListByPeriod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthAuditServiceServer).ListByPeriod(ctx, req.(*AuthListByPeriodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthAuditService_ListByUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthListByUsernameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthAuditServiceServer).ListByUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthAuditService_ListByUsername_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthAuditServiceServer).ListByUsername(ctx, req.(*AuthListByUsernameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthAuditService_ServiceDesc is the grpc.ServiceDesc for AuthAuditService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthAuditService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "audit.service.AuthAuditService",
	HandlerType: (*AuthAuditServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Audit",
			Handler:    _AuthAuditService_Audit_Handler,
		},
		{
			MethodName: "ListByPeriod",
			Handler:    _AuthAuditService_ListByPeriod_Handler,
		},
		{
			MethodName: "ListByUsername",
			Handler:    _AuthAuditService_ListByUsername_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tiny-audit-service/v1/auth-audit-service.proto",
}
