// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: tiny-audit-service/v1/data-audit-service.proto

package tiny_audit_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataAuditRequest struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Data *DataAudit             `protobuf:"bytes,1,opt,name=data"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DataAuditRequest) Reset() {
	*x = DataAuditRequest{}
	mi := &file_tiny_audit_service_v1_data_audit_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataAuditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataAuditRequest) ProtoMessage() {}

func (x *DataAuditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tiny_audit_service_v1_data_audit_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DataAuditRequest) GetData() *DataAudit {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *DataAuditRequest) SetData(v *DataAudit) {
	x.xxx_hidden_Data = v
}

func (x *DataAuditRequest) HasData() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Data != nil
}

func (x *DataAuditRequest) ClearData() {
	x.xxx_hidden_Data = nil
}

type DataAuditRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Data *DataAudit
}

func (b0 DataAuditRequest_builder) Build() *DataAuditRequest {
	m0 := &DataAuditRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Data = b.Data
	return m0
}

type DataListByPeriod struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_From        *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=from"`
	xxx_hidden_Till        *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=till"`
	xxx_hidden_Limit       uint32                 `protobuf:"varint,3,opt,name=limit"`
	xxx_hidden_Offset      uint32                 `protobuf:"varint,4,opt,name=offset"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DataListByPeriod) Reset() {
	*x = DataListByPeriod{}
	mi := &file_tiny_audit_service_v1_data_audit_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataListByPeriod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataListByPeriod) ProtoMessage() {}

func (x *DataListByPeriod) ProtoReflect() protoreflect.Message {
	mi := &file_tiny_audit_service_v1_data_audit_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DataListByPeriod) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_From
	}
	return nil
}

func (x *DataListByPeriod) GetTill() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Till
	}
	return nil
}

func (x *DataListByPeriod) GetLimit() uint32 {
	if x != nil {
		return x.xxx_hidden_Limit
	}
	return 0
}

func (x *DataListByPeriod) GetOffset() uint32 {
	if x != nil {
		return x.xxx_hidden_Offset
	}
	return 0
}

func (x *DataListByPeriod) SetFrom(v *timestamppb.Timestamp) {
	x.xxx_hidden_From = v
}

func (x *DataListByPeriod) SetTill(v *timestamppb.Timestamp) {
	x.xxx_hidden_Till = v
}

func (x *DataListByPeriod) SetLimit(v uint32) {
	x.xxx_hidden_Limit = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *DataListByPeriod) SetOffset(v uint32) {
	x.xxx_hidden_Offset = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *DataListByPeriod) HasFrom() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_From != nil
}

func (x *DataListByPeriod) HasTill() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Till != nil
}

func (x *DataListByPeriod) HasLimit() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *DataListByPeriod) HasOffset() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *DataListByPeriod) ClearFrom() {
	x.xxx_hidden_From = nil
}

func (x *DataListByPeriod) ClearTill() {
	x.xxx_hidden_Till = nil
}

func (x *DataListByPeriod) ClearLimit() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Limit = 0
}

func (x *DataListByPeriod) ClearOffset() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Offset = 0
}

type DataListByPeriod_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	From   *timestamppb.Timestamp
	Till   *timestamppb.Timestamp
	Limit  *uint32
	Offset *uint32
}

func (b0 DataListByPeriod_builder) Build() *DataListByPeriod {
	m0 := &DataListByPeriod{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_From = b.From
	x.xxx_hidden_Till = b.Till
	if b.Limit != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Limit = *b.Limit
	}
	if b.Offset != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_Offset = *b.Offset
	}
	return m0
}

type DataAuditInstances struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Instances *[]*DataAudit          `protobuf:"bytes,1,rep,name=instances"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DataAuditInstances) Reset() {
	*x = DataAuditInstances{}
	mi := &file_tiny_audit_service_v1_data_audit_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataAuditInstances) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataAuditInstances) ProtoMessage() {}

func (x *DataAuditInstances) ProtoReflect() protoreflect.Message {
	mi := &file_tiny_audit_service_v1_data_audit_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DataAuditInstances) GetInstances() []*DataAudit {
	if x != nil {
		if x.xxx_hidden_Instances != nil {
			return *x.xxx_hidden_Instances
		}
	}
	return nil
}

func (x *DataAuditInstances) SetInstances(v []*DataAudit) {
	x.xxx_hidden_Instances = &v
}

type DataAuditInstances_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Instances []*DataAudit
}

func (b0 DataAuditInstances_builder) Build() *DataAuditInstances {
	m0 := &DataAuditInstances{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Instances = &b.Instances
	return m0
}

type DataListByInstance struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TypeName    *string                `protobuf:"bytes,1,opt,name=type_name,json=typeName"`
	xxx_hidden_InstanceId  *string                `protobuf:"bytes,2,opt,name=instance_id,json=instanceId"`
	xxx_hidden_Limit       uint32                 `protobuf:"varint,3,opt,name=limit"`
	xxx_hidden_Offset      uint32                 `protobuf:"varint,4,opt,name=offset"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DataListByInstance) Reset() {
	*x = DataListByInstance{}
	mi := &file_tiny_audit_service_v1_data_audit_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataListByInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataListByInstance) ProtoMessage() {}

func (x *DataListByInstance) ProtoReflect() protoreflect.Message {
	mi := &file_tiny_audit_service_v1_data_audit_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DataListByInstance) GetTypeName() string {
	if x != nil {
		if x.xxx_hidden_TypeName != nil {
			return *x.xxx_hidden_TypeName
		}
		return ""
	}
	return ""
}

func (x *DataListByInstance) GetInstanceId() string {
	if x != nil {
		if x.xxx_hidden_InstanceId != nil {
			return *x.xxx_hidden_InstanceId
		}
		return ""
	}
	return ""
}

func (x *DataListByInstance) GetLimit() uint32 {
	if x != nil {
		return x.xxx_hidden_Limit
	}
	return 0
}

func (x *DataListByInstance) GetOffset() uint32 {
	if x != nil {
		return x.xxx_hidden_Offset
	}
	return 0
}

func (x *DataListByInstance) SetTypeName(v string) {
	x.xxx_hidden_TypeName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *DataListByInstance) SetInstanceId(v string) {
	x.xxx_hidden_InstanceId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *DataListByInstance) SetLimit(v uint32) {
	x.xxx_hidden_Limit = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *DataListByInstance) SetOffset(v uint32) {
	x.xxx_hidden_Offset = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *DataListByInstance) HasTypeName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DataListByInstance) HasInstanceId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *DataListByInstance) HasLimit() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *DataListByInstance) HasOffset() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *DataListByInstance) ClearTypeName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_TypeName = nil
}

func (x *DataListByInstance) ClearInstanceId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_InstanceId = nil
}

func (x *DataListByInstance) ClearLimit() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Limit = 0
}

func (x *DataListByInstance) ClearOffset() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Offset = 0
}

type DataListByInstance_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TypeName   *string
	InstanceId *string
	Limit      *uint32
	Offset     *uint32
}

func (b0 DataListByInstance_builder) Build() *DataListByInstance {
	m0 := &DataListByInstance{}
	b, x := &b0, m0
	_, _ = b, x
	if b.TypeName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_TypeName = b.TypeName
	}
	if b.InstanceId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_InstanceId = b.InstanceId
	}
	if b.Limit != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Limit = *b.Limit
	}
	if b.Offset != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_Offset = *b.Offset
	}
	return m0
}

var File_tiny_audit_service_v1_data_audit_service_proto protoreflect.FileDescriptor

const file_tiny_audit_service_v1_data_audit_service_proto_rawDesc = "" +
	"\n" +
	".tiny-audit-service/v1/data-audit-service.proto\x12\raudit.service\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a$tiny-audit-service/v1/messages.proto\"@\n" +
	"\x10DataAuditRequest\x12,\n" +
	"\x04data\x18\x01 \x01(\v2\x18.audit.service.DataAuditR\x04data\"\xa0\x01\n" +
	"\x10DataListByPeriod\x12.\n" +
	"\x04from\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12.\n" +
	"\x04till\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04till\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\rR\x06offset\"L\n" +
	"\x12DataAuditInstances\x126\n" +
	"\tinstances\x18\x01 \x03(\v2\x18.audit.service.DataAuditR\tinstances\"\x80\x01\n" +
	"\x12DataListByInstance\x12\x1b\n" +
	"\ttype_name\x18\x01 \x01(\tR\btypeName\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\rR\x06offset2\x80\x02\n" +
	"\x10DataAuditService\x12@\n" +
	"\x05Audit\x12\x1f.audit.service.DataAuditRequest\x1a\x16.google.protobuf.Empty\x12R\n" +
	"\fListByPeriod\x12\x1f.audit.service.DataListByPeriod\x1a!.audit.service.DataAuditInstances\x12V\n" +
	"\x0eListByInstance\x12!.audit.service.DataListByInstance\x1a!.audit.service.DataAuditInstancesB,Z*tiny-audit-service/grpc/tiny-audit-serviceb\beditionsp\xe8\a"

var file_tiny_audit_service_v1_data_audit_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_tiny_audit_service_v1_data_audit_service_proto_goTypes = []any{
	(*DataAuditRequest)(nil),      // 0: audit.service.DataAuditRequest
	(*DataListByPeriod)(nil),      // 1: audit.service.DataListByPeriod
	(*DataAuditInstances)(nil),    // 2: audit.service.DataAuditInstances
	(*DataListByInstance)(nil),    // 3: audit.service.DataListByInstance
	(*DataAudit)(nil),             // 4: audit.service.DataAudit
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 6: google.protobuf.Empty
}
var file_tiny_audit_service_v1_data_audit_service_proto_depIdxs = []int32{
	4, // 0: audit.service.DataAuditRequest.data:type_name -> audit.service.DataAudit
	5, // 1: audit.service.DataListByPeriod.from:type_name -> google.protobuf.Timestamp
	5, // 2: audit.service.DataListByPeriod.till:type_name -> google.protobuf.Timestamp
	4, // 3: audit.service.DataAuditInstances.instances:type_name -> audit.service.DataAudit
	0, // 4: audit.service.DataAuditService.Audit:input_type -> audit.service.DataAuditRequest
	1, // 5: audit.service.DataAuditService.ListByPeriod:input_type -> audit.service.DataListByPeriod
	3, // 6: audit.service.DataAuditService.ListByInstance:input_type -> audit.service.DataListByInstance
	6, // 7: audit.service.DataAuditService.Audit:output_type -> google.protobuf.Empty
	2, // 8: audit.service.DataAuditService.ListByPeriod:output_type -> audit.service.DataAuditInstances
	2, // 9: audit.service.DataAuditService.ListByInstance:output_type -> audit.service.DataAuditInstances
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_tiny_audit_service_v1_data_audit_service_proto_init() }
func file_tiny_audit_service_v1_data_audit_service_proto_init() {
	if File_tiny_audit_service_v1_data_audit_service_proto != nil {
		return
	}
	file_tiny_audit_service_v1_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tiny_audit_service_v1_data_audit_service_proto_rawDesc), len(file_tiny_audit_service_v1_data_audit_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tiny_audit_service_v1_data_audit_service_proto_goTypes,
		DependencyIndexes: file_tiny_audit_service_v1_data_audit_service_proto_depIdxs,
		MessageInfos:      file_tiny_audit_service_v1_data_audit_service_proto_msgTypes,
	}.Build()
	File_tiny_audit_service_v1_data_audit_service_proto = out.File
	file_tiny_audit_service_v1_data_audit_service_proto_goTypes = nil
	file_tiny_audit_service_v1_data_audit_service_proto_depIdxs = nil
}
