// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: tiny-audit-service/v1/data-audit-service.proto

package tiny_audit_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataAuditRequest struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Data *DataAudit             `protobuf:"bytes,1,opt,name=data"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DataAuditRequest) Reset() {
	*x = DataAuditRequest{}
	mi := &file_tiny_audit_service_v1_data_audit_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataAuditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataAuditRequest) ProtoMessage() {}

func (x *DataAuditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tiny_audit_service_v1_data_audit_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DataAuditRequest) GetData() *DataAudit {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *DataAuditRequest) SetData(v *DataAudit) {
	x.xxx_hidden_Data = v
}

func (x *DataAuditRequest) HasData() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Data != nil
}

func (x *DataAuditRequest) ClearData() {
	x.xxx_hidden_Data = nil
}

type DataAuditRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Data *DataAudit
}

func (b0 DataAuditRequest_builder) Build() *DataAuditRequest {
	m0 := &DataAuditRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Data = b.Data
	return m0
}

type DataAuditInstances struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Instances *[]*DataAudit          `protobuf:"bytes,1,rep,name=instances"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DataAuditInstances) Reset() {
	*x = DataAuditInstances{}
	mi := &file_tiny_audit_service_v1_data_audit_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataAuditInstances) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataAuditInstances) ProtoMessage() {}

func (x *DataAuditInstances) ProtoReflect() protoreflect.Message {
	mi := &file_tiny_audit_service_v1_data_audit_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DataAuditInstances) GetInstances() []*DataAudit {
	if x != nil {
		if x.xxx_hidden_Instances != nil {
			return *x.xxx_hidden_Instances
		}
	}
	return nil
}

func (x *DataAuditInstances) SetInstances(v []*DataAudit) {
	x.xxx_hidden_Instances = &v
}

type DataAuditInstances_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Instances []*DataAudit
}

func (b0 DataAuditInstances_builder) Build() *DataAuditInstances {
	m0 := &DataAuditInstances{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Instances = &b.Instances
	return m0
}

type ListByInstanceRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TypeName    *string                `protobuf:"bytes,1,opt,name=type_name,json=typeName"`
	xxx_hidden_InstanceId  *string                `protobuf:"bytes,2,opt,name=instance_id,json=instanceId"`
	xxx_hidden_Limit       uint32                 `protobuf:"varint,3,opt,name=limit"`
	xxx_hidden_Offset      uint32                 `protobuf:"varint,4,opt,name=offset"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ListByInstanceRequest) Reset() {
	*x = ListByInstanceRequest{}
	mi := &file_tiny_audit_service_v1_data_audit_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListByInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListByInstanceRequest) ProtoMessage() {}

func (x *ListByInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tiny_audit_service_v1_data_audit_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListByInstanceRequest) GetTypeName() string {
	if x != nil {
		if x.xxx_hidden_TypeName != nil {
			return *x.xxx_hidden_TypeName
		}
		return ""
	}
	return ""
}

func (x *ListByInstanceRequest) GetInstanceId() string {
	if x != nil {
		if x.xxx_hidden_InstanceId != nil {
			return *x.xxx_hidden_InstanceId
		}
		return ""
	}
	return ""
}

func (x *ListByInstanceRequest) GetLimit() uint32 {
	if x != nil {
		return x.xxx_hidden_Limit
	}
	return 0
}

func (x *ListByInstanceRequest) GetOffset() uint32 {
	if x != nil {
		return x.xxx_hidden_Offset
	}
	return 0
}

func (x *ListByInstanceRequest) SetTypeName(v string) {
	x.xxx_hidden_TypeName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *ListByInstanceRequest) SetInstanceId(v string) {
	x.xxx_hidden_InstanceId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *ListByInstanceRequest) SetLimit(v uint32) {
	x.xxx_hidden_Limit = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *ListByInstanceRequest) SetOffset(v uint32) {
	x.xxx_hidden_Offset = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *ListByInstanceRequest) HasTypeName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ListByInstanceRequest) HasInstanceId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ListByInstanceRequest) HasLimit() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ListByInstanceRequest) HasOffset() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *ListByInstanceRequest) ClearTypeName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_TypeName = nil
}

func (x *ListByInstanceRequest) ClearInstanceId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_InstanceId = nil
}

func (x *ListByInstanceRequest) ClearLimit() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Limit = 0
}

func (x *ListByInstanceRequest) ClearOffset() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Offset = 0
}

type ListByInstanceRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TypeName   *string
	InstanceId *string
	Limit      *uint32
	Offset     *uint32
}

func (b0 ListByInstanceRequest_builder) Build() *ListByInstanceRequest {
	m0 := &ListByInstanceRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.TypeName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_TypeName = b.TypeName
	}
	if b.InstanceId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_InstanceId = b.InstanceId
	}
	if b.Limit != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Limit = *b.Limit
	}
	if b.Offset != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_Offset = *b.Offset
	}
	return m0
}

var File_tiny_audit_service_v1_data_audit_service_proto protoreflect.FileDescriptor

const file_tiny_audit_service_v1_data_audit_service_proto_rawDesc = "" +
	"\n" +
	".tiny-audit-service/v1/data-audit-service.proto\x12\raudit.service\x1a\x1bgoogle/protobuf/empty.proto\x1a$tiny-audit-service/v1/messages.proto\"@\n" +
	"\x10DataAuditRequest\x12,\n" +
	"\x04data\x18\x01 \x01(\v2\x18.audit.service.DataAuditR\x04data\"L\n" +
	"\x12DataAuditInstances\x126\n" +
	"\tinstances\x18\x01 \x03(\v2\x18.audit.service.DataAuditR\tinstances\"\x83\x01\n" +
	"\x15ListByInstanceRequest\x12\x1b\n" +
	"\ttype_name\x18\x01 \x01(\tR\btypeName\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\rR\x06offset2\x86\x02\n" +
	"\x10DataAuditService\x12@\n" +
	"\x05Audit\x12\x1f.audit.service.DataAuditRequest\x1a\x16.google.protobuf.Empty\x12U\n" +
	"\fListByPeriod\x12\".audit.service.ListByPeriodRequest\x1a!.audit.service.DataAuditInstances\x12Y\n" +
	"\x0eListByInstance\x12$.audit.service.ListByInstanceRequest\x1a!.audit.service.DataAuditInstancesB,Z*tiny-audit-service/grpc/tiny-audit-serviceb\beditionsp\xe8\a"

var file_tiny_audit_service_v1_data_audit_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_tiny_audit_service_v1_data_audit_service_proto_goTypes = []any{
	(*DataAuditRequest)(nil),      // 0: audit.service.DataAuditRequest
	(*DataAuditInstances)(nil),    // 1: audit.service.DataAuditInstances
	(*ListByInstanceRequest)(nil), // 2: audit.service.ListByInstanceRequest
	(*DataAudit)(nil),             // 3: audit.service.DataAudit
	(*ListByPeriodRequest)(nil),   // 4: audit.service.ListByPeriodRequest
	(*emptypb.Empty)(nil),         // 5: google.protobuf.Empty
}
var file_tiny_audit_service_v1_data_audit_service_proto_depIdxs = []int32{
	3, // 0: audit.service.DataAuditRequest.data:type_name -> audit.service.DataAudit
	3, // 1: audit.service.DataAuditInstances.instances:type_name -> audit.service.DataAudit
	0, // 2: audit.service.DataAuditService.Audit:input_type -> audit.service.DataAuditRequest
	4, // 3: audit.service.DataAuditService.ListByPeriod:input_type -> audit.service.ListByPeriodRequest
	2, // 4: audit.service.DataAuditService.ListByInstance:input_type -> audit.service.ListByInstanceRequest
	5, // 5: audit.service.DataAuditService.Audit:output_type -> google.protobuf.Empty
	1, // 6: audit.service.DataAuditService.ListByPeriod:output_type -> audit.service.DataAuditInstances
	1, // 7: audit.service.DataAuditService.ListByInstance:output_type -> audit.service.DataAuditInstances
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_tiny_audit_service_v1_data_audit_service_proto_init() }
func file_tiny_audit_service_v1_data_audit_service_proto_init() {
	if File_tiny_audit_service_v1_data_audit_service_proto != nil {
		return
	}
	file_tiny_audit_service_v1_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tiny_audit_service_v1_data_audit_service_proto_rawDesc), len(file_tiny_audit_service_v1_data_audit_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tiny_audit_service_v1_data_audit_service_proto_goTypes,
		DependencyIndexes: file_tiny_audit_service_v1_data_audit_service_proto_depIdxs,
		MessageInfos:      file_tiny_audit_service_v1_data_audit_service_proto_msgTypes,
	}.Build()
	File_tiny_audit_service_v1_data_audit_service_proto = out.File
	file_tiny_audit_service_v1_data_audit_service_proto_goTypes = nil
	file_tiny_audit_service_v1_data_audit_service_proto_depIdxs = nil
}
