// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: tiny-audit-service/v1/data-audit-service.proto

package tiny_audit_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataAuditService_Audit_FullMethodName          = "/audit.service.DataAuditService/Audit"
	DataAuditService_ListByPeriod_FullMethodName   = "/audit.service.DataAuditService/ListByPeriod"
	DataAuditService_ListByInstance_FullMethodName = "/audit.service.DataAuditService/ListByInstance"
)

// DataAuditServiceClient is the client API for DataAuditService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataAuditServiceClient interface {
	Audit(ctx context.Context, in *DataAuditRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListByPeriod(ctx context.Context, in *ListByPeriodRequest, opts ...grpc.CallOption) (*DataAuditInstances, error)
	ListByInstance(ctx context.Context, in *ListByInstanceRequest, opts ...grpc.CallOption) (*DataAuditInstances, error)
}

type dataAuditServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataAuditServiceClient(cc grpc.ClientConnInterface) DataAuditServiceClient {
	return &dataAuditServiceClient{cc}
}

func (c *dataAuditServiceClient) Audit(ctx context.Context, in *DataAuditRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DataAuditService_Audit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataAuditServiceClient) ListByPeriod(ctx context.Context, in *ListByPeriodRequest, opts ...grpc.CallOption) (*DataAuditInstances, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DataAuditInstances)
	err := c.cc.Invoke(ctx, DataAuditService_ListByPeriod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataAuditServiceClient) ListByInstance(ctx context.Context, in *ListByInstanceRequest, opts ...grpc.CallOption) (*DataAuditInstances, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DataAuditInstances)
	err := c.cc.Invoke(ctx, DataAuditService_ListByInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataAuditServiceServer is the server API for DataAuditService service.
// All implementations must embed UnimplementedDataAuditServiceServer
// for forward compatibility.
type DataAuditServiceServer interface {
	Audit(context.Context, *DataAuditRequest) (*emptypb.Empty, error)
	ListByPeriod(context.Context, *ListByPeriodRequest) (*DataAuditInstances, error)
	ListByInstance(context.Context, *ListByInstanceRequest) (*DataAuditInstances, error)
	mustEmbedUnimplementedDataAuditServiceServer()
}

// UnimplementedDataAuditServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataAuditServiceServer struct{}

func (UnimplementedDataAuditServiceServer) Audit(context.Context, *DataAuditRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Audit not implemented")
}
func (UnimplementedDataAuditServiceServer) ListByPeriod(context.Context, *ListByPeriodRequest) (*DataAuditInstances, error) {
	return nil, status.Error(codes.Unimplemented, "method ListByPeriod not implemented")
}
func (UnimplementedDataAuditServiceServer) ListByInstance(context.Context, *ListByInstanceRequest) (*DataAuditInstances, error) {
	return nil, status.Error(codes.Unimplemented, "method ListByInstance not implemented")
}
func (UnimplementedDataAuditServiceServer) mustEmbedUnimplementedDataAuditServiceServer() {}
func (UnimplementedDataAuditServiceServer) testEmbeddedByValue()                          {}

// UnsafeDataAuditServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataAuditServiceServer will
// result in compilation errors.
type UnsafeDataAuditServiceServer interface {
	mustEmbedUnimplementedDataAuditServiceServer()
}

func RegisterDataAuditServiceServer(s grpc.ServiceRegistrar, srv DataAuditServiceServer) {
	// If the following call panics, it indicates UnimplementedDataAuditServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataAuditService_ServiceDesc, srv)
}

func _DataAuditService_Audit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataAuditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataAuditServiceServer).Audit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataAuditService_Audit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataAuditServiceServer).Audit(ctx, req.(*DataAuditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataAuditService_ListByPeriod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListByPeriodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataAuditServiceServer).ListByPeriod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataAuditService_ListByPeriod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataAuditServiceServer).ListByPeriod(ctx, req.(*ListByPeriodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataAuditService_ListByInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListByInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataAuditServiceServer).ListByInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataAuditService_ListByInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataAuditServiceServer).ListByInstance(ctx, req.(*ListByInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataAuditService_ServiceDesc is the grpc.ServiceDesc for DataAuditService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataAuditService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "audit.service.DataAuditService",
	HandlerType: (*DataAuditServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Audit",
			Handler:    _DataAuditService_Audit_Handler,
		},
		{
			MethodName: "ListByPeriod",
			Handler:    _DataAuditService_ListByPeriod_Handler,
		},
		{
			MethodName: "ListByInstance",
			Handler:    _DataAuditService_ListByInstance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tiny-audit-service/v1/data-audit-service.proto",
}
