// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: tiny-audit-service/v1/messages.proto

package tiny_audit_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListByPeriodRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_From        *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=from"`
	xxx_hidden_Till        *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=till"`
	xxx_hidden_Limit       uint32                 `protobuf:"varint,3,opt,name=limit"`
	xxx_hidden_Offset      uint32                 `protobuf:"varint,4,opt,name=offset"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ListByPeriodRequest) Reset() {
	*x = ListByPeriodRequest{}
	mi := &file_tiny_audit_service_v1_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListByPeriodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListByPeriodRequest) ProtoMessage() {}

func (x *ListByPeriodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tiny_audit_service_v1_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListByPeriodRequest) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_From
	}
	return nil
}

func (x *ListByPeriodRequest) GetTill() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Till
	}
	return nil
}

func (x *ListByPeriodRequest) GetLimit() uint32 {
	if x != nil {
		return x.xxx_hidden_Limit
	}
	return 0
}

func (x *ListByPeriodRequest) GetOffset() uint32 {
	if x != nil {
		return x.xxx_hidden_Offset
	}
	return 0
}

func (x *ListByPeriodRequest) SetFrom(v *timestamppb.Timestamp) {
	x.xxx_hidden_From = v
}

func (x *ListByPeriodRequest) SetTill(v *timestamppb.Timestamp) {
	x.xxx_hidden_Till = v
}

func (x *ListByPeriodRequest) SetLimit(v uint32) {
	x.xxx_hidden_Limit = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *ListByPeriodRequest) SetOffset(v uint32) {
	x.xxx_hidden_Offset = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *ListByPeriodRequest) HasFrom() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_From != nil
}

func (x *ListByPeriodRequest) HasTill() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Till != nil
}

func (x *ListByPeriodRequest) HasLimit() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ListByPeriodRequest) HasOffset() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *ListByPeriodRequest) ClearFrom() {
	x.xxx_hidden_From = nil
}

func (x *ListByPeriodRequest) ClearTill() {
	x.xxx_hidden_Till = nil
}

func (x *ListByPeriodRequest) ClearLimit() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Limit = 0
}

func (x *ListByPeriodRequest) ClearOffset() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Offset = 0
}

type ListByPeriodRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	From   *timestamppb.Timestamp
	Till   *timestamppb.Timestamp
	Limit  *uint32
	Offset *uint32
}

func (b0 ListByPeriodRequest_builder) Build() *ListByPeriodRequest {
	m0 := &ListByPeriodRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_From = b.From
	x.xxx_hidden_Till = b.Till
	if b.Limit != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Limit = *b.Limit
	}
	if b.Offset != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_Offset = *b.Offset
	}
	return m0
}

type AuthAudit struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id           *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Source       *string                `protobuf:"bytes,2,opt,name=source"`
	xxx_hidden_EventDate    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=event_date,json=eventDate"`
	xxx_hidden_Event        *string                `protobuf:"bytes,4,opt,name=event"`
	xxx_hidden_Status       *string                `protobuf:"bytes,5,opt,name=status"`
	xxx_hidden_RequestId    *string                `protobuf:"bytes,6,opt,name=request_id,json=requestId"`
	xxx_hidden_TraceId      *string                `protobuf:"bytes,7,opt,name=trace_id,json=traceId"`
	xxx_hidden_Username     *string                `protobuf:"bytes,8,opt,name=username"`
	xxx_hidden_AccessToken  *string                `protobuf:"bytes,9,opt,name=access_token,json=accessToken"`
	xxx_hidden_RefreshToken *string                `protobuf:"bytes,10,opt,name=refresh_token,json=refreshToken"`
	xxx_hidden_CreateAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=create_at,json=createAt"`
	xxx_hidden_UpdateAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=update_at,json=updateAt"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *AuthAudit) Reset() {
	*x = AuthAudit{}
	mi := &file_tiny_audit_service_v1_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthAudit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthAudit) ProtoMessage() {}

func (x *AuthAudit) ProtoReflect() protoreflect.Message {
	mi := &file_tiny_audit_service_v1_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AuthAudit) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *AuthAudit) GetSource() string {
	if x != nil {
		if x.xxx_hidden_Source != nil {
			return *x.xxx_hidden_Source
		}
		return ""
	}
	return ""
}

func (x *AuthAudit) GetEventDate() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_EventDate
	}
	return nil
}

func (x *AuthAudit) GetEvent() string {
	if x != nil {
		if x.xxx_hidden_Event != nil {
			return *x.xxx_hidden_Event
		}
		return ""
	}
	return ""
}

func (x *AuthAudit) GetStatus() string {
	if x != nil {
		if x.xxx_hidden_Status != nil {
			return *x.xxx_hidden_Status
		}
		return ""
	}
	return ""
}

func (x *AuthAudit) GetRequestId() string {
	if x != nil {
		if x.xxx_hidden_RequestId != nil {
			return *x.xxx_hidden_RequestId
		}
		return ""
	}
	return ""
}

func (x *AuthAudit) GetTraceId() string {
	if x != nil {
		if x.xxx_hidden_TraceId != nil {
			return *x.xxx_hidden_TraceId
		}
		return ""
	}
	return ""
}

func (x *AuthAudit) GetUsername() string {
	if x != nil {
		if x.xxx_hidden_Username != nil {
			return *x.xxx_hidden_Username
		}
		return ""
	}
	return ""
}

func (x *AuthAudit) GetAccessToken() string {
	if x != nil {
		if x.xxx_hidden_AccessToken != nil {
			return *x.xxx_hidden_AccessToken
		}
		return ""
	}
	return ""
}

func (x *AuthAudit) GetRefreshToken() string {
	if x != nil {
		if x.xxx_hidden_RefreshToken != nil {
			return *x.xxx_hidden_RefreshToken
		}
		return ""
	}
	return ""
}

func (x *AuthAudit) GetCreateAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreateAt
	}
	return nil
}

func (x *AuthAudit) GetUpdateAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_UpdateAt
	}
	return nil
}

func (x *AuthAudit) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 12)
}

func (x *AuthAudit) SetSource(v string) {
	x.xxx_hidden_Source = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 12)
}

func (x *AuthAudit) SetEventDate(v *timestamppb.Timestamp) {
	x.xxx_hidden_EventDate = v
}

func (x *AuthAudit) SetEvent(v string) {
	x.xxx_hidden_Event = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 12)
}

func (x *AuthAudit) SetStatus(v string) {
	x.xxx_hidden_Status = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 12)
}

func (x *AuthAudit) SetRequestId(v string) {
	x.xxx_hidden_RequestId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 12)
}

func (x *AuthAudit) SetTraceId(v string) {
	x.xxx_hidden_TraceId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 12)
}

func (x *AuthAudit) SetUsername(v string) {
	x.xxx_hidden_Username = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 12)
}

func (x *AuthAudit) SetAccessToken(v string) {
	x.xxx_hidden_AccessToken = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 12)
}

func (x *AuthAudit) SetRefreshToken(v string) {
	x.xxx_hidden_RefreshToken = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 9, 12)
}

func (x *AuthAudit) SetCreateAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreateAt = v
}

func (x *AuthAudit) SetUpdateAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_UpdateAt = v
}

func (x *AuthAudit) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AuthAudit) HasSource() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *AuthAudit) HasEventDate() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_EventDate != nil
}

func (x *AuthAudit) HasEvent() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *AuthAudit) HasStatus() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *AuthAudit) HasRequestId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *AuthAudit) HasTraceId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *AuthAudit) HasUsername() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *AuthAudit) HasAccessToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *AuthAudit) HasRefreshToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 9)
}

func (x *AuthAudit) HasCreateAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreateAt != nil
}

func (x *AuthAudit) HasUpdateAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_UpdateAt != nil
}

func (x *AuthAudit) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *AuthAudit) ClearSource() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Source = nil
}

func (x *AuthAudit) ClearEventDate() {
	x.xxx_hidden_EventDate = nil
}

func (x *AuthAudit) ClearEvent() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Event = nil
}

func (x *AuthAudit) ClearStatus() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Status = nil
}

func (x *AuthAudit) ClearRequestId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_RequestId = nil
}

func (x *AuthAudit) ClearTraceId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_TraceId = nil
}

func (x *AuthAudit) ClearUsername() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_Username = nil
}

func (x *AuthAudit) ClearAccessToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_AccessToken = nil
}

func (x *AuthAudit) ClearRefreshToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 9)
	x.xxx_hidden_RefreshToken = nil
}

func (x *AuthAudit) ClearCreateAt() {
	x.xxx_hidden_CreateAt = nil
}

func (x *AuthAudit) ClearUpdateAt() {
	x.xxx_hidden_UpdateAt = nil
}

type AuthAudit_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id           *string
	Source       *string
	EventDate    *timestamppb.Timestamp
	Event        *string
	Status       *string
	RequestId    *string
	TraceId      *string
	Username     *string
	AccessToken  *string
	RefreshToken *string
	CreateAt     *timestamppb.Timestamp
	UpdateAt     *timestamppb.Timestamp
}

func (b0 AuthAudit_builder) Build() *AuthAudit {
	m0 := &AuthAudit{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 12)
		x.xxx_hidden_Id = b.Id
	}
	if b.Source != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 12)
		x.xxx_hidden_Source = b.Source
	}
	x.xxx_hidden_EventDate = b.EventDate
	if b.Event != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 12)
		x.xxx_hidden_Event = b.Event
	}
	if b.Status != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 12)
		x.xxx_hidden_Status = b.Status
	}
	if b.RequestId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 12)
		x.xxx_hidden_RequestId = b.RequestId
	}
	if b.TraceId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 12)
		x.xxx_hidden_TraceId = b.TraceId
	}
	if b.Username != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 12)
		x.xxx_hidden_Username = b.Username
	}
	if b.AccessToken != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 12)
		x.xxx_hidden_AccessToken = b.AccessToken
	}
	if b.RefreshToken != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 9, 12)
		x.xxx_hidden_RefreshToken = b.RefreshToken
	}
	x.xxx_hidden_CreateAt = b.CreateAt
	x.xxx_hidden_UpdateAt = b.UpdateAt
	return m0
}

type DataAuditValue struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        *string                `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_Description *string                `protobuf:"bytes,2,opt,name=description"`
	xxx_hidden_Before      *string                `protobuf:"bytes,3,opt,name=before"`
	xxx_hidden_After       *string                `protobuf:"bytes,4,opt,name=after"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DataAuditValue) Reset() {
	*x = DataAuditValue{}
	mi := &file_tiny_audit_service_v1_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataAuditValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataAuditValue) ProtoMessage() {}

func (x *DataAuditValue) ProtoReflect() protoreflect.Message {
	mi := &file_tiny_audit_service_v1_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DataAuditValue) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *DataAuditValue) GetDescription() string {
	if x != nil {
		if x.xxx_hidden_Description != nil {
			return *x.xxx_hidden_Description
		}
		return ""
	}
	return ""
}

func (x *DataAuditValue) GetBefore() string {
	if x != nil {
		if x.xxx_hidden_Before != nil {
			return *x.xxx_hidden_Before
		}
		return ""
	}
	return ""
}

func (x *DataAuditValue) GetAfter() string {
	if x != nil {
		if x.xxx_hidden_After != nil {
			return *x.xxx_hidden_After
		}
		return ""
	}
	return ""
}

func (x *DataAuditValue) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *DataAuditValue) SetDescription(v string) {
	x.xxx_hidden_Description = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *DataAuditValue) SetBefore(v string) {
	x.xxx_hidden_Before = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *DataAuditValue) SetAfter(v string) {
	x.xxx_hidden_After = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *DataAuditValue) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DataAuditValue) HasDescription() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *DataAuditValue) HasBefore() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *DataAuditValue) HasAfter() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *DataAuditValue) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

func (x *DataAuditValue) ClearDescription() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Description = nil
}

func (x *DataAuditValue) ClearBefore() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Before = nil
}

func (x *DataAuditValue) ClearAfter() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_After = nil
}

type DataAuditValue_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name        *string
	Description *string
	Before      *string
	After       *string
}

func (b0 DataAuditValue_builder) Build() *DataAuditValue {
	m0 := &DataAuditValue{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Name = b.Name
	}
	if b.Description != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Description = b.Description
	}
	if b.Before != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Before = b.Before
	}
	if b.After != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_After = b.After
	}
	return m0
}

type DataAudit struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id               *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Source           *string                `protobuf:"bytes,2,opt,name=source"`
	xxx_hidden_EventDate        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=event_date,json=eventDate"`
	xxx_hidden_Event            *string                `protobuf:"bytes,4,opt,name=event"`
	xxx_hidden_Status           *string                `protobuf:"bytes,5,opt,name=status"`
	xxx_hidden_RequestId        *string                `protobuf:"bytes,6,opt,name=request_id,json=requestId"`
	xxx_hidden_TraceId          *string                `protobuf:"bytes,7,opt,name=trace_id,json=traceId"`
	xxx_hidden_Username         *string                `protobuf:"bytes,8,opt,name=username"`
	xxx_hidden_InternalTypeName *string                `protobuf:"bytes,9,opt,name=internal_type_name,json=internalTypeName"`
	xxx_hidden_TypeName         *string                `protobuf:"bytes,10,opt,name=type_name,json=typeName"`
	xxx_hidden_TypeDescription  *string                `protobuf:"bytes,11,opt,name=type_description,json=typeDescription"`
	xxx_hidden_InstanceId       *string                `protobuf:"bytes,12,opt,name=instance_id,json=instanceId"`
	xxx_hidden_InstanceName     *string                `protobuf:"bytes,13,opt,name=instance_name,json=instanceName"`
	xxx_hidden_Values           *[]*DataAuditValue     `protobuf:"bytes,14,rep,name=values"`
	xxx_hidden_CreateAt         *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=create_at,json=createAt"`
	xxx_hidden_UpdateAt         *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=update_at,json=updateAt"`
	XXX_raceDetectHookData      protoimpl.RaceDetectHookData
	XXX_presence                [1]uint32
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *DataAudit) Reset() {
	*x = DataAudit{}
	mi := &file_tiny_audit_service_v1_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataAudit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataAudit) ProtoMessage() {}

func (x *DataAudit) ProtoReflect() protoreflect.Message {
	mi := &file_tiny_audit_service_v1_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DataAudit) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *DataAudit) GetSource() string {
	if x != nil {
		if x.xxx_hidden_Source != nil {
			return *x.xxx_hidden_Source
		}
		return ""
	}
	return ""
}

func (x *DataAudit) GetEventDate() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_EventDate
	}
	return nil
}

func (x *DataAudit) GetEvent() string {
	if x != nil {
		if x.xxx_hidden_Event != nil {
			return *x.xxx_hidden_Event
		}
		return ""
	}
	return ""
}

func (x *DataAudit) GetStatus() string {
	if x != nil {
		if x.xxx_hidden_Status != nil {
			return *x.xxx_hidden_Status
		}
		return ""
	}
	return ""
}

func (x *DataAudit) GetRequestId() string {
	if x != nil {
		if x.xxx_hidden_RequestId != nil {
			return *x.xxx_hidden_RequestId
		}
		return ""
	}
	return ""
}

func (x *DataAudit) GetTraceId() string {
	if x != nil {
		if x.xxx_hidden_TraceId != nil {
			return *x.xxx_hidden_TraceId
		}
		return ""
	}
	return ""
}

func (x *DataAudit) GetUsername() string {
	if x != nil {
		if x.xxx_hidden_Username != nil {
			return *x.xxx_hidden_Username
		}
		return ""
	}
	return ""
}

func (x *DataAudit) GetInternalTypeName() string {
	if x != nil {
		if x.xxx_hidden_InternalTypeName != nil {
			return *x.xxx_hidden_InternalTypeName
		}
		return ""
	}
	return ""
}

func (x *DataAudit) GetTypeName() string {
	if x != nil {
		if x.xxx_hidden_TypeName != nil {
			return *x.xxx_hidden_TypeName
		}
		return ""
	}
	return ""
}

func (x *DataAudit) GetTypeDescription() string {
	if x != nil {
		if x.xxx_hidden_TypeDescription != nil {
			return *x.xxx_hidden_TypeDescription
		}
		return ""
	}
	return ""
}

func (x *DataAudit) GetInstanceId() string {
	if x != nil {
		if x.xxx_hidden_InstanceId != nil {
			return *x.xxx_hidden_InstanceId
		}
		return ""
	}
	return ""
}

func (x *DataAudit) GetInstanceName() string {
	if x != nil {
		if x.xxx_hidden_InstanceName != nil {
			return *x.xxx_hidden_InstanceName
		}
		return ""
	}
	return ""
}

func (x *DataAudit) GetValues() []*DataAuditValue {
	if x != nil {
		if x.xxx_hidden_Values != nil {
			return *x.xxx_hidden_Values
		}
	}
	return nil
}

func (x *DataAudit) GetCreateAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreateAt
	}
	return nil
}

func (x *DataAudit) GetUpdateAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_UpdateAt
	}
	return nil
}

func (x *DataAudit) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 16)
}

func (x *DataAudit) SetSource(v string) {
	x.xxx_hidden_Source = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 16)
}

func (x *DataAudit) SetEventDate(v *timestamppb.Timestamp) {
	x.xxx_hidden_EventDate = v
}

func (x *DataAudit) SetEvent(v string) {
	x.xxx_hidden_Event = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 16)
}

func (x *DataAudit) SetStatus(v string) {
	x.xxx_hidden_Status = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 16)
}

func (x *DataAudit) SetRequestId(v string) {
	x.xxx_hidden_RequestId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 16)
}

func (x *DataAudit) SetTraceId(v string) {
	x.xxx_hidden_TraceId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 16)
}

func (x *DataAudit) SetUsername(v string) {
	x.xxx_hidden_Username = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 16)
}

func (x *DataAudit) SetInternalTypeName(v string) {
	x.xxx_hidden_InternalTypeName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 16)
}

func (x *DataAudit) SetTypeName(v string) {
	x.xxx_hidden_TypeName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 9, 16)
}

func (x *DataAudit) SetTypeDescription(v string) {
	x.xxx_hidden_TypeDescription = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 10, 16)
}

func (x *DataAudit) SetInstanceId(v string) {
	x.xxx_hidden_InstanceId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 11, 16)
}

func (x *DataAudit) SetInstanceName(v string) {
	x.xxx_hidden_InstanceName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 12, 16)
}

func (x *DataAudit) SetValues(v []*DataAuditValue) {
	x.xxx_hidden_Values = &v
}

func (x *DataAudit) SetCreateAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreateAt = v
}

func (x *DataAudit) SetUpdateAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_UpdateAt = v
}

func (x *DataAudit) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DataAudit) HasSource() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *DataAudit) HasEventDate() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_EventDate != nil
}

func (x *DataAudit) HasEvent() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *DataAudit) HasStatus() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *DataAudit) HasRequestId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *DataAudit) HasTraceId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *DataAudit) HasUsername() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *DataAudit) HasInternalTypeName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *DataAudit) HasTypeName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 9)
}

func (x *DataAudit) HasTypeDescription() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 10)
}

func (x *DataAudit) HasInstanceId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 11)
}

func (x *DataAudit) HasInstanceName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 12)
}

func (x *DataAudit) HasCreateAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreateAt != nil
}

func (x *DataAudit) HasUpdateAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_UpdateAt != nil
}

func (x *DataAudit) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *DataAudit) ClearSource() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Source = nil
}

func (x *DataAudit) ClearEventDate() {
	x.xxx_hidden_EventDate = nil
}

func (x *DataAudit) ClearEvent() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Event = nil
}

func (x *DataAudit) ClearStatus() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Status = nil
}

func (x *DataAudit) ClearRequestId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_RequestId = nil
}

func (x *DataAudit) ClearTraceId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_TraceId = nil
}

func (x *DataAudit) ClearUsername() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_Username = nil
}

func (x *DataAudit) ClearInternalTypeName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_InternalTypeName = nil
}

func (x *DataAudit) ClearTypeName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 9)
	x.xxx_hidden_TypeName = nil
}

func (x *DataAudit) ClearTypeDescription() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 10)
	x.xxx_hidden_TypeDescription = nil
}

func (x *DataAudit) ClearInstanceId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 11)
	x.xxx_hidden_InstanceId = nil
}

func (x *DataAudit) ClearInstanceName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 12)
	x.xxx_hidden_InstanceName = nil
}

func (x *DataAudit) ClearCreateAt() {
	x.xxx_hidden_CreateAt = nil
}

func (x *DataAudit) ClearUpdateAt() {
	x.xxx_hidden_UpdateAt = nil
}

type DataAudit_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id               *string
	Source           *string
	EventDate        *timestamppb.Timestamp
	Event            *string
	Status           *string
	RequestId        *string
	TraceId          *string
	Username         *string
	InternalTypeName *string
	TypeName         *string
	TypeDescription  *string
	InstanceId       *string
	InstanceName     *string
	Values           []*DataAuditValue
	CreateAt         *timestamppb.Timestamp
	UpdateAt         *timestamppb.Timestamp
}

func (b0 DataAudit_builder) Build() *DataAudit {
	m0 := &DataAudit{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 16)
		x.xxx_hidden_Id = b.Id
	}
	if b.Source != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 16)
		x.xxx_hidden_Source = b.Source
	}
	x.xxx_hidden_EventDate = b.EventDate
	if b.Event != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 16)
		x.xxx_hidden_Event = b.Event
	}
	if b.Status != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 16)
		x.xxx_hidden_Status = b.Status
	}
	if b.RequestId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 16)
		x.xxx_hidden_RequestId = b.RequestId
	}
	if b.TraceId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 16)
		x.xxx_hidden_TraceId = b.TraceId
	}
	if b.Username != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 16)
		x.xxx_hidden_Username = b.Username
	}
	if b.InternalTypeName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 16)
		x.xxx_hidden_InternalTypeName = b.InternalTypeName
	}
	if b.TypeName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 9, 16)
		x.xxx_hidden_TypeName = b.TypeName
	}
	if b.TypeDescription != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 10, 16)
		x.xxx_hidden_TypeDescription = b.TypeDescription
	}
	if b.InstanceId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 11, 16)
		x.xxx_hidden_InstanceId = b.InstanceId
	}
	if b.InstanceName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 12, 16)
		x.xxx_hidden_InstanceName = b.InstanceName
	}
	x.xxx_hidden_Values = &b.Values
	x.xxx_hidden_CreateAt = b.CreateAt
	x.xxx_hidden_UpdateAt = b.UpdateAt
	return m0
}

var File_tiny_audit_service_v1_messages_proto protoreflect.FileDescriptor

const file_tiny_audit_service_v1_messages_proto_rawDesc = "" +
	"\n" +
	"$tiny-audit-service/v1/messages.proto\x12\raudit.service\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa3\x01\n" +
	"\x13ListByPeriodRequest\x12.\n" +
	"\x04from\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12.\n" +
	"\x04till\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04till\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\rR\x06offset\"\xac\x03\n" +
	"\tAuthAudit\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x129\n" +
	"\n" +
	"event_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\teventDate\x12\x14\n" +
	"\x05event\x18\x04 \x01(\tR\x05event\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"request_id\x18\x06 \x01(\tR\trequestId\x12\x19\n" +
	"\btrace_id\x18\a \x01(\tR\atraceId\x12\x1a\n" +
	"\busername\x18\b \x01(\tR\busername\x12!\n" +
	"\faccess_token\x18\t \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\n" +
	" \x01(\tR\frefreshToken\x127\n" +
	"\tcreate_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\bcreateAt\x127\n" +
	"\tupdate_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\bupdateAt\"t\n" +
	"\x0eDataAuditValue\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x16\n" +
	"\x06before\x18\x03 \x01(\tR\x06before\x12\x14\n" +
	"\x05after\x18\x04 \x01(\tR\x05after\"\xd7\x04\n" +
	"\tDataAudit\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x129\n" +
	"\n" +
	"event_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\teventDate\x12\x14\n" +
	"\x05event\x18\x04 \x01(\tR\x05event\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"request_id\x18\x06 \x01(\tR\trequestId\x12\x19\n" +
	"\btrace_id\x18\a \x01(\tR\atraceId\x12\x1a\n" +
	"\busername\x18\b \x01(\tR\busername\x12,\n" +
	"\x12internal_type_name\x18\t \x01(\tR\x10internalTypeName\x12\x1b\n" +
	"\ttype_name\x18\n" +
	" \x01(\tR\btypeName\x12)\n" +
	"\x10type_description\x18\v \x01(\tR\x0ftypeDescription\x12\x1f\n" +
	"\vinstance_id\x18\f \x01(\tR\n" +
	"instanceId\x12#\n" +
	"\rinstance_name\x18\r \x01(\tR\finstanceName\x125\n" +
	"\x06values\x18\x0e \x03(\v2\x1d.audit.service.DataAuditValueR\x06values\x127\n" +
	"\tcreate_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\bcreateAt\x127\n" +
	"\tupdate_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\bupdateAtB,Z*tiny-audit-service/grpc/tiny-audit-serviceb\beditionsp\xe8\a"

var file_tiny_audit_service_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_tiny_audit_service_v1_messages_proto_goTypes = []any{
	(*ListByPeriodRequest)(nil),   // 0: audit.service.ListByPeriodRequest
	(*AuthAudit)(nil),             // 1: audit.service.AuthAudit
	(*DataAuditValue)(nil),        // 2: audit.service.DataAuditValue
	(*DataAudit)(nil),             // 3: audit.service.DataAudit
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_tiny_audit_service_v1_messages_proto_depIdxs = []int32{
	4, // 0: audit.service.ListByPeriodRequest.from:type_name -> google.protobuf.Timestamp
	4, // 1: audit.service.ListByPeriodRequest.till:type_name -> google.protobuf.Timestamp
	4, // 2: audit.service.AuthAudit.event_date:type_name -> google.protobuf.Timestamp
	4, // 3: audit.service.AuthAudit.create_at:type_name -> google.protobuf.Timestamp
	4, // 4: audit.service.AuthAudit.update_at:type_name -> google.protobuf.Timestamp
	4, // 5: audit.service.DataAudit.event_date:type_name -> google.protobuf.Timestamp
	2, // 6: audit.service.DataAudit.values:type_name -> audit.service.DataAuditValue
	4, // 7: audit.service.DataAudit.create_at:type_name -> google.protobuf.Timestamp
	4, // 8: audit.service.DataAudit.update_at:type_name -> google.protobuf.Timestamp
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_tiny_audit_service_v1_messages_proto_init() }
func file_tiny_audit_service_v1_messages_proto_init() {
	if File_tiny_audit_service_v1_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tiny_audit_service_v1_messages_proto_rawDesc), len(file_tiny_audit_service_v1_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tiny_audit_service_v1_messages_proto_goTypes,
		DependencyIndexes: file_tiny_audit_service_v1_messages_proto_depIdxs,
		MessageInfos:      file_tiny_audit_service_v1_messages_proto_msgTypes,
	}.Build()
	File_tiny_audit_service_v1_messages_proto = out.File
	file_tiny_audit_service_v1_messages_proto_goTypes = nil
	file_tiny_audit_service_v1_messages_proto_depIdxs = nil
}
