// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTailCutUseCase creates a new instance of MockTailCutUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTailCutUseCase[ID comparable](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTailCutUseCase[ID] {
	mock := &MockTailCutUseCase[ID]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTailCutUseCase is an autogenerated mock type for the TailCutUseCase type
type MockTailCutUseCase[ID comparable] struct {
	mock.Mock
}

type MockTailCutUseCase_Expecter[ID comparable] struct {
	mock *mock.Mock
}

func (_m *MockTailCutUseCase[ID]) EXPECT() *MockTailCutUseCase_Expecter[ID] {
	return &MockTailCutUseCase_Expecter[ID]{mock: &_m.Mock}
}

// Cut provides a mock function for the type MockTailCutUseCase
func (_mock *MockTailCutUseCase[ID]) Cut(ctx context.Context, id ID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Cut")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTailCutUseCase_Cut_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cut'
type MockTailCutUseCase_Cut_Call[ID comparable] struct {
	*mock.Call
}

// Cut is a helper method to define mock.On call
//   - ctx context.Context
//   - id ID
func (_e *MockTailCutUseCase_Expecter[ID]) Cut(ctx interface{}, id interface{}) *MockTailCutUseCase_Cut_Call[ID] {
	return &MockTailCutUseCase_Cut_Call[ID]{Call: _e.mock.On("Cut", ctx, id)}
}

func (_c *MockTailCutUseCase_Cut_Call[ID]) Run(run func(ctx context.Context, id ID)) *MockTailCutUseCase_Cut_Call[ID] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ID
		if args[1] != nil {
			arg1 = args[1].(ID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTailCutUseCase_Cut_Call[ID]) Return(err error) *MockTailCutUseCase_Cut_Call[ID] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTailCutUseCase_Cut_Call[ID]) RunAndReturn(run func(ctx context.Context, id ID) error) *MockTailCutUseCase_Cut_Call[ID] {
	_c.Call.Return(run)
	return _c
}
