// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ElfAstAhe/tiny-audit-service/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthListByUsernameUseCase creates a new instance of MockAuthListByUsernameUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthListByUsernameUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthListByUsernameUseCase {
	mock := &MockAuthListByUsernameUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthListByUsernameUseCase is an autogenerated mock type for the AuthListByUsernameUseCase type
type MockAuthListByUsernameUseCase struct {
	mock.Mock
}

type MockAuthListByUsernameUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthListByUsernameUseCase) EXPECT() *MockAuthListByUsernameUseCase_Expecter {
	return &MockAuthListByUsernameUseCase_Expecter{mock: &_m.Mock}
}

// List provides a mock function for the type MockAuthListByUsernameUseCase
func (_mock *MockAuthListByUsernameUseCase) List(ctx context.Context, username string, limit int, offset int) ([]*domain.AuthAudit, error) {
	ret := _mock.Called(ctx, username, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.AuthAudit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) ([]*domain.AuthAudit, error)); ok {
		return returnFunc(ctx, username, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) []*domain.AuthAudit); ok {
		r0 = returnFunc(ctx, username, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.AuthAudit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = returnFunc(ctx, username, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthListByUsernameUseCase_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockAuthListByUsernameUseCase_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - limit int
//   - offset int
func (_e *MockAuthListByUsernameUseCase_Expecter) List(ctx interface{}, username interface{}, limit interface{}, offset interface{}) *MockAuthListByUsernameUseCase_List_Call {
	return &MockAuthListByUsernameUseCase_List_Call{Call: _e.mock.On("List", ctx, username, limit, offset)}
}

func (_c *MockAuthListByUsernameUseCase_List_Call) Run(run func(ctx context.Context, username string, limit int, offset int)) *MockAuthListByUsernameUseCase_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAuthListByUsernameUseCase_List_Call) Return(authAudits []*domain.AuthAudit, err error) *MockAuthListByUsernameUseCase_List_Call {
	_c.Call.Return(authAudits, err)
	return _c
}

func (_c *MockAuthListByUsernameUseCase_List_Call) RunAndReturn(run func(ctx context.Context, username string, limit int, offset int) ([]*domain.AuthAudit, error)) *MockAuthListByUsernameUseCase_List_Call {
	_c.Call.Return(run)
	return _c
}
