// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ElfAstAhe/tiny-audit-service/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthAuditUseCase creates a new instance of MockAuthAuditUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthAuditUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthAuditUseCase {
	mock := &MockAuthAuditUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthAuditUseCase is an autogenerated mock type for the AuthAuditUseCase type
type MockAuthAuditUseCase struct {
	mock.Mock
}

type MockAuthAuditUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthAuditUseCase) EXPECT() *MockAuthAuditUseCase_Expecter {
	return &MockAuthAuditUseCase_Expecter{mock: &_m.Mock}
}

// Audit provides a mock function for the type MockAuthAuditUseCase
func (_mock *MockAuthAuditUseCase) Audit(ctx context.Context, data *domain.AuthAudit) error {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Audit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuthAudit) error); ok {
		r0 = returnFunc(ctx, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthAuditUseCase_Audit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Audit'
type MockAuthAuditUseCase_Audit_Call struct {
	*mock.Call
}

// Audit is a helper method to define mock.On call
//   - ctx context.Context
//   - data *domain.AuthAudit
func (_e *MockAuthAuditUseCase_Expecter) Audit(ctx interface{}, data interface{}) *MockAuthAuditUseCase_Audit_Call {
	return &MockAuthAuditUseCase_Audit_Call{Call: _e.mock.On("Audit", ctx, data)}
}

func (_c *MockAuthAuditUseCase_Audit_Call) Run(run func(ctx context.Context, data *domain.AuthAudit)) *MockAuthAuditUseCase_Audit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.AuthAudit
		if args[1] != nil {
			arg1 = args[1].(*domain.AuthAudit)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthAuditUseCase_Audit_Call) Return(err error) *MockAuthAuditUseCase_Audit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthAuditUseCase_Audit_Call) RunAndReturn(run func(ctx context.Context, data *domain.AuthAudit) error) *MockAuthAuditUseCase_Audit_Call {
	_c.Call.Return(run)
	return _c
}
