// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ElfAstAhe/tiny-audit-service/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDataAuditUseCase creates a new instance of MockDataAuditUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDataAuditUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDataAuditUseCase {
	mock := &MockDataAuditUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDataAuditUseCase is an autogenerated mock type for the DataAuditUseCase type
type MockDataAuditUseCase struct {
	mock.Mock
}

type MockDataAuditUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDataAuditUseCase) EXPECT() *MockDataAuditUseCase_Expecter {
	return &MockDataAuditUseCase_Expecter{mock: &_m.Mock}
}

// Audit provides a mock function for the type MockDataAuditUseCase
func (_mock *MockDataAuditUseCase) Audit(ctx context.Context, data *domain.DataAudit) error {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Audit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.DataAudit) error); ok {
		r0 = returnFunc(ctx, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDataAuditUseCase_Audit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Audit'
type MockDataAuditUseCase_Audit_Call struct {
	*mock.Call
}

// Audit is a helper method to define mock.On call
//   - ctx context.Context
//   - data *domain.DataAudit
func (_e *MockDataAuditUseCase_Expecter) Audit(ctx interface{}, data interface{}) *MockDataAuditUseCase_Audit_Call {
	return &MockDataAuditUseCase_Audit_Call{Call: _e.mock.On("Audit", ctx, data)}
}

func (_c *MockDataAuditUseCase_Audit_Call) Run(run func(ctx context.Context, data *domain.DataAudit)) *MockDataAuditUseCase_Audit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.DataAudit
		if args[1] != nil {
			arg1 = args[1].(*domain.DataAudit)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDataAuditUseCase_Audit_Call) Return(err error) *MockDataAuditUseCase_Audit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDataAuditUseCase_Audit_Call) RunAndReturn(run func(ctx context.Context, data *domain.DataAudit) error) *MockDataAuditUseCase_Audit_Call {
	_c.Call.Return(run)
	return _c
}
