// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTailGetUseCase creates a new instance of MockTailGetUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTailGetUseCase[ID comparable](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTailGetUseCase[ID] {
	mock := &MockTailGetUseCase[ID]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTailGetUseCase is an autogenerated mock type for the TailGetUseCase type
type MockTailGetUseCase[ID comparable] struct {
	mock.Mock
}

type MockTailGetUseCase_Expecter[ID comparable] struct {
	mock *mock.Mock
}

func (_m *MockTailGetUseCase[ID]) EXPECT() *MockTailGetUseCase_Expecter[ID] {
	return &MockTailGetUseCase_Expecter[ID]{mock: &_m.Mock}
}

// GetTail provides a mock function for the type MockTailGetUseCase
func (_mock *MockTailGetUseCase[ID]) GetTail(ctx context.Context, tail time.Time) ([]ID, error) {
	ret := _mock.Called(ctx, tail)

	if len(ret) == 0 {
		panic("no return value specified for GetTail")
	}

	var r0 []ID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) ([]ID, error)); ok {
		return returnFunc(ctx, tail)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) []ID); ok {
		r0 = returnFunc(ctx, tail)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = returnFunc(ctx, tail)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTailGetUseCase_GetTail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTail'
type MockTailGetUseCase_GetTail_Call[ID comparable] struct {
	*mock.Call
}

// GetTail is a helper method to define mock.On call
//   - ctx context.Context
//   - tail time.Time
func (_e *MockTailGetUseCase_Expecter[ID]) GetTail(ctx interface{}, tail interface{}) *MockTailGetUseCase_GetTail_Call[ID] {
	return &MockTailGetUseCase_GetTail_Call[ID]{Call: _e.mock.On("GetTail", ctx, tail)}
}

func (_c *MockTailGetUseCase_GetTail_Call[ID]) Run(run func(ctx context.Context, tail time.Time)) *MockTailGetUseCase_GetTail_Call[ID] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTailGetUseCase_GetTail_Call[ID]) Return(vs []ID, err error) *MockTailGetUseCase_GetTail_Call[ID] {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockTailGetUseCase_GetTail_Call[ID]) RunAndReturn(run func(ctx context.Context, tail time.Time) ([]ID, error)) *MockTailGetUseCase_GetTail_Call[ID] {
	_c.Call.Return(run)
	return _c
}
