// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/ElfAstAhe/tiny-audit-service/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthListByPeriodUseCase creates a new instance of MockAuthListByPeriodUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthListByPeriodUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthListByPeriodUseCase {
	mock := &MockAuthListByPeriodUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthListByPeriodUseCase is an autogenerated mock type for the AuthListByPeriodUseCase type
type MockAuthListByPeriodUseCase struct {
	mock.Mock
}

type MockAuthListByPeriodUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthListByPeriodUseCase) EXPECT() *MockAuthListByPeriodUseCase_Expecter {
	return &MockAuthListByPeriodUseCase_Expecter{mock: &_m.Mock}
}

// List provides a mock function for the type MockAuthListByPeriodUseCase
func (_mock *MockAuthListByPeriodUseCase) List(ctx context.Context, from time.Time, till time.Time, limit int, offset int) ([]*domain.AuthAudit, error) {
	ret := _mock.Called(ctx, from, till, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.AuthAudit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, time.Time, int, int) ([]*domain.AuthAudit, error)); ok {
		return returnFunc(ctx, from, till, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, time.Time, int, int) []*domain.AuthAudit); ok {
		r0 = returnFunc(ctx, from, till, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.AuthAudit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time, time.Time, int, int) error); ok {
		r1 = returnFunc(ctx, from, till, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthListByPeriodUseCase_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockAuthListByPeriodUseCase_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - from time.Time
//   - till time.Time
//   - limit int
//   - offset int
func (_e *MockAuthListByPeriodUseCase_Expecter) List(ctx interface{}, from interface{}, till interface{}, limit interface{}, offset interface{}) *MockAuthListByPeriodUseCase_List_Call {
	return &MockAuthListByPeriodUseCase_List_Call{Call: _e.mock.On("List", ctx, from, till, limit, offset)}
}

func (_c *MockAuthListByPeriodUseCase_List_Call) Run(run func(ctx context.Context, from time.Time, till time.Time, limit int, offset int)) *MockAuthListByPeriodUseCase_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockAuthListByPeriodUseCase_List_Call) Return(authAudits []*domain.AuthAudit, err error) *MockAuthListByPeriodUseCase_List_Call {
	_c.Call.Return(authAudits, err)
	return _c
}

func (_c *MockAuthListByPeriodUseCase_List_Call) RunAndReturn(run func(ctx context.Context, from time.Time, till time.Time, limit int, offset int) ([]*domain.AuthAudit, error)) *MockAuthListByPeriodUseCase_List_Call {
	_c.Call.Return(run)
	return _c
}
