// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ElfAstAhe/tiny-audit-service/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDataListByInstanceUseCase creates a new instance of MockDataListByInstanceUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDataListByInstanceUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDataListByInstanceUseCase {
	mock := &MockDataListByInstanceUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDataListByInstanceUseCase is an autogenerated mock type for the DataListByInstanceUseCase type
type MockDataListByInstanceUseCase struct {
	mock.Mock
}

type MockDataListByInstanceUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDataListByInstanceUseCase) EXPECT() *MockDataListByInstanceUseCase_Expecter {
	return &MockDataListByInstanceUseCase_Expecter{mock: &_m.Mock}
}

// List provides a mock function for the type MockDataListByInstanceUseCase
func (_mock *MockDataListByInstanceUseCase) List(ctx context.Context, typeName string, instanceID string, limit int, offset int) ([]*domain.DataAudit, error) {
	ret := _mock.Called(ctx, typeName, instanceID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.DataAudit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int, int) ([]*domain.DataAudit, error)); ok {
		return returnFunc(ctx, typeName, instanceID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int, int) []*domain.DataAudit); ok {
		r0 = returnFunc(ctx, typeName, instanceID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.DataAudit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, int, int) error); ok {
		r1 = returnFunc(ctx, typeName, instanceID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDataListByInstanceUseCase_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockDataListByInstanceUseCase_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - typeName string
//   - instanceID string
//   - limit int
//   - offset int
func (_e *MockDataListByInstanceUseCase_Expecter) List(ctx interface{}, typeName interface{}, instanceID interface{}, limit interface{}, offset interface{}) *MockDataListByInstanceUseCase_List_Call {
	return &MockDataListByInstanceUseCase_List_Call{Call: _e.mock.On("List", ctx, typeName, instanceID, limit, offset)}
}

func (_c *MockDataListByInstanceUseCase_List_Call) Run(run func(ctx context.Context, typeName string, instanceID string, limit int, offset int)) *MockDataListByInstanceUseCase_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockDataListByInstanceUseCase_List_Call) Return(dataAudits []*domain.DataAudit, err error) *MockDataListByInstanceUseCase_List_Call {
	_c.Call.Return(dataAudits, err)
	return _c
}

func (_c *MockDataListByInstanceUseCase_List_Call) RunAndReturn(run func(ctx context.Context, typeName string, instanceID string, limit int, offset int) ([]*domain.DataAudit, error)) *MockDataListByInstanceUseCase_List_Call {
	_c.Call.Return(run)
	return _c
}
