// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAuditClient creates a new instance of MockAuditClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuditClient[A any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuditClient[A] {
	mock := &MockAuditClient[A]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuditClient is an autogenerated mock type for the AuditClient type
type MockAuditClient[A any] struct {
	mock.Mock
}

type MockAuditClient_Expecter[A any] struct {
	mock *mock.Mock
}

func (_m *MockAuditClient[A]) EXPECT() *MockAuditClient_Expecter[A] {
	return &MockAuditClient_Expecter[A]{mock: &_m.Mock}
}

// Audit provides a mock function for the type MockAuditClient
func (_mock *MockAuditClient[A]) Audit(data A) error {
	ret := _mock.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for Audit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(A) error); ok {
		r0 = returnFunc(data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuditClient_Audit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Audit'
type MockAuditClient_Audit_Call[A any] struct {
	*mock.Call
}

// Audit is a helper method to define mock.On call
//   - data A
func (_e *MockAuditClient_Expecter[A]) Audit(data interface{}) *MockAuditClient_Audit_Call[A] {
	return &MockAuditClient_Audit_Call[A]{Call: _e.mock.On("Audit", data)}
}

func (_c *MockAuditClient_Audit_Call[A]) Run(run func(data A)) *MockAuditClient_Audit_Call[A] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 A
		if args[0] != nil {
			arg0 = args[0].(A)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuditClient_Audit_Call[A]) Return(err error) *MockAuditClient_Audit_Call[A] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuditClient_Audit_Call[A]) RunAndReturn(run func(data A) error) *MockAuditClient_Audit_Call[A] {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type MockAuditClient
func (_mock *MockAuditClient[A]) Start(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuditClient_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockAuditClient_Start_Call[A any] struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAuditClient_Expecter[A]) Start(ctx interface{}) *MockAuditClient_Start_Call[A] {
	return &MockAuditClient_Start_Call[A]{Call: _e.mock.On("Start", ctx)}
}

func (_c *MockAuditClient_Start_Call[A]) Run(run func(ctx context.Context)) *MockAuditClient_Start_Call[A] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuditClient_Start_Call[A]) Return(err error) *MockAuditClient_Start_Call[A] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuditClient_Start_Call[A]) RunAndReturn(run func(ctx context.Context) error) *MockAuditClient_Start_Call[A] {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type MockAuditClient
func (_mock *MockAuditClient[A]) Stop(stopTimeout time.Duration) error {
	ret := _mock.Called(stopTimeout)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(time.Duration) error); ok {
		r0 = returnFunc(stopTimeout)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuditClient_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockAuditClient_Stop_Call[A any] struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - stopTimeout time.Duration
func (_e *MockAuditClient_Expecter[A]) Stop(stopTimeout interface{}) *MockAuditClient_Stop_Call[A] {
	return &MockAuditClient_Stop_Call[A]{Call: _e.mock.On("Stop", stopTimeout)}
}

func (_c *MockAuditClient_Stop_Call[A]) Run(run func(stopTimeout time.Duration)) *MockAuditClient_Stop_Call[A] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Duration
		if args[0] != nil {
			arg0 = args[0].(time.Duration)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuditClient_Stop_Call[A]) Return(err error) *MockAuditClient_Stop_Call[A] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuditClient_Stop_Call[A]) RunAndReturn(run func(stopTimeout time.Duration) error) *MockAuditClient_Stop_Call[A] {
	_c.Call.Return(run)
	return _c
}

// TotalLost provides a mock function for the type MockAuditClient
func (_mock *MockAuditClient[A]) TotalLost() int32 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for TotalLost")
	}

	var r0 int32
	if returnFunc, ok := ret.Get(0).(func() int32); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int32)
	}
	return r0
}

// MockAuditClient_TotalLost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TotalLost'
type MockAuditClient_TotalLost_Call[A any] struct {
	*mock.Call
}

// TotalLost is a helper method to define mock.On call
func (_e *MockAuditClient_Expecter[A]) TotalLost() *MockAuditClient_TotalLost_Call[A] {
	return &MockAuditClient_TotalLost_Call[A]{Call: _e.mock.On("TotalLost")}
}

func (_c *MockAuditClient_TotalLost_Call[A]) Run(run func()) *MockAuditClient_TotalLost_Call[A] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAuditClient_TotalLost_Call[A]) Return(n int32) *MockAuditClient_TotalLost_Call[A] {
	_c.Call.Return(n)
	return _c
}

func (_c *MockAuditClient_TotalLost_Call[A]) RunAndReturn(run func() int32) *MockAuditClient_TotalLost_Call[A] {
	_c.Call.Return(run)
	return _c
}
