// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/ElfAstAhe/tiny-audit-service/pkg/client/dto"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthAuditClient creates a new instance of MockAuthAuditClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthAuditClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthAuditClient {
	mock := &MockAuthAuditClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthAuditClient is an autogenerated mock type for the AuthAuditClient type
type MockAuthAuditClient struct {
	mock.Mock
}

type MockAuthAuditClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthAuditClient) EXPECT() *MockAuthAuditClient_Expecter {
	return &MockAuthAuditClient_Expecter{mock: &_m.Mock}
}

// Audit provides a mock function for the type MockAuthAuditClient
func (_mock *MockAuthAuditClient) Audit(data *dto.AuthAuditDTO) error {
	ret := _mock.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for Audit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*dto.AuthAuditDTO) error); ok {
		r0 = returnFunc(data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthAuditClient_Audit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Audit'
type MockAuthAuditClient_Audit_Call struct {
	*mock.Call
}

// Audit is a helper method to define mock.On call
//   - data *dto.AuthAuditDTO
func (_e *MockAuthAuditClient_Expecter) Audit(data interface{}) *MockAuthAuditClient_Audit_Call {
	return &MockAuthAuditClient_Audit_Call{Call: _e.mock.On("Audit", data)}
}

func (_c *MockAuthAuditClient_Audit_Call) Run(run func(data *dto.AuthAuditDTO)) *MockAuthAuditClient_Audit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *dto.AuthAuditDTO
		if args[0] != nil {
			arg0 = args[0].(*dto.AuthAuditDTO)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthAuditClient_Audit_Call) Return(err error) *MockAuthAuditClient_Audit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthAuditClient_Audit_Call) RunAndReturn(run func(data *dto.AuthAuditDTO) error) *MockAuthAuditClient_Audit_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type MockAuthAuditClient
func (_mock *MockAuthAuditClient) Start(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthAuditClient_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockAuthAuditClient_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAuthAuditClient_Expecter) Start(ctx interface{}) *MockAuthAuditClient_Start_Call {
	return &MockAuthAuditClient_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *MockAuthAuditClient_Start_Call) Run(run func(ctx context.Context)) *MockAuthAuditClient_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthAuditClient_Start_Call) Return(err error) *MockAuthAuditClient_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthAuditClient_Start_Call) RunAndReturn(run func(ctx context.Context) error) *MockAuthAuditClient_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type MockAuthAuditClient
func (_mock *MockAuthAuditClient) Stop(stopTimeout time.Duration) error {
	ret := _mock.Called(stopTimeout)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(time.Duration) error); ok {
		r0 = returnFunc(stopTimeout)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthAuditClient_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockAuthAuditClient_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - stopTimeout time.Duration
func (_e *MockAuthAuditClient_Expecter) Stop(stopTimeout interface{}) *MockAuthAuditClient_Stop_Call {
	return &MockAuthAuditClient_Stop_Call{Call: _e.mock.On("Stop", stopTimeout)}
}

func (_c *MockAuthAuditClient_Stop_Call) Run(run func(stopTimeout time.Duration)) *MockAuthAuditClient_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Duration
		if args[0] != nil {
			arg0 = args[0].(time.Duration)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthAuditClient_Stop_Call) Return(err error) *MockAuthAuditClient_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthAuditClient_Stop_Call) RunAndReturn(run func(stopTimeout time.Duration) error) *MockAuthAuditClient_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// TotalLost provides a mock function for the type MockAuthAuditClient
func (_mock *MockAuthAuditClient) TotalLost() int32 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for TotalLost")
	}

	var r0 int32
	if returnFunc, ok := ret.Get(0).(func() int32); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int32)
	}
	return r0
}

// MockAuthAuditClient_TotalLost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TotalLost'
type MockAuthAuditClient_TotalLost_Call struct {
	*mock.Call
}

// TotalLost is a helper method to define mock.On call
func (_e *MockAuthAuditClient_Expecter) TotalLost() *MockAuthAuditClient_TotalLost_Call {
	return &MockAuthAuditClient_TotalLost_Call{Call: _e.mock.On("TotalLost")}
}

func (_c *MockAuthAuditClient_TotalLost_Call) Run(run func()) *MockAuthAuditClient_TotalLost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAuthAuditClient_TotalLost_Call) Return(n int32) *MockAuthAuditClient_TotalLost_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockAuthAuditClient_TotalLost_Call) RunAndReturn(run func() int32) *MockAuthAuditClient_TotalLost_Call {
	_c.Call.Return(run)
	return _c
}
