// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AuthAuditDTO auth audit d t o
//
// swagger:model AuthAuditDTO
type AuthAuditDTO struct {

	// access token
	AccessToken string `json:"access_token,omitempty"`

	// created at
	CreatedAt string `json:"created_at,omitempty"`

	// event
	Event string `json:"event,omitempty"`

	// event date
	EventDate string `json:"event_date,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// refresh token
	RefreshToken string `json:"refresh_token,omitempty"`

	// request id
	RequestID string `json:"request_id,omitempty"`

	// source
	Source string `json:"source,omitempty"`

	// status
	Status string `json:"status,omitempty"`

	// updated at
	UpdatedAt string `json:"updated_at,omitempty"`

	// username
	Username string `json:"username,omitempty"`
}

// Validate validates this auth audit d t o
func (m *AuthAuditDTO) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this auth audit d t o based on context it is used
func (m *AuthAuditDTO) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AuthAuditDTO) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AuthAuditDTO) UnmarshalBinary(b []byte) error {
	var res AuthAuditDTO
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
