// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ElfAstAhe/tiny-audit-service/internal/facade/dto"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDataAuditFacade creates a new instance of MockDataAuditFacade. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDataAuditFacade(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDataAuditFacade {
	mock := &MockDataAuditFacade{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDataAuditFacade is an autogenerated mock type for the DataAuditFacade type
type MockDataAuditFacade struct {
	mock.Mock
}

type MockDataAuditFacade_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDataAuditFacade) EXPECT() *MockDataAuditFacade_Expecter {
	return &MockDataAuditFacade_Expecter{mock: &_m.Mock}
}

// Audit provides a mock function for the type MockDataAuditFacade
func (_mock *MockDataAuditFacade) Audit(ctx context.Context, data *dto.DataAuditDTO) error {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Audit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.DataAuditDTO) error); ok {
		r0 = returnFunc(ctx, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDataAuditFacade_Audit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Audit'
type MockDataAuditFacade_Audit_Call struct {
	*mock.Call
}

// Audit is a helper method to define mock.On call
//   - ctx context.Context
//   - data *dto.DataAuditDTO
func (_e *MockDataAuditFacade_Expecter) Audit(ctx interface{}, data interface{}) *MockDataAuditFacade_Audit_Call {
	return &MockDataAuditFacade_Audit_Call{Call: _e.mock.On("Audit", ctx, data)}
}

func (_c *MockDataAuditFacade_Audit_Call) Run(run func(ctx context.Context, data *dto.DataAuditDTO)) *MockDataAuditFacade_Audit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.DataAuditDTO
		if args[1] != nil {
			arg1 = args[1].(*dto.DataAuditDTO)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDataAuditFacade_Audit_Call) Return(err error) *MockDataAuditFacade_Audit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDataAuditFacade_Audit_Call) RunAndReturn(run func(ctx context.Context, data *dto.DataAuditDTO) error) *MockDataAuditFacade_Audit_Call {
	_c.Call.Return(run)
	return _c
}

// ListByInstance provides a mock function for the type MockDataAuditFacade
func (_mock *MockDataAuditFacade) ListByInstance(ctx context.Context, auditInstance *dto.AuditInstanceDTO) ([]*dto.DataAuditDTO, error) {
	ret := _mock.Called(ctx, auditInstance)

	if len(ret) == 0 {
		panic("no return value specified for ListByInstance")
	}

	var r0 []*dto.DataAuditDTO
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.AuditInstanceDTO) ([]*dto.DataAuditDTO, error)); ok {
		return returnFunc(ctx, auditInstance)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.AuditInstanceDTO) []*dto.DataAuditDTO); ok {
		r0 = returnFunc(ctx, auditInstance)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.DataAuditDTO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.AuditInstanceDTO) error); ok {
		r1 = returnFunc(ctx, auditInstance)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDataAuditFacade_ListByInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByInstance'
type MockDataAuditFacade_ListByInstance_Call struct {
	*mock.Call
}

// ListByInstance is a helper method to define mock.On call
//   - ctx context.Context
//   - auditInstance *dto.AuditInstanceDTO
func (_e *MockDataAuditFacade_Expecter) ListByInstance(ctx interface{}, auditInstance interface{}) *MockDataAuditFacade_ListByInstance_Call {
	return &MockDataAuditFacade_ListByInstance_Call{Call: _e.mock.On("ListByInstance", ctx, auditInstance)}
}

func (_c *MockDataAuditFacade_ListByInstance_Call) Run(run func(ctx context.Context, auditInstance *dto.AuditInstanceDTO)) *MockDataAuditFacade_ListByInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.AuditInstanceDTO
		if args[1] != nil {
			arg1 = args[1].(*dto.AuditInstanceDTO)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDataAuditFacade_ListByInstance_Call) Return(dataAuditDTOs []*dto.DataAuditDTO, err error) *MockDataAuditFacade_ListByInstance_Call {
	_c.Call.Return(dataAuditDTOs, err)
	return _c
}

func (_c *MockDataAuditFacade_ListByInstance_Call) RunAndReturn(run func(ctx context.Context, auditInstance *dto.AuditInstanceDTO) ([]*dto.DataAuditDTO, error)) *MockDataAuditFacade_ListByInstance_Call {
	_c.Call.Return(run)
	return _c
}

// ListByPeriod provides a mock function for the type MockDataAuditFacade
func (_mock *MockDataAuditFacade) ListByPeriod(ctx context.Context, auditPeriod *dto.AuditPeriodDTO) ([]*dto.DataAuditDTO, error) {
	ret := _mock.Called(ctx, auditPeriod)

	if len(ret) == 0 {
		panic("no return value specified for ListByPeriod")
	}

	var r0 []*dto.DataAuditDTO
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.AuditPeriodDTO) ([]*dto.DataAuditDTO, error)); ok {
		return returnFunc(ctx, auditPeriod)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.AuditPeriodDTO) []*dto.DataAuditDTO); ok {
		r0 = returnFunc(ctx, auditPeriod)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.DataAuditDTO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.AuditPeriodDTO) error); ok {
		r1 = returnFunc(ctx, auditPeriod)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDataAuditFacade_ListByPeriod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByPeriod'
type MockDataAuditFacade_ListByPeriod_Call struct {
	*mock.Call
}

// ListByPeriod is a helper method to define mock.On call
//   - ctx context.Context
//   - auditPeriod *dto.AuditPeriodDTO
func (_e *MockDataAuditFacade_Expecter) ListByPeriod(ctx interface{}, auditPeriod interface{}) *MockDataAuditFacade_ListByPeriod_Call {
	return &MockDataAuditFacade_ListByPeriod_Call{Call: _e.mock.On("ListByPeriod", ctx, auditPeriod)}
}

func (_c *MockDataAuditFacade_ListByPeriod_Call) Run(run func(ctx context.Context, auditPeriod *dto.AuditPeriodDTO)) *MockDataAuditFacade_ListByPeriod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.AuditPeriodDTO
		if args[1] != nil {
			arg1 = args[1].(*dto.AuditPeriodDTO)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDataAuditFacade_ListByPeriod_Call) Return(dataAuditDTOs []*dto.DataAuditDTO, err error) *MockDataAuditFacade_ListByPeriod_Call {
	_c.Call.Return(dataAuditDTOs, err)
	return _c
}

func (_c *MockDataAuditFacade_ListByPeriod_Call) RunAndReturn(run func(ctx context.Context, auditPeriod *dto.AuditPeriodDTO) ([]*dto.DataAuditDTO, error)) *MockDataAuditFacade_ListByPeriod_Call {
	_c.Call.Return(run)
	return _c
}
