// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ElfAstAhe/tiny-audit-service/internal/facade/dto"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthAuditFacade creates a new instance of MockAuthAuditFacade. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthAuditFacade(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthAuditFacade {
	mock := &MockAuthAuditFacade{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthAuditFacade is an autogenerated mock type for the AuthAuditFacade type
type MockAuthAuditFacade struct {
	mock.Mock
}

type MockAuthAuditFacade_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthAuditFacade) EXPECT() *MockAuthAuditFacade_Expecter {
	return &MockAuthAuditFacade_Expecter{mock: &_m.Mock}
}

// Audit provides a mock function for the type MockAuthAuditFacade
func (_mock *MockAuthAuditFacade) Audit(ctx context.Context, data *dto.AuthAuditDTO) error {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Audit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.AuthAuditDTO) error); ok {
		r0 = returnFunc(ctx, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthAuditFacade_Audit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Audit'
type MockAuthAuditFacade_Audit_Call struct {
	*mock.Call
}

// Audit is a helper method to define mock.On call
//   - ctx context.Context
//   - data *dto.AuthAuditDTO
func (_e *MockAuthAuditFacade_Expecter) Audit(ctx interface{}, data interface{}) *MockAuthAuditFacade_Audit_Call {
	return &MockAuthAuditFacade_Audit_Call{Call: _e.mock.On("Audit", ctx, data)}
}

func (_c *MockAuthAuditFacade_Audit_Call) Run(run func(ctx context.Context, data *dto.AuthAuditDTO)) *MockAuthAuditFacade_Audit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.AuthAuditDTO
		if args[1] != nil {
			arg1 = args[1].(*dto.AuthAuditDTO)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthAuditFacade_Audit_Call) Return(err error) *MockAuthAuditFacade_Audit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthAuditFacade_Audit_Call) RunAndReturn(run func(ctx context.Context, data *dto.AuthAuditDTO) error) *MockAuthAuditFacade_Audit_Call {
	_c.Call.Return(run)
	return _c
}

// ListByPeriod provides a mock function for the type MockAuthAuditFacade
func (_mock *MockAuthAuditFacade) ListByPeriod(ctx context.Context, auditPeriod *dto.AuditPeriodDTO) ([]*dto.AuthAuditDTO, error) {
	ret := _mock.Called(ctx, auditPeriod)

	if len(ret) == 0 {
		panic("no return value specified for ListByPeriod")
	}

	var r0 []*dto.AuthAuditDTO
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.AuditPeriodDTO) ([]*dto.AuthAuditDTO, error)); ok {
		return returnFunc(ctx, auditPeriod)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.AuditPeriodDTO) []*dto.AuthAuditDTO); ok {
		r0 = returnFunc(ctx, auditPeriod)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.AuthAuditDTO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.AuditPeriodDTO) error); ok {
		r1 = returnFunc(ctx, auditPeriod)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthAuditFacade_ListByPeriod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByPeriod'
type MockAuthAuditFacade_ListByPeriod_Call struct {
	*mock.Call
}

// ListByPeriod is a helper method to define mock.On call
//   - ctx context.Context
//   - auditPeriod *dto.AuditPeriodDTO
func (_e *MockAuthAuditFacade_Expecter) ListByPeriod(ctx interface{}, auditPeriod interface{}) *MockAuthAuditFacade_ListByPeriod_Call {
	return &MockAuthAuditFacade_ListByPeriod_Call{Call: _e.mock.On("ListByPeriod", ctx, auditPeriod)}
}

func (_c *MockAuthAuditFacade_ListByPeriod_Call) Run(run func(ctx context.Context, auditPeriod *dto.AuditPeriodDTO)) *MockAuthAuditFacade_ListByPeriod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.AuditPeriodDTO
		if args[1] != nil {
			arg1 = args[1].(*dto.AuditPeriodDTO)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthAuditFacade_ListByPeriod_Call) Return(authAuditDTOs []*dto.AuthAuditDTO, err error) *MockAuthAuditFacade_ListByPeriod_Call {
	_c.Call.Return(authAuditDTOs, err)
	return _c
}

func (_c *MockAuthAuditFacade_ListByPeriod_Call) RunAndReturn(run func(ctx context.Context, auditPeriod *dto.AuditPeriodDTO) ([]*dto.AuthAuditDTO, error)) *MockAuthAuditFacade_ListByPeriod_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUsername provides a mock function for the type MockAuthAuditFacade
func (_mock *MockAuthAuditFacade) ListByUsername(ctx context.Context, auditUser *dto.AuditUserDTO) ([]*dto.AuthAuditDTO, error) {
	ret := _mock.Called(ctx, auditUser)

	if len(ret) == 0 {
		panic("no return value specified for ListByUsername")
	}

	var r0 []*dto.AuthAuditDTO
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.AuditUserDTO) ([]*dto.AuthAuditDTO, error)); ok {
		return returnFunc(ctx, auditUser)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.AuditUserDTO) []*dto.AuthAuditDTO); ok {
		r0 = returnFunc(ctx, auditUser)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.AuthAuditDTO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.AuditUserDTO) error); ok {
		r1 = returnFunc(ctx, auditUser)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthAuditFacade_ListByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUsername'
type MockAuthAuditFacade_ListByUsername_Call struct {
	*mock.Call
}

// ListByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - auditUser *dto.AuditUserDTO
func (_e *MockAuthAuditFacade_Expecter) ListByUsername(ctx interface{}, auditUser interface{}) *MockAuthAuditFacade_ListByUsername_Call {
	return &MockAuthAuditFacade_ListByUsername_Call{Call: _e.mock.On("ListByUsername", ctx, auditUser)}
}

func (_c *MockAuthAuditFacade_ListByUsername_Call) Run(run func(ctx context.Context, auditUser *dto.AuditUserDTO)) *MockAuthAuditFacade_ListByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.AuditUserDTO
		if args[1] != nil {
			arg1 = args[1].(*dto.AuditUserDTO)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthAuditFacade_ListByUsername_Call) Return(authAuditDTOs []*dto.AuthAuditDTO, err error) *MockAuthAuditFacade_ListByUsername_Call {
	_c.Call.Return(authAuditDTOs, err)
	return _c
}

func (_c *MockAuthAuditFacade_ListByUsername_Call) RunAndReturn(run func(ctx context.Context, auditUser *dto.AuditUserDTO) ([]*dto.AuthAuditDTO, error)) *MockAuthAuditFacade_ListByUsername_Call {
	_c.Call.Return(run)
	return _c
}
