// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ElfAstAhe/tiny-audit-service/internal/facade/dto"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthAudit creates a new instance of MockAuthAudit. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthAudit(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthAudit {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockAuthAudit{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockAuthAudit is an autogenerated mock type for the AuthAudit type
type MockAuthAudit struct {
	mock.Mock
}

type MockAuthAudit_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthAudit) EXPECT() *MockAuthAudit_Expecter {
	return &MockAuthAudit_Expecter{mock: &_m.Mock}
}

// Audit provides a mock function for the type MockAuthAudit
func (_mock *MockAuthAudit) Audit(ctx context.Context, data *dto.AuthAuditDTO) error {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Audit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.AuthAuditDTO) error); ok {
		r0 = returnFunc(ctx, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthAudit_Audit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Audit'
type MockAuthAudit_Audit_Call struct {
	*mock.Call
}

// Audit is a helper method to define mock.On call
//   - ctx context.Context
//   - data *dto.AuthAuditDTO
func (_e *MockAuthAudit_Expecter) Audit(ctx any, data any) *MockAuthAudit_Audit_Call {
	return &MockAuthAudit_Audit_Call{Call: _e.mock.On("Audit", ctx, data)}
}

func (_c *MockAuthAudit_Audit_Call) Run(run func(ctx context.Context, data *dto.AuthAuditDTO)) *MockAuthAudit_Audit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.AuthAuditDTO
		if args[1] != nil {
			arg1 = args[1].(*dto.AuthAuditDTO)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthAudit_Audit_Call) Return(err error) *MockAuthAudit_Audit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthAudit_Audit_Call) RunAndReturn(run func(ctx context.Context, data *dto.AuthAuditDTO) error) *MockAuthAudit_Audit_Call {
	_c.Call.Return(run)
	return _c
}

// ListByPeriod provides a mock function for the type MockAuthAudit
func (_mock *MockAuthAudit) ListByPeriod(ctx context.Context, auditPeriod *dto.AuditPeriodDTO) ([]*dto.AuthAuditDTO, error) {
	ret := _mock.Called(ctx, auditPeriod)

	if len(ret) == 0 {
		panic("no return value specified for ListByPeriod")
	}

	var r0 []*dto.AuthAuditDTO
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.AuditPeriodDTO) ([]*dto.AuthAuditDTO, error)); ok {
		return returnFunc(ctx, auditPeriod)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.AuditPeriodDTO) []*dto.AuthAuditDTO); ok {
		r0 = returnFunc(ctx, auditPeriod)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.AuthAuditDTO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.AuditPeriodDTO) error); ok {
		r1 = returnFunc(ctx, auditPeriod)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthAudit_ListByPeriod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByPeriod'
type MockAuthAudit_ListByPeriod_Call struct {
	*mock.Call
}

// ListByPeriod is a helper method to define mock.On call
//   - ctx context.Context
//   - auditPeriod *dto.AuditPeriodDTO
func (_e *MockAuthAudit_Expecter) ListByPeriod(ctx any, auditPeriod any) *MockAuthAudit_ListByPeriod_Call {
	return &MockAuthAudit_ListByPeriod_Call{Call: _e.mock.On("ListByPeriod", ctx, auditPeriod)}
}

func (_c *MockAuthAudit_ListByPeriod_Call) Run(run func(ctx context.Context, auditPeriod *dto.AuditPeriodDTO)) *MockAuthAudit_ListByPeriod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.AuditPeriodDTO
		if args[1] != nil {
			arg1 = args[1].(*dto.AuditPeriodDTO)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthAudit_ListByPeriod_Call) Return(authAuditDTOs []*dto.AuthAuditDTO, err error) *MockAuthAudit_ListByPeriod_Call {
	_c.Call.Return(authAuditDTOs, err)
	return _c
}

func (_c *MockAuthAudit_ListByPeriod_Call) RunAndReturn(run func(ctx context.Context, auditPeriod *dto.AuditPeriodDTO) ([]*dto.AuthAuditDTO, error)) *MockAuthAudit_ListByPeriod_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUsername provides a mock function for the type MockAuthAudit
func (_mock *MockAuthAudit) ListByUsername(ctx context.Context, auditUser *dto.AuditUserDTO) ([]*dto.AuthAuditDTO, error) {
	ret := _mock.Called(ctx, auditUser)

	if len(ret) == 0 {
		panic("no return value specified for ListByUsername")
	}

	var r0 []*dto.AuthAuditDTO
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.AuditUserDTO) ([]*dto.AuthAuditDTO, error)); ok {
		return returnFunc(ctx, auditUser)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.AuditUserDTO) []*dto.AuthAuditDTO); ok {
		r0 = returnFunc(ctx, auditUser)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.AuthAuditDTO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.AuditUserDTO) error); ok {
		r1 = returnFunc(ctx, auditUser)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthAudit_ListByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUsername'
type MockAuthAudit_ListByUsername_Call struct {
	*mock.Call
}

// ListByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - auditUser *dto.AuditUserDTO
func (_e *MockAuthAudit_Expecter) ListByUsername(ctx any, auditUser any) *MockAuthAudit_ListByUsername_Call {
	return &MockAuthAudit_ListByUsername_Call{Call: _e.mock.On("ListByUsername", ctx, auditUser)}
}

func (_c *MockAuthAudit_ListByUsername_Call) Run(run func(ctx context.Context, auditUser *dto.AuditUserDTO)) *MockAuthAudit_ListByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.AuditUserDTO
		if args[1] != nil {
			arg1 = args[1].(*dto.AuditUserDTO)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthAudit_ListByUsername_Call) Return(authAuditDTOs []*dto.AuthAuditDTO, err error) *MockAuthAudit_ListByUsername_Call {
	_c.Call.Return(authAuditDTOs, err)
	return _c
}

func (_c *MockAuthAudit_ListByUsername_Call) RunAndReturn(run func(ctx context.Context, auditUser *dto.AuditUserDTO) ([]*dto.AuthAuditDTO, error)) *MockAuthAudit_ListByUsername_Call {
	_c.Call.Return(run)
	return _c
}
