// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuditable creates a new instance of MockAuditable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuditable(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuditable {
	mock := &MockAuditable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuditable is an autogenerated mock type for the Auditable type
type MockAuditable struct {
	mock.Mock
}

type MockAuditable_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuditable) EXPECT() *MockAuditable_Expecter {
	return &MockAuditable_Expecter{mock: &_m.Mock}
}

// GetInstanceID provides a mock function for the type MockAuditable
func (_mock *MockAuditable) GetInstanceID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetInstanceID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockAuditable_GetInstanceID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInstanceID'
type MockAuditable_GetInstanceID_Call struct {
	*mock.Call
}

// GetInstanceID is a helper method to define mock.On call
func (_e *MockAuditable_Expecter) GetInstanceID() *MockAuditable_GetInstanceID_Call {
	return &MockAuditable_GetInstanceID_Call{Call: _e.mock.On("GetInstanceID")}
}

func (_c *MockAuditable_GetInstanceID_Call) Run(run func()) *MockAuditable_GetInstanceID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAuditable_GetInstanceID_Call) Return(s string) *MockAuditable_GetInstanceID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockAuditable_GetInstanceID_Call) RunAndReturn(run func() string) *MockAuditable_GetInstanceID_Call {
	_c.Call.Return(run)
	return _c
}

// GetInstanceName provides a mock function for the type MockAuditable
func (_mock *MockAuditable) GetInstanceName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetInstanceName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockAuditable_GetInstanceName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInstanceName'
type MockAuditable_GetInstanceName_Call struct {
	*mock.Call
}

// GetInstanceName is a helper method to define mock.On call
func (_e *MockAuditable_Expecter) GetInstanceName() *MockAuditable_GetInstanceName_Call {
	return &MockAuditable_GetInstanceName_Call{Call: _e.mock.On("GetInstanceName")}
}

func (_c *MockAuditable_GetInstanceName_Call) Run(run func()) *MockAuditable_GetInstanceName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAuditable_GetInstanceName_Call) Return(s string) *MockAuditable_GetInstanceName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockAuditable_GetInstanceName_Call) RunAndReturn(run func() string) *MockAuditable_GetInstanceName_Call {
	_c.Call.Return(run)
	return _c
}

// GetInternalTypeName provides a mock function for the type MockAuditable
func (_mock *MockAuditable) GetInternalTypeName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetInternalTypeName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockAuditable_GetInternalTypeName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInternalTypeName'
type MockAuditable_GetInternalTypeName_Call struct {
	*mock.Call
}

// GetInternalTypeName is a helper method to define mock.On call
func (_e *MockAuditable_Expecter) GetInternalTypeName() *MockAuditable_GetInternalTypeName_Call {
	return &MockAuditable_GetInternalTypeName_Call{Call: _e.mock.On("GetInternalTypeName")}
}

func (_c *MockAuditable_GetInternalTypeName_Call) Run(run func()) *MockAuditable_GetInternalTypeName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAuditable_GetInternalTypeName_Call) Return(s string) *MockAuditable_GetInternalTypeName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockAuditable_GetInternalTypeName_Call) RunAndReturn(run func() string) *MockAuditable_GetInternalTypeName_Call {
	_c.Call.Return(run)
	return _c
}

// GetTypeDescription provides a mock function for the type MockAuditable
func (_mock *MockAuditable) GetTypeDescription() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTypeDescription")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockAuditable_GetTypeDescription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTypeDescription'
type MockAuditable_GetTypeDescription_Call struct {
	*mock.Call
}

// GetTypeDescription is a helper method to define mock.On call
func (_e *MockAuditable_Expecter) GetTypeDescription() *MockAuditable_GetTypeDescription_Call {
	return &MockAuditable_GetTypeDescription_Call{Call: _e.mock.On("GetTypeDescription")}
}

func (_c *MockAuditable_GetTypeDescription_Call) Run(run func()) *MockAuditable_GetTypeDescription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAuditable_GetTypeDescription_Call) Return(s string) *MockAuditable_GetTypeDescription_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockAuditable_GetTypeDescription_Call) RunAndReturn(run func() string) *MockAuditable_GetTypeDescription_Call {
	_c.Call.Return(run)
	return _c
}

// GetTypeName provides a mock function for the type MockAuditable
func (_mock *MockAuditable) GetTypeName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTypeName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockAuditable_GetTypeName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTypeName'
type MockAuditable_GetTypeName_Call struct {
	*mock.Call
}

// GetTypeName is a helper method to define mock.On call
func (_e *MockAuditable_Expecter) GetTypeName() *MockAuditable_GetTypeName_Call {
	return &MockAuditable_GetTypeName_Call{Call: _e.mock.On("GetTypeName")}
}

func (_c *MockAuditable_GetTypeName_Call) Run(run func()) *MockAuditable_GetTypeName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAuditable_GetTypeName_Call) Return(s string) *MockAuditable_GetTypeName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockAuditable_GetTypeName_Call) RunAndReturn(run func() string) *MockAuditable_GetTypeName_Call {
	_c.Call.Return(run)
	return _c
}

// HashCode provides a mock function for the type MockAuditable
func (_mock *MockAuditable) HashCode() uint32 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for HashCode")
	}

	var r0 uint32
	if returnFunc, ok := ret.Get(0).(func() uint32); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(uint32)
	}
	return r0
}

// MockAuditable_HashCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HashCode'
type MockAuditable_HashCode_Call struct {
	*mock.Call
}

// HashCode is a helper method to define mock.On call
func (_e *MockAuditable_Expecter) HashCode() *MockAuditable_HashCode_Call {
	return &MockAuditable_HashCode_Call{Call: _e.mock.On("HashCode")}
}

func (_c *MockAuditable_HashCode_Call) Run(run func()) *MockAuditable_HashCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAuditable_HashCode_Call) Return(v uint32) *MockAuditable_HashCode_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockAuditable_HashCode_Call) RunAndReturn(run func() uint32) *MockAuditable_HashCode_Call {
	_c.Call.Return(run)
	return _c
}

// ToAuditMap provides a mock function for the type MockAuditable
func (_mock *MockAuditable) ToAuditMap() map[string]string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ToAuditMap")
	}

	var r0 map[string]string
	if returnFunc, ok := ret.Get(0).(func() map[string]string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}
	return r0
}

// MockAuditable_ToAuditMap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToAuditMap'
type MockAuditable_ToAuditMap_Call struct {
	*mock.Call
}

// ToAuditMap is a helper method to define mock.On call
func (_e *MockAuditable_Expecter) ToAuditMap() *MockAuditable_ToAuditMap_Call {
	return &MockAuditable_ToAuditMap_Call{Call: _e.mock.On("ToAuditMap")}
}

func (_c *MockAuditable_ToAuditMap_Call) Run(run func()) *MockAuditable_ToAuditMap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAuditable_ToAuditMap_Call) Return(stringToString map[string]string) *MockAuditable_ToAuditMap_Call {
	_c.Call.Return(stringToString)
	return _c
}

func (_c *MockAuditable_ToAuditMap_Call) RunAndReturn(run func() map[string]string) *MockAuditable_ToAuditMap_Call {
	_c.Call.Return(run)
	return _c
}
